// GENERATED from product/mint_next/batch16/six-locale-semantic-fixture.yaml.
// Do not edit by hand.
const batch16SemanticFixture = <String, Map<String, String>>{
  "fr": <String, String>{
    "batch16AnnualOrdinaryTotalMeaning": "Saisis une seule fois, pour chaque prestataire, le total annuel des cotisations ordinaires indiqué sur son attestation annuelle.",
    "batch16ActuallyCreditedMeaning": "Compte uniquement ce qui a réellement été crédité pour {taxYear}, pas ce qui était prévu, envoyé ou débité.",
    "batch16ExcludedMovementsMeaning": "N’inclus pas les transferts, rachats rétroactifs, mouvements en attente, remboursements ni gains de placement.",
    "batch16ProviderConfirmedNetMeaning": "Après une correction ou un remboursement, demande au prestataire son total net confirmé des cotisations ordinaires; ne soustrais rien toi-même.",
    "batch16InsuranceCertificateMeaning": "Pour une assurance, utilise l’attestation annuelle; n’utilise ni la valeur de rachat ni la répartition risque/épargne.",
    "batch16RefundVsAllZeroMeaning": "Le remboursement intégral d’un prestataire ne signifie pas que tous les prestataires sont à zéro.",
    "batch16MintNotVerifiedMeaning": "MINT n’a pas vérifié le montant saisi.",
    "batch16NoTaxAdviceMeaning": "Cette étape ne produit ni résultat fiscal ni recommandation.",
  },
  "en": <String, String>{
    "batch16AnnualOrdinaryTotalMeaning": "Enter once, for each provider, the annual total of ordinary contributions shown on its annual certificate.",
    "batch16ActuallyCreditedMeaning": "Count only what was actually credited for {taxYear}, not what was planned, sent or debited.",
    "batch16ExcludedMovementsMeaning": "Do not include transfers, retroactive buy-ins, pending movements, refunds or investment gains.",
    "batch16ProviderConfirmedNetMeaning": "After a correction or refund, ask the provider for its confirmed net total of ordinary contributions; do not subtract anything yourself.",
    "batch16InsuranceCertificateMeaning": "For insurance, use the annual certificate; use neither the surrender value nor the risk/savings split.",
    "batch16RefundVsAllZeroMeaning": "A full refund from one provider does not mean that all providers are at zero.",
    "batch16MintNotVerifiedMeaning": "MINT has not verified the amount entered.",
    "batch16NoTaxAdviceMeaning": "This step produces neither a tax result nor a recommendation.",
  },
  "de": <String, String>{
    "batch16AnnualOrdinaryTotalMeaning": "Erfasse für jeden Anbieter einmal den Jahrestotalbetrag der ordentlichen Beiträge aus seiner Jahresbescheinigung.",
    "batch16ActuallyCreditedMeaning": "Zähle nur, was für {taxYear} tatsächlich gutgeschrieben wurde, nicht was geplant, überwiesen oder belastet wurde.",
    "batch16ExcludedMovementsMeaning": "Schliesse Überträge, rückwirkende Einkäufe, ausstehende Bewegungen, Rückerstattungen und Anlagegewinne aus.",
    "batch16ProviderConfirmedNetMeaning": "Frage den Anbieter nach einer Korrektur oder Rückerstattung nach dem bestätigten Nettototal der ordentlichen Beiträge; ziehe selbst nichts ab.",
    "batch16InsuranceCertificateMeaning": "Verwende bei einer Versicherung die Jahresbescheinigung; nutze weder den Rückkaufswert noch die Aufteilung in Risiko und Sparen.",
    "batch16RefundVsAllZeroMeaning": "Eine vollständige Rückerstattung eines Anbieters bedeutet nicht, dass bei allen Anbietern null verbleibt.",
    "batch16MintNotVerifiedMeaning": "MINT hat den eingegebenen Betrag nicht überprüft.",
    "batch16NoTaxAdviceMeaning": "Dieser Schritt liefert weder ein Steuerergebnis noch eine Empfehlung.",
  },
  "it": <String, String>{
    "batch16AnnualOrdinaryTotalMeaning": "Inserisci una sola volta, per ogni offerente, il totale annuo dei contributi ordinari indicato nell’attestazione annuale.",
    "batch16ActuallyCreditedMeaning": "Considera solo quanto è stato effettivamente accreditato per il {taxYear}, non quanto era previsto, inviato o addebitato.",
    "batch16ExcludedMovementsMeaning": "Non includere trasferimenti, versamenti retroattivi, movimenti in sospeso, rimborsi o guadagni d’investimento.",
    "batch16ProviderConfirmedNetMeaning": "Dopo una correzione o un rimborso, chiedi all’offerente il totale netto confermato dei contributi ordinari; non sottrarre nulla autonomamente.",
    "batch16InsuranceCertificateMeaning": "Per un’assicurazione usa l’attestazione annuale; non usare né il valore di riscatto né la ripartizione rischio/risparmio.",
    "batch16RefundVsAllZeroMeaning": "Il rimborso integrale di un offerente non significa che tutti gli offerenti siano a zero.",
    "batch16MintNotVerifiedMeaning": "MINT non ha verificato l’importo inserito.",
    "batch16NoTaxAdviceMeaning": "Questo passaggio non produce né un risultato fiscale né una raccomandazione.",
  },
  "es": <String, String>{
    "batch16AnnualOrdinaryTotalMeaning": "Introduce una sola vez, para cada proveedor, el total anual de las aportaciones ordinarias indicado en su certificado anual.",
    "batch16ActuallyCreditedMeaning": "Cuenta solo lo que se abonó realmente para {taxYear}, no lo que estaba previsto, se envió o se cargó.",
    "batch16ExcludedMovementsMeaning": "No incluyas transferencias, aportaciones retroactivas, movimientos pendientes, reembolsos ni ganancias de inversión.",
    "batch16ProviderConfirmedNetMeaning": "Tras una corrección o un reembolso, pide al proveedor el total neto confirmado de las aportaciones ordinarias; no restes nada por tu cuenta.",
    "batch16InsuranceCertificateMeaning": "Para un seguro, utiliza el certificado anual; no uses ni el valor de rescate ni el reparto entre riesgo y ahorro.",
    "batch16RefundVsAllZeroMeaning": "El reembolso íntegro de un proveedor no significa que todos los proveedores estén a cero.",
    "batch16MintNotVerifiedMeaning": "MINT no ha verificado el importe introducido.",
    "batch16NoTaxAdviceMeaning": "Este paso no produce ni un resultado fiscal ni una recomendación.",
  },
  "pt": <String, String>{
    "batch16AnnualOrdinaryTotalMeaning": "Introduz uma única vez, para cada prestador, o total anual das contribuições ordinárias indicado no certificado anual.",
    "batch16ActuallyCreditedMeaning": "Conta apenas o que foi efetivamente creditado para {taxYear}, não o que estava previsto, foi enviado ou debitado.",
    "batch16ExcludedMovementsMeaning": "Não incluas transferências, contribuições retroativas, movimentos pendentes, reembolsos nem ganhos de investimento.",
    "batch16ProviderConfirmedNetMeaning": "Após uma correção ou um reembolso, pede ao prestador o total líquido confirmado das contribuições ordinárias; não subtraias nada por tua conta.",
    "batch16InsuranceCertificateMeaning": "Para um seguro, utiliza o certificado anual; não uses nem o valor de resgate nem a repartição entre risco e poupança.",
    "batch16RefundVsAllZeroMeaning": "O reembolso integral de um prestador não significa que todos os prestadores estejam a zero.",
    "batch16MintNotVerifiedMeaning": "A MINT não verificou o montante introduzido.",
    "batch16NoTaxAdviceMeaning": "Este passo não produz qualquer resultado fiscal nem recomendação.",
  },
};
