// Generated from the accepted Batch17 copy; guarded by Batch19.
// Do not edit by hand.

const batch18CantonFixtureSourceSha256 =
    '3c6d19a37dee264bf5bd0b9e80151eac2796b6a517ddd82a96feb397c49050fe';

const batch18AllowedCantonCodes = <String>{
  "AG",
  "AI",
  "AR",
  "BE",
  "BL",
  "BS",
  "FR",
  "GE",
  "GL",
  "GR",
  "JU",
  "LU",
  "NE",
  "NW",
  "OW",
  "SG",
  "SH",
  "SO",
  "SZ",
  "TG",
  "TI",
  "UR",
  "VD",
  "VS",
  "ZG",
  "ZH",
};

const batch18CantonLabels = <String, Map<String, String>>{
  "fr": <String, String>{
    "AG": "Argovie",
    "AI": "Appenzell Rhodes-Intérieures",
    "AR": "Appenzell Rhodes-Extérieures",
    "BE": "Berne",
    "BL": "Bâle-Campagne",
    "BS": "Bâle-Ville",
    "FR": "Fribourg",
    "GE": "Genève",
    "GL": "Glaris",
    "GR": "Grisons",
    "JU": "Jura",
    "LU": "Lucerne",
    "NE": "Neuchâtel",
    "NW": "Nidwald",
    "OW": "Obwald",
    "SG": "Saint-Gall",
    "SH": "Schaffhouse",
    "SO": "Soleure",
    "SZ": "Schwytz",
    "TG": "Thurgovie",
    "TI": "Tessin",
    "UR": "Uri",
    "VD": "Vaud",
    "VS": "Valais",
    "ZG": "Zoug",
    "ZH": "Zurich",
  },
  "en": <String, String>{
    "AG": "Aargau",
    "AI": "Appenzell Innerrhoden",
    "AR": "Appenzell Ausserrhoden",
    "BE": "Bern",
    "BL": "Basel-Landschaft",
    "BS": "Basel-Stadt",
    "FR": "Fribourg",
    "GE": "Geneva",
    "GL": "Glarus",
    "GR": "Graubünden",
    "JU": "Jura",
    "LU": "Lucerne",
    "NE": "Neuchâtel",
    "NW": "Nidwalden",
    "OW": "Obwalden",
    "SG": "St. Gallen",
    "SH": "Schaffhausen",
    "SO": "Solothurn",
    "SZ": "Schwyz",
    "TG": "Thurgau",
    "TI": "Ticino",
    "UR": "Uri",
    "VD": "Vaud",
    "VS": "Valais",
    "ZG": "Zug",
    "ZH": "Zurich",
  },
  "de": <String, String>{
    "AG": "Aargau",
    "AI": "Appenzell Innerrhoden",
    "AR": "Appenzell Ausserrhoden",
    "BE": "Bern",
    "BL": "Basel-Landschaft",
    "BS": "Basel-Stadt",
    "FR": "Freiburg",
    "GE": "Genf",
    "GL": "Glarus",
    "GR": "Graubünden",
    "JU": "Jura",
    "LU": "Luzern",
    "NE": "Neuenburg",
    "NW": "Nidwalden",
    "OW": "Obwalden",
    "SG": "St. Gallen",
    "SH": "Schaffhausen",
    "SO": "Solothurn",
    "SZ": "Schwyz",
    "TG": "Thurgau",
    "TI": "Tessin",
    "UR": "Uri",
    "VD": "Waadt",
    "VS": "Wallis",
    "ZG": "Zug",
    "ZH": "Zürich",
  },
  "it": <String, String>{
    "AG": "Argovia",
    "AI": "Appenzello Interno",
    "AR": "Appenzello Esterno",
    "BE": "Berna",
    "BL": "Basilea Campagna",
    "BS": "Basilea Città",
    "FR": "Friburgo",
    "GE": "Ginevra",
    "GL": "Glarona",
    "GR": "Grigioni",
    "JU": "Giura",
    "LU": "Lucerna",
    "NE": "Neuchâtel",
    "NW": "Nidvaldo",
    "OW": "Obvaldo",
    "SG": "San Gallo",
    "SH": "Sciaffusa",
    "SO": "Soletta",
    "SZ": "Svitto",
    "TG": "Turgovia",
    "TI": "Ticino",
    "UR": "Uri",
    "VD": "Vaud",
    "VS": "Vallese",
    "ZG": "Zugo",
    "ZH": "Zurigo",
  },
  "es": <String, String>{
    "AG": "Argovia",
    "AI": "Appenzell Rodas Interiores",
    "AR": "Appenzell Rodas Exteriores",
    "BE": "Berna",
    "BL": "Basilea-Campiña",
    "BS": "Basilea-Ciudad",
    "FR": "Friburgo",
    "GE": "Ginebra",
    "GL": "Glaris",
    "GR": "Grisones",
    "JU": "Jura",
    "LU": "Lucerna",
    "NE": "Neuchâtel",
    "NW": "Nidwalden",
    "OW": "Obwalden",
    "SG": "San Galo",
    "SH": "Schaffhausen",
    "SO": "Soleura",
    "SZ": "Schwyz",
    "TG": "Turgovia",
    "TI": "Tesino",
    "UR": "Uri",
    "VD": "Vaud",
    "VS": "Valais",
    "ZG": "Zug",
    "ZH": "Zúrich",
  },
  "pt": <String, String>{
    "AG": "Argóvia",
    "AI": "Appenzell Interior",
    "AR": "Appenzell Exterior",
    "BE": "Berna",
    "BL": "Basileia-Campo",
    "BS": "Basileia-Cidade",
    "FR": "Friburgo",
    "GE": "Genebra",
    "GL": "Glaris",
    "GR": "Grisões",
    "JU": "Jura",
    "LU": "Lucerna",
    "NE": "Neuchâtel",
    "NW": "Nidwalden",
    "OW": "Obwalden",
    "SG": "São Galo",
    "SH": "Schaffhausen",
    "SO": "Soleura",
    "SZ": "Schwyz",
    "TG": "Turgóvia",
    "TI": "Ticino",
    "UR": "Uri",
    "VD": "Vaud",
    "VS": "Valais",
    "ZG": "Zug",
    "ZH": "Zurique",
  },
};

const batch18CantonOrder = <String, List<String>>{
  "fr": <String>[
    "AR",
    "AI",
    "AG",
    "BL",
    "BS",
    "BE",
    "FR",
    "GE",
    "GL",
    "GR",
    "JU",
    "LU",
    "NE",
    "NW",
    "OW",
    "SG",
    "SH",
    "SZ",
    "SO",
    "TI",
    "TG",
    "UR",
    "VS",
    "VD",
    "ZG",
    "ZH",
  ],
  "en": <String>[
    "AG",
    "AR",
    "AI",
    "BL",
    "BS",
    "BE",
    "FR",
    "GE",
    "GL",
    "GR",
    "JU",
    "LU",
    "NE",
    "NW",
    "OW",
    "SH",
    "SZ",
    "SO",
    "SG",
    "TG",
    "TI",
    "UR",
    "VS",
    "VD",
    "ZG",
    "ZH",
  ],
  "de": <String>[
    "AG",
    "AR",
    "AI",
    "BL",
    "BS",
    "BE",
    "FR",
    "GE",
    "GL",
    "GR",
    "JU",
    "LU",
    "NE",
    "NW",
    "OW",
    "SH",
    "SZ",
    "SO",
    "SG",
    "TI",
    "TG",
    "UR",
    "VD",
    "VS",
    "ZG",
    "ZH",
  ],
  "it": <String>[
    "AR",
    "AI",
    "AG",
    "BL",
    "BS",
    "BE",
    "FR",
    "GE",
    "JU",
    "GL",
    "GR",
    "LU",
    "NE",
    "NW",
    "OW",
    "SG",
    "SH",
    "SO",
    "SZ",
    "TI",
    "TG",
    "UR",
    "VS",
    "VD",
    "ZG",
    "ZH",
  ],
  "es": <String>[
    "AR",
    "AI",
    "AG",
    "BL",
    "BS",
    "BE",
    "FR",
    "GE",
    "GL",
    "GR",
    "JU",
    "LU",
    "NE",
    "NW",
    "OW",
    "SG",
    "SH",
    "SZ",
    "SO",
    "TI",
    "TG",
    "UR",
    "VS",
    "VD",
    "ZG",
    "ZH",
  ],
  "pt": <String>[
    "AR",
    "AI",
    "AG",
    "BL",
    "BS",
    "BE",
    "FR",
    "GE",
    "GL",
    "GR",
    "JU",
    "LU",
    "NE",
    "NW",
    "OW",
    "SG",
    "SH",
    "SZ",
    "SO",
    "TI",
    "TG",
    "UR",
    "VS",
    "VD",
    "ZG",
    "ZH",
  ],
};
