"""Phase mint-calc-engine-v1 Plan 14 — D-CE-14 reverse-dep map contract tests.

Verifies ``REVERSE_DEP_MAP`` (auto-generated by ``tools/generate_calc_registry.py``
alongside ``REGISTRY`` per Override #5 « kills two birds ») has the shape Plan 15
(BackgroundTasks pre-compute) expects.

Test budget : 7 tests per PLAN.md Task 1 <behavior> spec. Note that the registry
artifact + map are already shipped by Plan 05 (« reverse-dep map seed »); Plan 14
ships the dedicated test surface + locks down the API contract for Plan 15.

References
----------
- mint-calc-engine-v1-14-w3-reverse-dep-map-PLAN.md
- mint-calc-engine-v1-CONTEXT.md §D-CE-14
- mint-calc-engine-v1-VALIDATION.md Q4 (direct deps only in v1)
- Plan 05 SUMMARY (146 fields, 25 calcs depend on canton, 63 calcs)

Deviation note for Test 5
-------------------------
PLAN.md Task 1 Test 5 reads :

  > « REVERSE_DEP_MAP keys are all valid profile field names from
  >   `_PROFILE_SAFE_FIELDS` canonical list at `coach_chat.py:875` (no drift). »

This is conceptually inverted : ``_PROFILE_SAFE_FIELDS`` is a PII whitelist for
the **LLM coach context** (56 narrow user-facing fields exposed to Claude), while
``REVERSE_DEP_MAP`` keys are the **internal profile fields each calculator declares
as needed** (146 fields, many of which are calculator-internal intermediate values
like ``taux_marginal``, ``a3a_maxed``, ``rendement_3a``). The two sets are
deliberately different — only 7 fields overlap (``age``, ``canton``,
``conjoint_age``, ``conjoint_salary``, ``has_debt``, ``marital_status``,
``primary_focus``).

The drift-style assertion the plan envisions only makes sense in the reverse
direction : the **intersection between the LLM-safe whitelist and REVERSE_DEP_MAP
keys** should contain the canonical anchor fields (``canton``, ``age``). That's
what Test 5 below asserts. Documented as Rule 1 deviation in SUMMARY.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path



# tests/ → services/backend/ → MINT.nosync/
PROJECT_ROOT = Path(__file__).resolve().parents[3]
GENERATOR_PATH = PROJECT_ROOT / "tools" / "generate_calc_registry.py"


# ---------------------------------------------------------------------------
# Test 1 — map non-empty
# ---------------------------------------------------------------------------


def test_reverse_dep_map_is_non_empty_dict():
    """``REVERSE_DEP_MAP`` is a dict with at least 5 keys (D-CE-14 floor)."""
    from app.calculators import REVERSE_DEP_MAP

    assert isinstance(REVERSE_DEP_MAP, dict)
    assert len(REVERSE_DEP_MAP) >= 5, (
        f"REVERSE_DEP_MAP has only {len(REVERSE_DEP_MAP)} keys ; "
        "Plan 05 baseline was 146. Has the generator regressed ?"
    )


# ---------------------------------------------------------------------------
# Test 2 — canton is the widespread anchor (≥20 calcs)
# ---------------------------------------------------------------------------


def test_reverse_dep_map_canton_has_min_twenty_calcs():
    """``canton`` is the canonical wide-spread anchor field ; ≥20 calcs depend on it.

    Per PLAN.md acceptance criterion : « `canton` field deps ≥10 (≥20 ideal) ».
    Plan 05 baseline shipped 25. This test locks the floor at 20 so any future
    heuristic narrowing can be caught before it lands.
    """
    from app.calculators import REVERSE_DEP_MAP

    canton_deps = REVERSE_DEP_MAP.get("canton", set())
    assert isinstance(canton_deps, set)
    assert len(canton_deps) >= 20, (
        f"canton has only {len(canton_deps)} dependent calcs ; "
        "Plan 05 baseline was 25. Drop below 20 = the heuristic widening "
        "from Plan 05 is being undone, investigate before merging."
    )


# ---------------------------------------------------------------------------
# Test 3 — age has ≥5 calc deps
# ---------------------------------------------------------------------------


def test_reverse_dep_map_age_has_min_five_calcs():
    """``age`` is another wide-spread anchor ; ≥5 calcs depend on it."""
    from app.calculators import REVERSE_DEP_MAP

    age_deps = REVERSE_DEP_MAP.get("age", set())
    assert isinstance(age_deps, set)
    assert len(age_deps) >= 5, (
        f"age has only {len(age_deps)} dependent calcs ; "
        "Plan 05 baseline was 6."
    )


# ---------------------------------------------------------------------------
# Test 4 — unknown field returns empty set (does not raise)
# ---------------------------------------------------------------------------


def test_get_reverse_deps_unknown_field_returns_empty_set():
    """``get_reverse_deps(unknown)`` returns empty set, never raises.

    Critical for Plan 15 BackgroundTasks : the orchestrator iterates over
    arbitrary profile-field-mutation keys and must NOT raise if a key is not
    in the static dep map (e.g. user-defined custom fields, deprecated fields).
    """
    from app.calculators import get_reverse_deps

    deps = get_reverse_deps("nonexistent_field_xyz_42")
    assert deps == set()
    # Edge case : empty string is treated the same way.
    assert get_reverse_deps("") == set()


# ---------------------------------------------------------------------------
# Test 5 — anchor fields from _PROFILE_SAFE_FIELDS are present in the map
# ---------------------------------------------------------------------------


def test_reverse_dep_map_includes_pii_safe_anchor_fields():
    """The canonical anchor fields shared between PII-safe LLM whitelist and
    internal calculator deps (``canton``, ``age``) must appear in the map.

    Reframed from PLAN.md Test 5 — see module docstring for rationale.
    The original Test 5 assertion (« REVERSE_DEP_MAP keys ⊆ _PROFILE_SAFE_FIELDS »)
    is conceptually inverted because the two sets describe different concerns :
    PII safety (56 LLM-facing fields) vs internal calculator deps (146 fields
    including calculator-internal intermediates like ``taux_marginal``).
    The well-formed assertion is that the *intersection* contains the anchors.
    """
    from app.calculators import REVERSE_DEP_MAP
    from app.api.v1.endpoints.coach_chat import _PROFILE_SAFE_FIELDS

    rev_keys = set(REVERSE_DEP_MAP.keys())
    intersection = rev_keys & _PROFILE_SAFE_FIELDS

    # Canonical anchors that exist in BOTH the PII-safe whitelist and the
    # internal calculator dep map. ``canton`` + ``age`` are the must-haves.
    must_have_anchors = {"canton", "age"}
    missing = must_have_anchors - intersection
    assert not missing, (
        f"Canonical anchor fields missing from REVERSE_DEP_MAP ∩ "
        f"_PROFILE_SAFE_FIELDS : {sorted(missing)}. "
        "These are the bridge fields Plan 15 pre-compute relies on to drive "
        "downstream cache invalidation when the LLM updates user profile."
    )

    # Plan-level smoke check : the bridge intersection is non-trivial (≥5).
    assert len(intersection) >= 5, (
        f"REVERSE_DEP_MAP ∩ _PROFILE_SAFE_FIELDS has only "
        f"{len(intersection)} fields ({sorted(intersection)}). "
        "Expected at least 5 bridge fields for Plan 15 pre-compute coverage."
    )


# ---------------------------------------------------------------------------
# Test 6 — regeneration is idempotent
# ---------------------------------------------------------------------------


def test_reverse_dep_map_regeneration_is_idempotent():
    """``python3 tools/generate_calc_registry.py --check`` exits 0 immediately
    after a fresh write.

    Locks the « D-CE-14 kills two birds » contract : if a future commit modifies
    ``_registry.py`` by hand (forbidden), the next ``--check`` run fails CI.
    """
    result = subprocess.run(
        [sys.executable, str(GENERATOR_PATH), "--check"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, (
        f"generate_calc_registry.py --check failed with exit "
        f"{result.returncode}.\nstdout : {result.stdout}\nstderr : {result.stderr}"
    )


# ---------------------------------------------------------------------------
# Test 7 — every value in REVERSE_DEP_MAP is a set of names ALL in REGISTRY
# ---------------------------------------------------------------------------


def test_reverse_dep_map_values_are_all_valid_calc_names():
    """No orphan : every calc name in any REVERSE_DEP_MAP value set must
    exist as a key in REGISTRY.

    Catches regressions where the generator emits a stale calc name (e.g.
    if a service file is renamed but the dep map is not regenerated).
    """
    from app.calculators import REGISTRY, REVERSE_DEP_MAP

    registry_keys = set(REGISTRY.keys())
    orphans: dict[str, set[str]] = {}
    for field, calcs in REVERSE_DEP_MAP.items():
        assert isinstance(calcs, set), (
            f"REVERSE_DEP_MAP[{field!r}] is {type(calcs).__name__}, expected set"
        )
        bad = calcs - registry_keys
        if bad:
            orphans[field] = bad

    assert not orphans, (
        f"REVERSE_DEP_MAP has {sum(len(v) for v in orphans.values())} orphan "
        f"calc names across {len(orphans)} fields. Sample : "
        f"{dict(list(orphans.items())[:3])}"
    )
