"""Phase 95 Plan 95-03 / TEST-03 — alembic forward+rollback+check ladder.

Generalises the Phase 93-01 seed (`test_alembic_audit_log_forward_rollback.py`)
from one migration (p93_coach_message_audit) to the WHOLE alembic chain
under `services/backend/alembic/versions/` (currently 21+ files).

Closes the « `eclairage_delivered does not exist` » class of Sentry
incident: SQLite tolerates schema drift silently, Postgres `alembic
check` is strict and would have caught the bug at PR-time, not staging-
time.

Five tests, all marked `pytest.mark.postgres`:
  1. test_full_forward — alembic upgrade head from base; assert HEAD
     reached without exception.
  2. test_alembic_check_clean — alembic check after forward; asserts no
     diff between SQLAlchemy models and applied migrations (the actual
     « column does not exist » detector).
  3. test_full_rollback — alembic downgrade base; asserts no exception
     and current revision == None.
  4. test_full_forward_idempotent — second upgrade head; asserts no
     exception (idempotency guard inherited from p93 seed pattern).
  5. test_revision_graph_linear — walks every revision via
     `ScriptDirectory.from_config`; asserts the chain has zero gaps and
     that the known merge node `5f7922bff82b_merge_p11_and_p15` is the
     only multi-parent revision.

Skips automatically when Docker is unavailable (per `postgres_container`
fixture in conftest.py).
"""

from __future__ import annotations

import os

import pytest
from alembic import command
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import inspect


pytestmark = pytest.mark.postgres


_BACKEND_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), os.pardir)
)


def _make_config(url: str) -> Config:
    """Build an alembic Config pointing at the given DATABASE_URL."""
    cfg = Config(os.path.join(_BACKEND_DIR, "alembic.ini"))
    cfg.set_main_option("sqlalchemy.url", url)
    return cfg


@pytest.fixture
def alembic_cfg(pg_engine):
    """Per-test alembic Config bound to the testcontainers Postgres URL.

    Each test that needs to mutate revision state ALSO sets DATABASE_URL
    in the env so env.py picks up the right URL when alembic.command
    drives the migration.
    """
    url = str(pg_engine.url)
    prev = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = url
    try:
        yield _make_config(url)
    finally:
        if prev is None:
            os.environ.pop("DATABASE_URL", None)
        else:
            os.environ["DATABASE_URL"] = prev


# ---------------------------------------------------------------------------
# 1. Full forward upgrade — base → head.
# ---------------------------------------------------------------------------


def test_full_forward(pg_engine, alembic_cfg):
    """`alembic upgrade head` from any state lands on the script HEAD revision.

    pg_engine already runs upgrade head once on session setup; this test
    asserts a SECOND `upgrade head` is a no-op and that the recorded
    revision in alembic_version matches the script directory HEAD.
    """
    command.upgrade(alembic_cfg, "head")

    script = ScriptDirectory.from_config(alembic_cfg)
    expected_heads = set(script.get_heads())
    assert expected_heads, "alembic script directory has no head revisions"

    with pg_engine.connect() as conn:
        result = conn.exec_driver_sql(
            "SELECT version_num FROM alembic_version"
        ).fetchall()
    actual = {row[0] for row in result}
    assert actual == expected_heads, (
        f"alembic_version mismatch: got {actual}, expected {expected_heads}"
    )


# ---------------------------------------------------------------------------
# 2. alembic check — detects SQLAlchemy ↔ migration drift.
# ---------------------------------------------------------------------------


def test_alembic_check_clean(pg_engine, alembic_cfg):
    """`alembic check` produces no diff between models and migrations.

    This is the gate the « eclairage_delivered does not exist » class of
    bug would trip. If a model field is added without a matching
    migration, alembic check raises AutogenerateDiffsDetected and the
    test fails RED.

    If this test is RED on first run, that's the intended detection of
    latent drift — see DRIFT-FINDINGS.md (and consider xfail-ing this
    case temporarily while drift items are filed as separate work).
    """
    command.upgrade(alembic_cfg, "head")
    # alembic.command.check raises AutogenerateDiffsDetected on drift.
    # Anything else surfacing here is a real failure (e.g. driver error).
    command.check(alembic_cfg)


# ---------------------------------------------------------------------------
# 3. Full rollback — head → base.
# ---------------------------------------------------------------------------


def test_full_rollback(pg_engine, alembic_cfg):
    """`alembic downgrade base` empties alembic_version and drops user tables.

    Postgres-specific: SQLite would silently swallow most ALTER TABLE
    DROP COLUMN cases. On Postgres this exercises every migration's
    `downgrade()` body.
    """
    command.upgrade(alembic_cfg, "head")
    command.downgrade(alembic_cfg, "base")

    with pg_engine.connect() as conn:
        # alembic_version should be empty after a downgrade-to-base.
        rows = conn.exec_driver_sql(
            "SELECT version_num FROM alembic_version"
        ).fetchall()
    assert rows == [], (
        f"alembic_version should be empty after downgrade base, got {rows}"
    )

    # Restore HEAD so subsequent tests in this session don't inherit a
    # base-level schema (pg_engine is session-scoped; this guard keeps
    # the fixture contract additive).
    command.upgrade(alembic_cfg, "head")


# ---------------------------------------------------------------------------
# 4. Idempotent forward — head → head (second pass).
# ---------------------------------------------------------------------------


def test_full_forward_idempotent(pg_engine, alembic_cfg):
    """A second `alembic upgrade head` is a no-op even after a roundtrip.

    Inherits the idempotency-guard pattern from
    `services/backend/alembic/versions/p93_coach_message_audit.py`
    (which short-circuits when `inspector.get_table_names()` already
    contains the target table).
    """
    command.upgrade(alembic_cfg, "head")
    # Second pass: must not raise.
    command.upgrade(alembic_cfg, "head")

    inspector = inspect(pg_engine)
    table_names = set(inspector.get_table_names())
    # Sanity: the most recent migrations create these well-known tables.
    assert "users" in table_names
    assert "coach_message_audits" in table_names
    assert "alembic_version" in table_names


# ---------------------------------------------------------------------------
# 5. Revision graph — linear with one known merge node.
# ---------------------------------------------------------------------------


def test_revision_graph_linear(alembic_cfg):
    """The script directory walks cleanly with one declared merge node.

    Acceptable shape:
      - exactly one base revision (down_revision = None)
      - exactly one head
      - exactly one merge node (`5f7922bff82b_merge_p11_and_p15`)

    A second merge node WOULD be a flag (chain forked unintentionally);
    a missing base or head WOULD also flag (chain corrupted). This test
    is the « collision detector » called out by threat T-95-03-04.
    """
    script = ScriptDirectory.from_config(alembic_cfg)

    bases = list(script.get_bases())
    heads = list(script.get_heads())
    assert len(bases) == 1, f"expected exactly 1 base revision, got {bases}"
    assert len(heads) == 1, f"expected exactly 1 head revision, got {heads}"

    merge_nodes = []
    for rev in script.walk_revisions():
        # A merge revision has a tuple/list of parents in down_revision.
        if isinstance(rev.down_revision, (list, tuple)) and len(rev.down_revision) > 1:
            merge_nodes.append(rev.revision)

    # We currently have one declared merge:
    #   alembic/versions/5f7922bff82b_merge_p11_and_p15.py
    expected_merge_prefixes = {"5f7922bff82b"}
    actual_prefixes = {rev[:12] for rev in merge_nodes}
    assert actual_prefixes == expected_merge_prefixes, (
        f"unexpected merge node configuration: got {merge_nodes}, "
        f"expected one node prefixed by {expected_merge_prefixes}"
    )
