#!/usr/bin/env python3
"""Regional microcopy codegen — Phase 6 / REGIONAL-04.

Reads the 3 canton ARB carve-outs at:
    apps/mobile/lib/l10n_regional/app_regional_{vs,zh,ti}.arb

Emits a single deterministic Python module at:
    services/backend/app/services/coach/regional_microcopy.py

The generated module exposes a single class `RegionalMicrocopy` that
replaces the legacy dual-system (`REGIONAL_MAP` + `_REGIONAL_IDENTITY`)
in `claude_coach_service.py`.

Determinism: this script must produce byte-identical output on every
run. CI drift guard re-runs it and fails on `git diff --exit-code`.

Per Phase 6 D-05: VS is the Romande anchor. All Romande secondary
cantons (VD/GE/NE/JU/FR) route to the VS identity block.

Run:
    python3 tools/regional/regional_microcopy_codegen.py
"""
from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
ARB_DIR = REPO_ROOT / "apps" / "mobile" / "lib" / "l10n_regional"
OUTPUT = (
    REPO_ROOT
    / "services"
    / "backend"
    / "app"
    / "services"
    / "coach"
    / "regional_microcopy.py"
)

CANTONS = ("VS", "ZH", "TI")

# Phase 6 D-05: VS is the Romande anchor. Flip relative to legacy.
# Romande (VD/GE/NE/JU/FR) -> VS
# Deutschschweiz (all German cantons + bilingual BE/BS/BL) -> ZH
# GR -> TI (Italian-speaking region)
CANTON_TO_PRIMARY = {
    # Romande -> VS
    "VD": "VS",
    "GE": "VS",
    "NE": "VS",
    "JU": "VS",
    "FR": "VS",
    # Deutschschweiz -> ZH
    "BE": "ZH",
    "LU": "ZH",
    "AG": "ZH",
    "SG": "ZH",
    "TG": "ZH",
    "SO": "ZH",
    "SH": "ZH",
    "AR": "ZH",
    "AI": "ZH",
    "OW": "ZH",
    "NW": "ZH",
    "GL": "ZH",
    "SZ": "ZH",
    "UR": "ZH",
    "ZG": "ZH",
    "BL": "ZH",
    "BS": "ZH",
    # Italiana -> TI
    "GR": "TI",
}

# Human-readable names for each anchor canton, used in the identity block.
ANCHOR_LABEL = {
    "VS": ("Romande", "fr-CH"),
    "ZH": ("Deutschschweiz", "de-CH"),
    "TI": ("Italiana", "it-CH"),
}

# Keys we extract from each ARB to assemble a coherent identity block.
# Order is fixed for determinism.
EXTRACT_KEYS = (
    "greetingMorning",
    "coachInputHint",
    "emptyStateDefault",
    "emptyStateDefaultBody",
    "coachLoading",
    "coachShockSubtitle",
)


def _read_arb(canton: str) -> dict:
    path = ARB_DIR / f"app_regional_{canton.lower()}.arb"
    if not path.exists():
        raise SystemExit(f"Missing ARB: {path}")
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _identity_block_for(canton: str, arb: dict) -> str:
    label, base_lang = ANCHOR_LABEL[canton]
    voice_rules = arb.get("@@x-voice-rules", "")
    lines = [
        f"REGIONAL IDENTITY ({label} / {base_lang} / canton anchor: {canton}):",
        f"- Voice rules: {voice_rules}",
        "- Sample microcopy from the validated ARB carve-out (use as tonal anchor, never copy verbatim):",
    ]
    for key in EXTRACT_KEYS:
        value = arb.get(key, "").strip()
        if value:
            lines.append(f"  * {key}: {value}")
    lines.append(
        "- Stay subtle. Regional flavor is coloring, not a costume. "
        "One regional touch per response maximum, never caricature, never shame other regions."
    )
    return "\n".join(lines) + "\n"


# Neutral fallback when canton is unknown / None. Mirrors the spirit of
# the legacy `_REGIONAL_IDENTITY` block but stays canton-agnostic.
_BASE_IDENTITY = (
    "REGIONAL IDENTITY:\n"
    "- The user has no canton on file (or an unrecognized one). Stay neutral and educational.\n"
    "- Do not invent regional flavor. No septante/nonante, no Mundart, no ticinese references.\n"
    "- If the user later sets a canton in their profile, the regional layer will activate automatically.\n"
)


def _render_module(blocks: dict[str, str]) -> str:
    """Render the final Python module string. Deterministic."""
    parts: list[str] = []
    parts.append(
        "# GENERATED by tools/regional/regional_microcopy_codegen.py — do not edit by hand.\n"
    )
    parts.append(
        '"""Regional microcopy module — Phase 6 / REGIONAL-04.\n\n'
        "Single source of truth for the backend regional voice layer.\n"
        "Generated from the 3 canton ARB carve-outs at\n"
        "apps/mobile/lib/l10n_regional/app_regional_{vs,zh,ti}.arb.\n\n"
        "Replaces the legacy `REGIONAL_MAP` + `_REGIONAL_IDENTITY` dual-system\n"
        "previously hand-coded in `claude_coach_service.py`.\n\n"
        "Per Phase 6 D-05: VS is the Romande anchor. VD/GE/NE/JU/FR all\n"
        "route to the VS identity block via `CANTON_TO_PRIMARY`.\n"
        '"""\n'
    )
    parts.append("from __future__ import annotations\n\n")
    parts.append("from typing import Optional\n\n")
    parts.append('__all__ = ["RegionalMicrocopy", "CANTON_TO_PRIMARY"]\n\n')

    # CANTON_TO_PRIMARY dict, sorted for determinism
    parts.append("CANTON_TO_PRIMARY: dict[str, str] = {\n")
    for k in sorted(CANTON_TO_PRIMARY.keys()):
        parts.append(f'    "{k}": "{CANTON_TO_PRIMARY[k]}",\n')
    parts.append("}\n\n")

    # Identity blocks
    for canton in CANTONS:
        parts.append(f"_{canton}_IDENTITY = (\n")
        block = blocks[canton]
        # Split into lines, emit each as a quoted string concatenation
        block_lines = block.split("\n")
        # Drop trailing empty from final newline
        if block_lines and block_lines[-1] == "":
            block_lines = block_lines[:-1]
        for line in block_lines:
            escaped = line.replace("\\", "\\\\").replace('"', '\\"')
            parts.append(f'    "{escaped}\\n"\n')
        parts.append(")\n\n")

    # Base identity
    parts.append("_BASE_IDENTITY = (\n")
    base_lines = _BASE_IDENTITY.split("\n")
    if base_lines and base_lines[-1] == "":
        base_lines = base_lines[:-1]
    for line in base_lines:
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        parts.append(f'    "{escaped}\\n"\n')
    parts.append(")\n\n")

    parts.append("_PRIMARY_BLOCKS: dict[str, str] = {\n")
    for canton in CANTONS:
        parts.append(f'    "{canton}": _{canton}_IDENTITY,\n')
    parts.append("}\n\n")

    parts.append(
        "class RegionalMicrocopy:\n"
        '    """Single entry point for backend regional voice injection."""\n\n'
        "    @staticmethod\n"
        "    def resolve(canton: Optional[str]) -> Optional[str]:\n"
        '        """Resolve a raw canton code to its anchor (VS/ZH/TI).\n\n'
        "        Returns None if `canton` is None or unknown. Never raises.\n"
        '        """\n'
        "        if not canton:\n"
        "            return None\n"
        "        upper = canton.strip().upper()\n"
        "        if upper in _PRIMARY_BLOCKS:\n"
        "            return upper\n"
        "        return CANTON_TO_PRIMARY.get(upper)\n\n"
        "    @staticmethod\n"
        "    def identity_block(canton: Optional[str]) -> str:\n"
        '        """Return the regional identity prompt fragment for a canton.\n\n'
        "        - Known canton (primary or secondary): the anchor's identity block.\n"
        "        - None / unknown: the neutral `_BASE_IDENTITY` block.\n\n"
        "        Single injection point for `claude_coach_service.build_system_prompt`.\n"
        '        """\n'
        "        anchor = RegionalMicrocopy.resolve(canton)\n"
        "        if anchor is None:\n"
        "            return _BASE_IDENTITY\n"
        "        return _PRIMARY_BLOCKS[anchor]\n"
    )

    return "".join(parts)


def main() -> int:
    blocks = {c: _identity_block_for(c, _read_arb(c)) for c in CANTONS}
    rendered = _render_module(blocks)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as f:
        f.write(rendered)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
