"""
Claude Coach Service — Sprint S56+.

Builds the system prompt for the MINT coach Claude API integration.
Consumed by the coach chat endpoint to initialize every conversation.

Responsibilities:
    - build_system_prompt(ctx): returns the full system prompt string for the
      current user context, including tool routing rules.
    - COACH_TOOLS is imported from coach_tools.py and passed separately to
      the Anthropic API as the `tools` parameter.

Architecture:
    - The system prompt is NEVER shown to the user.
    - All user-facing text is generated by the LLM and validated by
      ComplianceGuard before delivery.
    - Tool descriptions in coach_tools.py are internal (English).
    - Coach narrative in the system prompt is in French (informal "tu").

Compliance:
    - LSFin art. 3 (information financière)
    - LPD art. 6 (protection des données)
    - FINMA circular 2008/21

Sources:
    - docs/BLUEPRINT_COACH_AI_LAYER.md
    - docs/CHAT_TO_SCREEN_ORCHESTRATION_STRATEGY.md §6
    - docs/VOICE_SYSTEM.md
"""

from typing import Optional

from app.services.coach.coach_models import CoachContext
from app.services.coach.coach_tools import COACH_TOOLS, ROUTE_TO_SCREEN_INTENT_TAGS

__all__ = ["build_system_prompt", "COACH_TOOLS"]


# ---------------------------------------------------------------------------
# Compliance constants (internal — never shown to users)
# ---------------------------------------------------------------------------

_BANNED_TERMS_REMINDER = (
    "garanti, certain, assuré, sans risque, optimal, meilleur, parfait, "
    "conseiller (use 'spécialiste'), tu devrais, tu dois, il faut"
)

_TOOL_ROUTING_RULES = """\
ROUTING RULES:
- Use route_to_screen when the user's question clearly maps to a MINT screen \
(simulator, life event, comparison tool).
- For simple questions about concepts, respond in text with show_fact_card.
- For budget or remaining-money queries, use show_budget_snapshot.
- For score or financial-health queries, use show_score_gauge.
- For complex decisions (rente vs capital, job comparison, housing), route to \
the appropriate screen.
- Always set confidence accurately — if unsure (confidence < 0.5), ask a \
clarifying question via ask_user_input instead of routing.
- The Flutter app will check data readiness before opening any screen; it \
will handle partial/blocked states automatically.
- Never emit a raw navigation route (e.g. '/rente-vs-capital'). Always use \
the route_to_screen tool with an intent tag.
- context_message MUST be educational and non-prescriptive. Use conditional \
language ('pourrait', 'dans ce scénario'). Banned terms are forbidden.

REGISTERED INTENT TAGS (route_to_screen only):
""" + "\n".join(f"  - {tag}" for tag in ROUTE_TO_SCREEN_INTENT_TAGS)


# ---------------------------------------------------------------------------
# System prompt builder
# ---------------------------------------------------------------------------

_BASE_SYSTEM_PROMPT = """\
Tu es le coach financier de MINT, une application d'éducation financière suisse.

IDENTITÉ :
- Tu es un narrateur, pas un conseiller. Tu expliques, tu contextualises, tu simules.
- Tu ne donnes JAMAIS de recommandation personnalisée au sens LSFin art. 3.
- Tu tutoies l'utilisateur. Ton ton est calme, précis, rassurant. Jamais générique.

RÈGLES ABSOLUES :
- Utilise TOUJOURS le conditionnel : "pourrait", "dans ce scénario", "selon ces hypothèses".
- Mentionne TOUJOURS l'incertitude pour les projections.
- Ne cite JAMAIS un chiffre que tu ne peux pas sourcer depuis le contexte fourni.
- Ne compare JAMAIS l'utilisateur à d'autres personnes ou à une moyenne.
- Adapte le niveau de détail au niveau de maîtrise financière de l'utilisateur.

TERMES INTERDITS (ne les utilise JAMAIS dans tes réponses) :
{banned_terms}

FORMAT DES RÉPONSES :
- Phrases courtes (max 20 mots).
- Un paragraphe = une idée.
- Ancre toujours sur un chiffre concret du contexte utilisateur si disponible.
- Pour les actions concrètes : utilise les outils (show_fact_card, route_to_screen, etc.)
  plutôt que de décrire l'action en texte.

DISCLAIMER (à rappeler si l'utilisateur demande une décision) :
MINT est un outil éducatif. Il ne constitue pas un conseil financier au sens
de la LSFin. Pour une analyse adaptée à ta situation, consulte un·e spécialiste.

{routing_rules}
"""


def build_system_prompt(ctx: Optional[CoachContext] = None) -> str:
    """Build the full system prompt for the Claude coach.

    Args:
        ctx: Optional CoachContext with user-specific data. When provided,
             the prompt is enriched with the user's known values, archetype,
             and confidence score. When None, returns the base prompt only.

    Returns:
        The complete system prompt string to pass to the Anthropic API.
    """
    base = _BASE_SYSTEM_PROMPT.format(
        banned_terms=_BANNED_TERMS_REMINDER,
        routing_rules=_TOOL_ROUTING_RULES,
    )

    if ctx is None:
        return base

    # Enrich with user context
    context_section = _build_context_section(ctx)
    return base + "\n" + context_section


def _build_context_section(ctx: CoachContext) -> str:
    """Build the user-specific context section of the system prompt.

    Privacy: NEVER includes IBAN, full name, NPA, employer, or raw account
    numbers. Only aggregated financial indicators are passed.
    """
    known = ctx.known_values or {}

    lines = ["CONTEXTE UTILISATEUR (données agrégées, non identifiantes) :"]

    if ctx.archetype:
        lines.append(f"- Archétype : {ctx.archetype}")
    if ctx.age:
        lines.append(f"- Âge : {ctx.age} ans")
    if ctx.canton:
        lines.append(f"- Canton : {ctx.canton}")
    if ctx.fri_total is not None:
        lines.append(f"- Score FRI : {ctx.fri_total}/100")
    if ctx.fri_delta is not None:
        sign = "+" if ctx.fri_delta >= 0 else ""
        lines.append(f"- Variation FRI : {sign}{ctx.fri_delta:.0f} points")
    if ctx.primary_focus:
        lines.append(f"- Priorité actuelle : {ctx.primary_focus}")
    if ctx.replacement_ratio is not None:
        lines.append(f"- Taux de remplacement estimé : {ctx.replacement_ratio * 100:.0f}%")
    if ctx.months_liquidity is not None:
        lines.append(f"- Liquidités : {ctx.months_liquidity:.1f} mois de charges")
    if ctx.tax_saving_potential is not None:
        lines.append(f"- Potentiel d'économie fiscale : {ctx.tax_saving_potential:.0f} CHF")
    if ctx.confidence_score is not None:
        lines.append(f"- Confiance données : {ctx.confidence_score:.0f}%")
    if ctx.fiscal_season:
        lines.append(f"- Saison fiscale : {ctx.fiscal_season}")
    if ctx.upcoming_event:
        lines.append(f"- Événement à venir : {ctx.upcoming_event}")
    if ctx.check_in_streak:
        lines.append(f"- Streak de check-ins : {ctx.check_in_streak} jours")

    # Append extra known_values not already covered
    extra_keys = {
        k: v for k, v in known.items()
        if k not in {
            "fri_total", "replacement_ratio", "months_liquidity",
            "tax_saving", "confidence_score",
        }
        and v is not None
    }
    for key, value in extra_keys.items():
        lines.append(f"- {key} : {value}")

    lines.append(
        "\nNote : Ces données sont des estimations. "
        "Rappelle l'incertitude si tu les cites dans une projection."
    )

    return "\n".join(lines)
