# GENERATED by tools/regional/regional_microcopy_codegen.py — do not edit by hand.
"""Regional microcopy module — Phase 6 / REGIONAL-04.

Single source of truth for the backend regional voice layer.
Generated from the 3 canton ARB carve-outs at
apps/mobile/lib/l10n_regional/app_regional_{vs,zh,ti}.arb.

Replaces the legacy `REGIONAL_MAP` + `_REGIONAL_IDENTITY` dual-system
previously hand-coded in `claude_coach_service.py`.

Per Phase 6 D-05: VS is the Romande anchor. VD/GE/NE/JU/FR all
route to the VS identity block via `CANTON_TO_PRIMARY`.
"""
from __future__ import annotations

from typing import Optional

__all__ = ["RegionalMicrocopy", "CANTON_TO_PRIMARY"]

CANTON_TO_PRIMARY: dict[str, str] = {
    "AG": "ZH",
    "AI": "ZH",
    "AR": "ZH",
    "BE": "ZH",
    "BL": "ZH",
    "BS": "ZH",
    "FR": "VS",
    "GE": "VS",
    "GL": "ZH",
    "GR": "TI",
    "JU": "VS",
    "LU": "ZH",
    "NE": "VS",
    "NW": "ZH",
    "OW": "ZH",
    "SG": "ZH",
    "SH": "ZH",
    "SO": "ZH",
    "SZ": "ZH",
    "TG": "ZH",
    "UR": "ZH",
    "VD": "VS",
    "ZG": "ZH",
}

_VS_IDENTITY = (
    "REGIONAL IDENTITY (Romande / fr-CH / canton anchor: VS):\n"
    "- Voice rules: VS: direct, montagnard, pragmatique. septante/nonante naturels. Jamais de caricature, jamais de honte. Base: fr-CH.\n"
    "- Sample microcopy from the validated ARB carve-out (use as tonal anchor, never copy verbatim):\n"
    "  * greetingMorning: Salut\n"
    "  * coachInputHint: Une question sur tes sous ?\n"
    "  * emptyStateDefault: Rien à signaler pour l'instant\n"
    "  * emptyStateDefaultBody: On démarre doucement, ça viendra à son rythme.\n"
    "  * coachLoading: Je regarde tes chiffres, deux secondes…\n"
    "  * coachShockSubtitle: Quelques chiffres pour te situer, sans détour.\n"
    "- Stay subtle. Regional flavor is coloring, not a costume. One regional touch per response maximum, never caricature, never shame other regions.\n"
)

_ZH_IDENTITY = (
    "REGIONAL IDENTITY (Deutschschweiz / de-CH / canton anchor: ZH):\n"
    "- Voice rules: ZH: Hochdeutsch base, subtile Schweizer Wärme, ruhige Kompetenz, Sparkultur. Keine schweren Mundart-Klischees. Base: de-CH.\n"
    "- Sample microcopy from the validated ARB carve-out (use as tonal anchor, never copy verbatim):\n"
    "  * greetingMorning: Grüezi\n"
    "  * coachInputHint: Eine Frage zu deinen Finanzen?\n"
    "  * emptyStateDefault: Hier ist noch nichts zu sehen\n"
    "  * emptyStateDefaultBody: Ganz normal — wir fangen in Ruhe an.\n"
    "  * coachLoading: Ich schaue mir deine Zahlen kurz an…\n"
    "  * coachShockSubtitle: Ein paar Zahlen, klar und ohne Umschweife.\n"
    "- Stay subtle. Regional flavor is coloring, not a costume. One regional touch per response maximum, never caricature, never shame other regions.\n"
)

_TI_IDENTITY = (
    "REGIONAL IDENTITY (Italiana / it-CH / canton anchor: TI):\n"
    "- Voice rules: TI: calore mediterraneo + rigore svizzero. Famiglia, risparmio, piano piano. Nessuna caricatura. Base: it-CH.\n"
    "- Sample microcopy from the validated ARB carve-out (use as tonal anchor, never copy verbatim):\n"
    "  * greetingMorning: Ciao\n"
    "  * coachInputHint: Una domanda sui tuoi soldi?\n"
    "  * emptyStateDefault: Qui ancora niente\n"
    "  * emptyStateDefaultBody: È normale, si parte con calma — piano piano.\n"
    "  * coachLoading: Sto guardando i tuoi numeri, un attimo…\n"
    "  * coachShockSubtitle: Qualche cifra per orientarti, con calma e chiarezza.\n"
    "- Stay subtle. Regional flavor is coloring, not a costume. One regional touch per response maximum, never caricature, never shame other regions.\n"
)

_BASE_IDENTITY = (
    "REGIONAL IDENTITY:\n"
    "- The user has no canton on file (or an unrecognized one). Stay neutral and educational.\n"
    "- Do not invent regional flavor. No septante/nonante, no Mundart, no ticinese references.\n"
    "- If the user later sets a canton in their profile, the regional layer will activate automatically.\n"
)

_PRIMARY_BLOCKS: dict[str, str] = {
    "VS": _VS_IDENTITY,
    "ZH": _ZH_IDENTITY,
    "TI": _TI_IDENTITY,
}

class RegionalMicrocopy:
    """Single entry point for backend regional voice injection."""

    @staticmethod
    def resolve(canton: Optional[str]) -> Optional[str]:
        """Resolve a raw canton code to its anchor (VS/ZH/TI).

        Returns None if `canton` is None or unknown. Never raises.
        """
        if not canton:
            return None
        upper = canton.strip().upper()
        if upper in _PRIMARY_BLOCKS:
            return upper
        return CANTON_TO_PRIMARY.get(upper)

    @staticmethod
    def identity_block(canton: Optional[str]) -> str:
        """Return the regional identity prompt fragment for a canton.

        - Known canton (primary or secondary): the anchor's identity block.
        - None / unknown: the neutral `_BASE_IDENTITY` block.

        Single injection point for `claude_coach_service.build_system_prompt`.
        """
        anchor = RegionalMicrocopy.resolve(canton)
        if anchor is None:
            return _BASE_IDENTITY
        return _PRIMARY_BLOCKS[anchor]
