// GENERATED — do not edit by hand.
// Source: apps/mobile/lib/services/navigation/screen_registry.dart
// Generator: tools/contracts/regen_screen_registry_contract.py
// Phase 53-04 — three-way intent contract parity gate.
//
// Set of routes the coach is allowed to navigate to from chat.
// Derived from MintScreenRegistry entries with preferFromChat: true.
// Updating: edit screen_registry.dart, then run
//   python3 tools/contracts/regen_screen_registry_contract.py
library;

const Set<String> kGeneratedValidRoutes = <String>{
  '/3a-deep/comparator',
  '/3a-deep/real-return',
  '/3a-deep/staggered-withdrawal',
  '/3a-retroactif',
  '/arbitrage/allocation-annuelle',
  '/arbitrage/bilan',
  '/arbitrage/location-vs-propriete',
  '/assurances/coverage',
  '/assurances/lamal',
  '/bank-import',
  '/budget',
  '/budget/setup',
  '/cantonal-benchmark',
  '/check/debt',
  '/coach/chat',
  '/concubinage',
  '/confidence',
  '/couple',
  '/couple/accept',
  '/debt/help',
  '/debt/ratio',
  '/debt/repayment',
  '/decaissement',
  '/disability/insurance',
  '/disability/self-employed',
  '/divorce',
  '/documents',
  '/education/hub',
  '/education/theme/:id',
  '/epl',
  '/expatriation',
  '/explore/famille',
  '/explore/fiscalite',
  '/explore/logement',
  '/explore/patrimoine',
  '/explore/retraite',
  '/explore/sante',
  '/explore/travail',
  '/first-job',
  '/fiscal',
  '/hypotheque',
  '/independants/3a',
  '/independants/avs',
  '/independants/dividende-salaire',
  '/independants/ijm',
  '/independants/lpp-volontaire',
  '/invalidite',
  '/libre-passage',
  '/life-event/deces-proche',
  '/life-event/demenagement-cantonal',
  '/life-event/donation',
  '/life-event/housing-sale',
  '/mariage',
  '/mortgage/amortization',
  '/mortgage/epl-combined',
  '/mortgage/imputed-rental',
  '/mortgage/saron-vs-fixed',
  '/naissance',
  '/open-banking',
  '/pilier-3a',
  '/profile/bilan',
  '/rachat-lpp',
  '/rente-vs-capital',
  '/retraite',
  '/scan',
  '/scan/avs-guide',
  '/segments/frontalier',
  '/segments/gender-gap',
  '/segments/independant',
  '/simulator/compound',
  '/simulator/credit',
  '/simulator/job-comparison',
  '/simulator/leasing',
  '/succession',
  '/timeline',
  '/unemployment',
};
