#!/usr/bin/env python3
"""Phase 53-04 — regenerate the 3-way intent contract from MintScreenRegistry.

Reads `apps/mobile/lib/services/navigation/screen_registry.dart` (the
single source of truth post-Plan 53-01), parses every ScreenEntry literal,
and emits three artifacts:

  1. `tools/contracts/screen_registry.json` — canonical JSON snapshot
     committed to the repo (machine-readable diff target)
  2. `apps/mobile/lib/services/coach/_valid_routes_generated.dart` —
     generated Dart `const Set<String>` consumed by ToolCallParser
  3. `services/backend/app/services/coach/_route_intents_generated.py`
     — generated Python set consumed by COACH_TOOLS

Reads the same regex patterns as `tools/checks/screen_registry_parity.py`
for consistency. Stdlib-only Python 3.9-compatible.

Usage:
    python3 tools/contracts/regen_screen_registry_contract.py [--check]

  --check : exit 1 if any of the 3 generated files would change (drift
            detection — used by CI). No writes when --check is set.

The companion lint `tools/checks/screen_registry_three_way_parity.py`
calls this with --check and fails CI on drift.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
REGISTRY_DART = REPO / "apps" / "mobile" / "lib" / "services" / "navigation" / "screen_registry.dart"
JSON_OUT = REPO / "tools" / "contracts" / "screen_registry.json"
DART_OUT = REPO / "apps" / "mobile" / "lib" / "services" / "coach" / "_valid_routes_generated.dart"
PY_OUT = REPO / "services" / "backend" / "app" / "services" / "coach" / "_route_intents_generated.py"

_ENTRY_RE = re.compile(r"ScreenEntry\s*\(([^)]*?)\)", re.DOTALL)
_INTENT_RE = re.compile(r"intentTag:\s*['\"]([^'\"]+)['\"]")
_ROUTE_RE = re.compile(r"\broute:\s*['\"]([^'\"]+)['\"]")
_PREFER_RE = re.compile(r"preferFromChat:\s*(true|false)")


def parse_registry(src: str) -> list[dict]:
    """Parse all ScreenEntry literals; return [{intent, route, preferFromChat}]."""
    out: list[dict] = []
    for body in _ENTRY_RE.findall(src):
        intent_m = _INTENT_RE.search(body)
        route_m = _ROUTE_RE.search(body)
        if not intent_m or not route_m:
            continue
        prefer_m = _PREFER_RE.search(body)
        # Default preferFromChat is true per ScreenEntry constructor at
        # screen_registry.dart:105; absence in source = true.
        prefer = (prefer_m.group(1) if prefer_m else "true") == "true"
        # Strip query string from route — `?topic=foo` shortcuts collapse
        # to the bare GoRoute target. Same normalization as the parity lint.
        route = route_m.group(1).split("?", 1)[0]
        out.append({
            "intent": intent_m.group(1),
            "route": route,
            "preferFromChat": prefer,
        })
    return out


def render_json(entries: list[dict]) -> str:
    """Stable JSON: sorted by route. Pretty-printed for diff-friendliness."""
    sorted_entries = sorted(entries, key=lambda e: (e["route"], e["intent"]))
    return json.dumps(
        {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$comment": (
                "Generated by tools/contracts/regen_screen_registry_contract.py "
                "from MintScreenRegistry (single source of truth). DO NOT EDIT "
                "BY HAND — modify screen_registry.dart and re-run the generator."
            ),
            "entries": sorted_entries,
        },
        indent=2,
        sort_keys=False,
        ensure_ascii=False,
    ) + "\n"


def render_dart(entries: list[dict]) -> str:
    """Generate the Dart const Set<String> for chat-routable routes."""
    routable = sorted({e["route"] for e in entries if e["preferFromChat"]})
    body = "\n".join(f"  '{r}'," for r in routable)
    return (
        "// GENERATED — do not edit by hand.\n"
        "// Source: apps/mobile/lib/services/navigation/screen_registry.dart\n"
        "// Generator: tools/contracts/regen_screen_registry_contract.py\n"
        "// Phase 53-04 — three-way intent contract parity gate.\n"
        "//\n"
        "// Set of routes the coach is allowed to navigate to from chat.\n"
        "// Derived from MintScreenRegistry entries with preferFromChat: true.\n"
        "// Updating: edit screen_registry.dart, then run\n"
        "//   python3 tools/contracts/regen_screen_registry_contract.py\n"
        "library;\n"
        "\n"
        f"const Set<String> kGeneratedValidRoutes = <String>{{\n{body}\n}};\n"
    )


def render_python(entries: list[dict]) -> str:
    """Generate the Python frozenset for chat-routable intent tags."""
    routable = sorted({e["intent"] for e in entries if e["preferFromChat"]})
    body = "\n".join(f"    {tag!r}," for tag in routable)
    return (
        '"""GENERATED — do not edit by hand.\n'
        "Source: apps/mobile/lib/services/navigation/screen_registry.dart\n"
        "Generator: tools/contracts/regen_screen_registry_contract.py\n"
        "Phase 53-04 — three-way intent contract parity gate.\n"
        "\n"
        "Frozen set of intent tags the LLM is allowed to suggest via the\n"
        "route_to_screen tool. Derived from MintScreenRegistry entries with\n"
        "preferFromChat: true.\n"
        "\n"
        "Updating: edit screen_registry.dart, then run\n"
        "  python3 tools/contracts/regen_screen_registry_contract.py\n"
        '"""\n'
        "from __future__ import annotations\n"
        "\n"
        f"GENERATED_ROUTE_TO_SCREEN_INTENT_TAGS: frozenset[str] = frozenset({{\n{body}\n}})\n"
    )


def write_if_changed(path: Path, new_content: str, check_only: bool) -> bool:
    """Return True if the file changed (or would change in --check mode)."""
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if existing == new_content:
        return False
    if check_only:
        sys.stderr.write(
            f"::error file={path.relative_to(REPO).as_posix()}::"
            f"would change — run python3 tools/contracts/regen_screen_registry_contract.py\n"
        )
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(new_content, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO).as_posix()}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if any generated file would change. No writes.",
    )
    args = parser.parse_args()

    if not REGISTRY_DART.exists():
        sys.stderr.write(
            f"[FAIL] screen_registry.dart not found at {REGISTRY_DART}\n"
        )
        return 2

    entries = parse_registry(REGISTRY_DART.read_text(encoding="utf-8"))
    sys.stderr.write(
        f"[info] parsed {len(entries)} ScreenEntry literals; "
        f"{sum(1 for e in entries if e['preferFromChat'])} chat-routable\n"
    )

    drift = 0
    drift += int(write_if_changed(JSON_OUT, render_json(entries), args.check))
    drift += int(write_if_changed(DART_OUT, render_dart(entries), args.check))
    drift += int(write_if_changed(PY_OUT, render_python(entries), args.check))

    if args.check and drift > 0:
        sys.stderr.write(
            f"\n{drift} contract artifact(s) out of sync with screen_registry.dart. "
            f"Run: python3 tools/contracts/regen_screen_registry_contract.py\n"
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
