"""AUTO-GENERATED by ``tools/generate_calc_registry.py`` — DO NOT EDIT MANUALLY.

Regenerate :
    python3 tools/generate_calc_registry.py

Freshness check (exit 1 on drift) :
    python3 tools/generate_calc_registry.py --check

Phase mint-calc-engine-v1 Plan 05 — D-CE-09 / D-CE-11 / D-CE-14.
"""
from __future__ import annotations

from typing import Dict, List, Literal, Set, TypedDict


class CalculatorMetadata(TypedDict):
    """Per-calculator metadata per D-CE-11.

    ``output_type`` aligns with ``app/models/lucidity/_payload.py``
    ``LucidityLevel`` (Plan 04).
    """

    name: str
    file: str
    profile_fields_needed: List[str]
    life_events_served: List[str]
    output_type: Literal["L1", "L2", "L3", "L4"]


REGISTRY: Dict[str, CalculatorMetadata] = {
    "affordability_service__AffordabilityService_calculate_affordability": {
        "name": "affordability_service__AffordabilityService_calculate_affordability",
        "file": "app/services/mortgage/affordability_service.py",
        "profile_fields_needed": ["revenu_brut_annuel", "epargne_disponible", "avoir_3a", "avoir_lpp", "prix_achat", "canton"],
        "life_events_served": ["housing"],
        "output_type": "L1",
    },
    "allocation_annuelle__compare_allocation_annuelle": {
        "name": "allocation_annuelle__compare_allocation_annuelle",
        "file": "app/services/arbitrage/allocation_annuelle.py",
        "profile_fields_needed": ["montant_disponible", "taux_marginal", "a3a_maxed", "potentiel_rachat_lpp", "is_property_owner", "taux_hypothecaire", "annees_avant_retraite", "rendement_3a", "rendement_lpp", "rendement_marche", "canton", "is_married"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "amortization_service__AmortizationService_compare": {
        "name": "amortization_service__AmortizationService_compare",
        "file": "app/services/mortgage/amortization_service.py",
        "profile_fields_needed": ["montant_hypothecaire", "taux_interet", "duree_ans", "versement_annuel_amortissement", "taux_marginal_imposition", "rendement_3a", "canton"],
        "life_events_served": ["housing"],
        "output_type": "L1",
    },
    "avs_estimation_service__AvsEstimationService_estimate": {
        "name": "avs_estimation_service__AvsEstimationService_estimate",
        "file": "app/services/retirement/avs_estimation_service.py",
        "profile_fields_needed": ["current_age", "retirement_age", "is_couple", "annees_lacunes", "life_expectancy", "gross_salary"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "calculator__UnemploymentCalculator_calculate": {
        "name": "calculator__UnemploymentCalculator_calculate",
        "file": "app/services/unemployment/calculator.py",
        "profile_fields_needed": ["gain_assure_mensuel", "age", "annees_cotisation", "has_children", "has_disability", "canton", "date_licenciement"],
        "life_events_served": ["career"],
        "output_type": "L1",
    },
    "calendrier_retraits__compare_calendrier_retraits": {
        "name": "calendrier_retraits__compare_calendrier_retraits",
        "file": "app/services/arbitrage/calendrier_retraits.py",
        "profile_fields_needed": ["assets", "age_retraite", "canton", "is_married"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "cantonal_comparator__CantonalComparator_compare_all_cantons": {
        "name": "cantonal_comparator__CantonalComparator_compare_all_cantons",
        "file": "app/services/fiscal/cantonal_comparator.py",
        "profile_fields_needed": ["income", "civil_status", "children"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "cantonal_comparator__CantonalComparator_estimate_tax": {
        "name": "cantonal_comparator__CantonalComparator_estimate_tax",
        "file": "app/services/fiscal/cantonal_comparator.py",
        "profile_fields_needed": ["income", "canton", "civil_status", "children"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "cantonal_comparator__CantonalComparator_simulate_move": {
        "name": "cantonal_comparator__CantonalComparator_simulate_move",
        "file": "app/services/fiscal/cantonal_comparator.py",
        "profile_fields_needed": ["income", "canton_from", "canton_to", "civil_status", "children"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "cantonal_comparator__estimate_capital_withdrawal_tax": {
        "name": "cantonal_comparator__estimate_capital_withdrawal_tax",
        "file": "app/services/fiscal/cantonal_comparator.py",
        "profile_fields_needed": ["amount", "canton", "is_married"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "cantonal_comparator__estimate_income_tax": {
        "name": "cantonal_comparator__estimate_income_tax",
        "file": "app/services/fiscal/cantonal_comparator.py",
        "profile_fields_needed": ["taxable_income", "canton", "is_married", "income_factor_base"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "cantonal_comparator__estimate_income_tax_on_rente": {
        "name": "cantonal_comparator__estimate_income_tax_on_rente",
        "file": "app/services/fiscal/cantonal_comparator.py",
        "profile_fields_needed": ["rente_annuelle", "canton", "is_married"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "church_tax_service__ChurchTaxService_compare_church_tax_all_cantons": {
        "name": "church_tax_service__ChurchTaxService_compare_church_tax_all_cantons",
        "file": "app/services/fiscal/church_tax_service.py",
        "profile_fields_needed": ["cantonal_tax"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "church_tax_service__ChurchTaxService_estimate_church_tax": {
        "name": "church_tax_service__ChurchTaxService_estimate_church_tax",
        "file": "app/services/fiscal/church_tax_service.py",
        "profile_fields_needed": ["cantonal_tax", "canton"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage": {
        "name": "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage",
        "file": "app/services/family/concubinage_service.py",
        "profile_fields_needed": ["revenu_1", "revenu_2", "canton", "enfants", "patrimoine"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "concubinage_service__ConcubinageService_estimate_inheritance_tax": {
        "name": "concubinage_service__ConcubinageService_estimate_inheritance_tax",
        "file": "app/services/family/concubinage_service.py",
        "profile_fields_needed": ["patrimoine", "canton", "is_married"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "cross_pillar_service__CrossPillarService_compute": {
        "name": "cross_pillar_service__CrossPillarService_compute",
        "file": "app/services/arbitrage/cross_pillar_service.py",
        "profile_fields_needed": ["profile_data"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "debt_ratio_service__DebtRatioService_calculate_debt_ratio": {
        "name": "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
        "file": "app/services/debt_prevention/debt_ratio_service.py",
        "profile_fields_needed": ["revenus_mensuels", "charges_dette_mensuelles", "loyer", "autres_charges_fixes", "situation_familiale", "nb_enfants"],
        "life_events_served": ["debt"],
        "output_type": "L1",
    },
    "divorce_simulator__DivorceSimulator_simulate": {
        "name": "divorce_simulator__DivorceSimulator_simulate",
        "file": "app/services/divorce_simulator.py",
        "profile_fields_needed": ["input_data"],
        "life_events_served": ["family", "divorce"],
        "output_type": "L1",
    },
    "donation_service__DonationService_calculate": {
        "name": "donation_service__DonationService_calculate",
        "file": "app/services/donation_service.py",
        "profile_fields_needed": ["input_data"],
        "life_events_served": ["family", "succession"],
        "output_type": "L1",
    },
    "epl_combined_service__EplCombinedService_calculate": {
        "name": "epl_combined_service__EplCombinedService_calculate",
        "file": "app/services/mortgage/epl_combined_service.py",
        "profile_fields_needed": ["avoir_3a", "avoir_lpp_total", "avoir_obligatoire", "avoir_surobligatoire", "age", "canton", "epargne_cash", "prix_cible", "a_rachete_recemment", "annees_depuis_dernier_rachat", "avoir_lpp_a_50_ans", "is_married"],
        "life_events_served": ["housing"],
        "output_type": "L1",
    },
    "epl_service__EPLService_simulate": {
        "name": "epl_service__EPLService_simulate",
        "file": "app/services/lpp_deep/epl_service.py",
        "profile_fields_needed": ["avoir_lpp_total", "avoir_obligatoire", "avoir_surobligatoire", "age", "montant_retrait_souhaite", "a_rachete_recemment", "annees_depuis_dernier_rachat", "avoir_a_50_ans", "canton", "is_married"],
        "life_events_served": ["retirement", "buyback"],
        "output_type": "L1",
    },
    "expat_service__ExpatService_compare_tax_burden": {
        "name": "expat_service__ExpatService_compare_tax_burden",
        "file": "app/services/expat/expat_service.py",
        "profile_fields_needed": ["salary", "canton", "target_country"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "expat_service__ExpatService_estimate_avs_gap": {
        "name": "expat_service__ExpatService_estimate_avs_gap",
        "file": "app/services/expat/expat_service.py",
        "profile_fields_needed": ["years_abroad", "years_in_ch"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "expat_service__ExpatService_simulate_forfait_fiscal": {
        "name": "expat_service__ExpatService_simulate_forfait_fiscal",
        "file": "app/services/expat/expat_service.py",
        "profile_fields_needed": ["canton", "living_expenses", "actual_income"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "fri_display_service__FriDisplayService_compute_for_display": {
        "name": "fri_display_service__FriDisplayService_compute_for_display",
        "file": "app/services/fri/fri_display_service.py",
        "profile_fields_needed": ["inp", "confidence_score"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "fri_display_service__FriDisplayService_simulate_action": {
        "name": "fri_display_service__FriDisplayService_simulate_action",
        "file": "app/services/fri/fri_display_service.py",
        "profile_fields_needed": ["inp", "action_type", "confidence_score"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "fri_service__FriService_compute": {
        "name": "fri_service__FriService_compute",
        "file": "app/services/fri/fri_service.py",
        "profile_fields_needed": ["inp", "confidence_score", "reference_date"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "fri_service__FriService_compute_fiscal": {
        "name": "fri_service__FriService_compute_fiscal",
        "file": "app/services/fri/fri_service.py",
        "profile_fields_needed": ["inp"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "fri_service__FriService_compute_liquidity": {
        "name": "fri_service__FriService_compute_liquidity",
        "file": "app/services/fri/fri_service.py",
        "profile_fields_needed": ["inp"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "fri_service__FriService_compute_retirement": {
        "name": "fri_service__FriService_compute_retirement",
        "file": "app/services/fri/fri_service.py",
        "profile_fields_needed": ["inp"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "fri_service__FriService_compute_structural_risk": {
        "name": "fri_service__FriService_compute_structural_risk",
        "file": "app/services/fri/fri_service.py",
        "profile_fields_needed": ["inp"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "frontalier_service__FrontalierSegmentService_calculate_source_tax": {
        "name": "frontalier_service__FrontalierSegmentService_calculate_source_tax",
        "file": "app/services/expat/frontalier_service.py",
        "profile_fields_needed": ["salary", "canton", "marital_status", "children", "church_tax"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "frontalier_service__FrontalierSegmentService_compare_social_charges": {
        "name": "frontalier_service__FrontalierSegmentService_compare_social_charges",
        "file": "app/services/expat/frontalier_service.py",
        "profile_fields_needed": ["salary", "country_of_residence"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "frontalier_service__FrontalierSegmentService_estimate_lamal_option": {
        "name": "frontalier_service__FrontalierSegmentService_estimate_lamal_option",
        "file": "app/services/expat/frontalier_service.py",
        "profile_fields_needed": ["age", "canton", "family_size", "residence_country"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "frontalier_service__FrontalierSegmentService_simulate_90_day_rule": {
        "name": "frontalier_service__FrontalierSegmentService_simulate_90_day_rule",
        "file": "app/services/expat/frontalier_service.py",
        "profile_fields_needed": ["home_office_days", "commute_days"],
        "life_events_served": ["cross_border"],
        "output_type": "L1",
    },
    "housing_sale_service__HousingSaleService_calculate": {
        "name": "housing_sale_service__HousingSaleService_calculate",
        "file": "app/services/housing_sale_service.py",
        "profile_fields_needed": ["input_data"],
        "life_events_served": ["housing"],
        "output_type": "L1",
    },
    "imputed_rental_service__ImputedRentalService_calculate": {
        "name": "imputed_rental_service__ImputedRentalService_calculate",
        "file": "app/services/mortgage/imputed_rental_service.py",
        "profile_fields_needed": ["valeur_venale", "canton", "interets_hypothecaires_annuels", "frais_entretien_annuels", "prime_assurance_batiment", "age_bien_ans", "taux_marginal_imposition"],
        "life_events_served": ["housing"],
        "output_type": "L1",
    },
    "independant_service__IndependantService_calculate_3a_plafond": {
        "name": "independant_service__IndependantService_calculate_3a_plafond",
        "file": "app/services/independant_service.py",
        "profile_fields_needed": ["revenu_net"],
        "life_events_served": ["independent"],
        "output_type": "L1",
    },
    "independant_service__IndependantService_calculate_avs_contribution": {
        "name": "independant_service__IndependantService_calculate_avs_contribution",
        "file": "app/services/independant_service.py",
        "profile_fields_needed": ["revenu_net"],
        "life_events_served": ["independent"],
        "output_type": "L1",
    },
    "independant_service__IndependantService_estimate_ijm_cost": {
        "name": "independant_service__IndependantService_estimate_ijm_cost",
        "file": "app/services/independant_service.py",
        "profile_fields_needed": ["revenu_net"],
        "life_events_served": ["independent"],
        "output_type": "L1",
    },
    "independant_service__IndependantService_estimate_laa_cost": {
        "name": "independant_service__IndependantService_estimate_laa_cost",
        "file": "app/services/independant_service.py",
        "profile_fields_needed": ["revenu_net"],
        "life_events_served": ["independent"],
        "output_type": "L1",
    },
    "job_comparator__JobComparator_compare": {
        "name": "job_comparator__JobComparator_compare",
        "file": "app/services/job_comparator.py",
        "profile_fields_needed": ["current", "new", "age", "years_to_retirement"],
        "life_events_served": ["career"],
        "output_type": "L1",
    },
    "location_vs_propriete__compare_location_vs_propriete": {
        "name": "location_vs_propriete__compare_location_vs_propriete",
        "file": "app/services/arbitrage/location_vs_propriete.py",
        "profile_fields_needed": ["capital_disponible", "loyer_mensuel_actuel", "prix_bien", "canton", "horizon_annees", "rendement_marche", "appreciation_immo", "taux_hypotheque", "taux_entretien", "is_married"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "lpp_conversion_service__LppConversionService_compare": {
        "name": "lpp_conversion_service__LppConversionService_compare",
        "file": "app/services/retirement/lpp_conversion_service.py",
        "profile_fields_needed": ["capital_lpp", "canton", "retirement_age", "life_expectancy", "taux_marginal_revenu", "is_married"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "mariage_service__MariageService_compare_fiscal_impact": {
        "name": "mariage_service__MariageService_compare_fiscal_impact",
        "file": "app/services/family/mariage_service.py",
        "profile_fields_needed": ["revenu_1", "revenu_2", "canton", "enfants"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "mariage_service__MariageService_estimate_survivor_benefits": {
        "name": "mariage_service__MariageService_estimate_survivor_benefits",
        "file": "app/services/family/mariage_service.py",
        "profile_fields_needed": ["rente_lpp", "rente_avs"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "mariage_service__MariageService_simulate_regime_matrimonial": {
        "name": "mariage_service__MariageService_simulate_regime_matrimonial",
        "file": "app/services/family/mariage_service.py",
        "profile_fields_needed": ["patrimoine_1", "patrimoine_2", "regime"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "multi_account_service__MultiAccountService_simulate_staggered_withdrawal": {
        "name": "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
        "file": "app/services/pillar_3a_deep/multi_account_service.py",
        "profile_fields_needed": ["avoir_total", "nb_comptes", "canton", "revenu_imposable", "age_retrait_debut", "age_retrait_fin", "frais_annuels_par_compte"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "naissance_service__NaissanceService_calculate_impact_fiscal_enfant": {
        "name": "naissance_service__NaissanceService_calculate_impact_fiscal_enfant",
        "file": "app/services/family/naissance_service.py",
        "profile_fields_needed": ["revenu_imposable", "taux_marginal", "nb_enfants", "frais_garde"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "naissance_service__NaissanceService_estimate_allocations": {
        "name": "naissance_service__NaissanceService_estimate_allocations",
        "file": "app/services/family/naissance_service.py",
        "profile_fields_needed": ["canton", "nb_enfants", "ages_enfants"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "naissance_service__NaissanceService_simulate_conge_parental": {
        "name": "naissance_service__NaissanceService_simulate_conge_parental",
        "file": "app/services/family/naissance_service.py",
        "profile_fields_needed": ["salaire_mensuel", "is_mother"],
        "life_events_served": ["family", "marriage"],
        "output_type": "L1",
    },
    "next_steps_service__NextStepsService_calculate": {
        "name": "next_steps_service__NextStepsService_calculate",
        "file": "app/services/next_steps_service.py",
        "profile_fields_needed": ["input_data"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "provider_comparator_service__ProviderComparatorService_compare_providers": {
        "name": "provider_comparator_service__ProviderComparatorService_compare_providers",
        "file": "app/services/pillar_3a_deep/provider_comparator_service.py",
        "profile_fields_needed": ["age", "versement_annuel", "duree", "profil_risque"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "rachat_echelonne_service__RachatEchelonneService_simulate": {
        "name": "rachat_echelonne_service__RachatEchelonneService_simulate",
        "file": "app/services/lpp_deep/rachat_echelonne_service.py",
        "profile_fields_needed": ["avoir_actuel", "rachat_max", "revenu_imposable", "taux_marginal_estime", "canton", "horizon_rachat_annees"],
        "life_events_served": ["retirement", "buyback"],
        "output_type": "L1",
    },
    "rachat_vs_marche__compare_rachat_vs_marche": {
        "name": "rachat_vs_marche__compare_rachat_vs_marche",
        "file": "app/services/arbitrage/rachat_vs_marche.py",
        "profile_fields_needed": ["montant", "taux_marginal", "annees_avant_retraite", "rendement_lpp", "rendement_marche", "taux_conversion", "canton", "is_married"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "real_return_service__RealReturnService_calculate_real_return": {
        "name": "real_return_service__RealReturnService_calculate_real_return",
        "file": "app/services/pillar_3a_deep/real_return_service.py",
        "profile_fields_needed": ["versement_annuel", "taux_marginal", "rendement_brut", "frais_gestion", "duree_annees", "inflation"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "rente_vs_capital__compare_rente_vs_capital": {
        "name": "rente_vs_capital__compare_rente_vs_capital",
        "file": "app/services/arbitrage/rente_vs_capital.py",
        "profile_fields_needed": ["capital_lpp_total", "capital_obligatoire", "capital_surobligatoire", "rente_annuelle_proposee", "taux_conversion_obligatoire", "taux_conversion_surobligatoire", "canton", "age_retraite", "taux_retrait", "rendement_capital", "inflation", "horizon", "is_married"],
        "life_events_served": ["cross_cutting"],
        "output_type": "L1",
    },
    "repayment_service__RepaymentService_compare_strategies": {
        "name": "repayment_service__RepaymentService_compare_strategies",
        "file": "app/services/debt_prevention/repayment_service.py",
        "profile_fields_needed": ["dettes", "budget_mensuel_remboursement"],
        "life_events_served": ["debt"],
        "output_type": "L1",
    },
    "retirement_projection_service__RetirementProjectionService_compute": {
        "name": "retirement_projection_service__RetirementProjectionService_compute",
        "file": "app/services/retirement/retirement_projection_service.py",
        "profile_fields_needed": ["profile_data"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "retroactive_3a_service__calculate_retroactive_3a": {
        "name": "retroactive_3a_service__calculate_retroactive_3a",
        "file": "app/services/pillar_3a_deep/retroactive_3a_service.py",
        "profile_fields_needed": ["gap_years", "taux_marginal", "has_lpp", "revenu_net_annuel", "reference_year"],
        "life_events_served": ["retirement"],
        "output_type": "L1",
    },
    "saron_vs_fixed_service__SaronVsFixedService_compare": {
        "name": "saron_vs_fixed_service__SaronVsFixedService_compare",
        "file": "app/services/mortgage/saron_vs_fixed_service.py",
        "profile_fields_needed": ["montant_hypothecaire", "duree_ans", "taux_saron_actuel", "marge_banque", "scenarios_saron", "taux_fixe"],
        "life_events_served": ["housing"],
        "output_type": "L1",
    },
    "succession_simulator__SuccessionSimulator_simulate": {
        "name": "succession_simulator__SuccessionSimulator_simulate",
        "file": "app/services/succession_simulator.py",
        "profile_fields_needed": ["input_data"],
        "life_events_served": ["family", "succession"],
        "output_type": "L1",
    },
    "wealth_tax_service__WealthTaxService_compare_all_cantons": {
        "name": "wealth_tax_service__WealthTaxService_compare_all_cantons",
        "file": "app/services/fiscal/wealth_tax_service.py",
        "profile_fields_needed": ["fortune", "civil_status"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "wealth_tax_service__WealthTaxService_estimate_wealth_tax": {
        "name": "wealth_tax_service__WealthTaxService_estimate_wealth_tax",
        "file": "app/services/fiscal/wealth_tax_service.py",
        "profile_fields_needed": ["fortune", "canton", "civil_status"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
    "wealth_tax_service__WealthTaxService_simulate_move_wealth": {
        "name": "wealth_tax_service__WealthTaxService_simulate_move_wealth",
        "file": "app/services/fiscal/wealth_tax_service.py",
        "profile_fields_needed": ["fortune", "canton_from", "canton_to", "civil_status"],
        "life_events_served": ["taxes"],
        "output_type": "L1",
    },
}


REVERSE_DEP_MAP: Dict[str, Set[str]] = {
    "a3a_maxed": {
        "allocation_annuelle__compare_allocation_annuelle",
    },
    "a_rachete_recemment": {
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
    },
    "action_type": {
        "fri_display_service__FriDisplayService_simulate_action",
    },
    "actual_income": {
        "expat_service__ExpatService_simulate_forfait_fiscal",
    },
    "age": {
        "calculator__UnemploymentCalculator_calculate",
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
        "frontalier_service__FrontalierSegmentService_estimate_lamal_option",
        "job_comparator__JobComparator_compare",
        "provider_comparator_service__ProviderComparatorService_compare_providers",
    },
    "age_bien_ans": {
        "imputed_rental_service__ImputedRentalService_calculate",
    },
    "age_retrait_debut": {
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
    },
    "age_retrait_fin": {
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
    },
    "age_retraite": {
        "calendrier_retraits__compare_calendrier_retraits",
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "ages_enfants": {
        "naissance_service__NaissanceService_estimate_allocations",
    },
    "amount": {
        "cantonal_comparator__estimate_capital_withdrawal_tax",
    },
    "annees_avant_retraite": {
        "allocation_annuelle__compare_allocation_annuelle",
        "rachat_vs_marche__compare_rachat_vs_marche",
    },
    "annees_cotisation": {
        "calculator__UnemploymentCalculator_calculate",
    },
    "annees_depuis_dernier_rachat": {
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
    },
    "annees_lacunes": {
        "avs_estimation_service__AvsEstimationService_estimate",
    },
    "appreciation_immo": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "assets": {
        "calendrier_retraits__compare_calendrier_retraits",
    },
    "autres_charges_fixes": {
        "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
    },
    "avoir_3a": {
        "affordability_service__AffordabilityService_calculate_affordability",
        "epl_combined_service__EplCombinedService_calculate",
    },
    "avoir_a_50_ans": {
        "epl_service__EPLService_simulate",
    },
    "avoir_actuel": {
        "rachat_echelonne_service__RachatEchelonneService_simulate",
    },
    "avoir_lpp": {
        "affordability_service__AffordabilityService_calculate_affordability",
    },
    "avoir_lpp_a_50_ans": {
        "epl_combined_service__EplCombinedService_calculate",
    },
    "avoir_lpp_total": {
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
    },
    "avoir_obligatoire": {
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
    },
    "avoir_surobligatoire": {
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
    },
    "avoir_total": {
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
    },
    "budget_mensuel_remboursement": {
        "repayment_service__RepaymentService_compare_strategies",
    },
    "canton": {
        "affordability_service__AffordabilityService_calculate_affordability",
        "allocation_annuelle__compare_allocation_annuelle",
        "amortization_service__AmortizationService_compare",
        "calculator__UnemploymentCalculator_calculate",
        "calendrier_retraits__compare_calendrier_retraits",
        "cantonal_comparator__CantonalComparator_estimate_tax",
        "cantonal_comparator__estimate_capital_withdrawal_tax",
        "cantonal_comparator__estimate_income_tax",
        "cantonal_comparator__estimate_income_tax_on_rente",
        "church_tax_service__ChurchTaxService_estimate_church_tax",
        "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage",
        "concubinage_service__ConcubinageService_estimate_inheritance_tax",
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
        "expat_service__ExpatService_compare_tax_burden",
        "expat_service__ExpatService_simulate_forfait_fiscal",
        "frontalier_service__FrontalierSegmentService_calculate_source_tax",
        "frontalier_service__FrontalierSegmentService_estimate_lamal_option",
        "imputed_rental_service__ImputedRentalService_calculate",
        "location_vs_propriete__compare_location_vs_propriete",
        "lpp_conversion_service__LppConversionService_compare",
        "mariage_service__MariageService_compare_fiscal_impact",
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
        "naissance_service__NaissanceService_estimate_allocations",
        "rachat_echelonne_service__RachatEchelonneService_simulate",
        "rachat_vs_marche__compare_rachat_vs_marche",
        "rente_vs_capital__compare_rente_vs_capital",
        "wealth_tax_service__WealthTaxService_estimate_wealth_tax",
    },
    "canton_from": {
        "cantonal_comparator__CantonalComparator_simulate_move",
        "wealth_tax_service__WealthTaxService_simulate_move_wealth",
    },
    "canton_to": {
        "cantonal_comparator__CantonalComparator_simulate_move",
        "wealth_tax_service__WealthTaxService_simulate_move_wealth",
    },
    "cantonal_tax": {
        "church_tax_service__ChurchTaxService_compare_church_tax_all_cantons",
        "church_tax_service__ChurchTaxService_estimate_church_tax",
    },
    "capital_disponible": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "capital_lpp": {
        "lpp_conversion_service__LppConversionService_compare",
    },
    "capital_lpp_total": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "capital_obligatoire": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "capital_surobligatoire": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "charges_dette_mensuelles": {
        "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
    },
    "children": {
        "cantonal_comparator__CantonalComparator_compare_all_cantons",
        "cantonal_comparator__CantonalComparator_estimate_tax",
        "cantonal_comparator__CantonalComparator_simulate_move",
        "frontalier_service__FrontalierSegmentService_calculate_source_tax",
    },
    "church_tax": {
        "frontalier_service__FrontalierSegmentService_calculate_source_tax",
    },
    "civil_status": {
        "cantonal_comparator__CantonalComparator_compare_all_cantons",
        "cantonal_comparator__CantonalComparator_estimate_tax",
        "cantonal_comparator__CantonalComparator_simulate_move",
        "wealth_tax_service__WealthTaxService_compare_all_cantons",
        "wealth_tax_service__WealthTaxService_estimate_wealth_tax",
        "wealth_tax_service__WealthTaxService_simulate_move_wealth",
    },
    "commute_days": {
        "frontalier_service__FrontalierSegmentService_simulate_90_day_rule",
    },
    "confidence_score": {
        "fri_display_service__FriDisplayService_compute_for_display",
        "fri_display_service__FriDisplayService_simulate_action",
        "fri_service__FriService_compute",
    },
    "country_of_residence": {
        "frontalier_service__FrontalierSegmentService_compare_social_charges",
    },
    "current": {
        "job_comparator__JobComparator_compare",
    },
    "current_age": {
        "avs_estimation_service__AvsEstimationService_estimate",
    },
    "date_licenciement": {
        "calculator__UnemploymentCalculator_calculate",
    },
    "dettes": {
        "repayment_service__RepaymentService_compare_strategies",
    },
    "duree": {
        "provider_comparator_service__ProviderComparatorService_compare_providers",
    },
    "duree_annees": {
        "real_return_service__RealReturnService_calculate_real_return",
    },
    "duree_ans": {
        "amortization_service__AmortizationService_compare",
        "saron_vs_fixed_service__SaronVsFixedService_compare",
    },
    "enfants": {
        "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage",
        "mariage_service__MariageService_compare_fiscal_impact",
    },
    "epargne_cash": {
        "epl_combined_service__EplCombinedService_calculate",
    },
    "epargne_disponible": {
        "affordability_service__AffordabilityService_calculate_affordability",
    },
    "family_size": {
        "frontalier_service__FrontalierSegmentService_estimate_lamal_option",
    },
    "fortune": {
        "wealth_tax_service__WealthTaxService_compare_all_cantons",
        "wealth_tax_service__WealthTaxService_estimate_wealth_tax",
        "wealth_tax_service__WealthTaxService_simulate_move_wealth",
    },
    "frais_annuels_par_compte": {
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
    },
    "frais_entretien_annuels": {
        "imputed_rental_service__ImputedRentalService_calculate",
    },
    "frais_garde": {
        "naissance_service__NaissanceService_calculate_impact_fiscal_enfant",
    },
    "frais_gestion": {
        "real_return_service__RealReturnService_calculate_real_return",
    },
    "gain_assure_mensuel": {
        "calculator__UnemploymentCalculator_calculate",
    },
    "gap_years": {
        "retroactive_3a_service__calculate_retroactive_3a",
    },
    "gross_salary": {
        "avs_estimation_service__AvsEstimationService_estimate",
    },
    "has_children": {
        "calculator__UnemploymentCalculator_calculate",
    },
    "has_disability": {
        "calculator__UnemploymentCalculator_calculate",
    },
    "has_lpp": {
        "retroactive_3a_service__calculate_retroactive_3a",
    },
    "home_office_days": {
        "frontalier_service__FrontalierSegmentService_simulate_90_day_rule",
    },
    "horizon": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "horizon_annees": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "horizon_rachat_annees": {
        "rachat_echelonne_service__RachatEchelonneService_simulate",
    },
    "income": {
        "cantonal_comparator__CantonalComparator_compare_all_cantons",
        "cantonal_comparator__CantonalComparator_estimate_tax",
        "cantonal_comparator__CantonalComparator_simulate_move",
    },
    "income_factor_base": {
        "cantonal_comparator__estimate_income_tax",
    },
    "inflation": {
        "real_return_service__RealReturnService_calculate_real_return",
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "inp": {
        "fri_display_service__FriDisplayService_compute_for_display",
        "fri_display_service__FriDisplayService_simulate_action",
        "fri_service__FriService_compute",
        "fri_service__FriService_compute_fiscal",
        "fri_service__FriService_compute_liquidity",
        "fri_service__FriService_compute_retirement",
        "fri_service__FriService_compute_structural_risk",
    },
    "input_data": {
        "divorce_simulator__DivorceSimulator_simulate",
        "donation_service__DonationService_calculate",
        "housing_sale_service__HousingSaleService_calculate",
        "next_steps_service__NextStepsService_calculate",
        "succession_simulator__SuccessionSimulator_simulate",
    },
    "interets_hypothecaires_annuels": {
        "imputed_rental_service__ImputedRentalService_calculate",
    },
    "is_couple": {
        "avs_estimation_service__AvsEstimationService_estimate",
    },
    "is_married": {
        "allocation_annuelle__compare_allocation_annuelle",
        "calendrier_retraits__compare_calendrier_retraits",
        "cantonal_comparator__estimate_capital_withdrawal_tax",
        "cantonal_comparator__estimate_income_tax",
        "cantonal_comparator__estimate_income_tax_on_rente",
        "concubinage_service__ConcubinageService_estimate_inheritance_tax",
        "epl_combined_service__EplCombinedService_calculate",
        "epl_service__EPLService_simulate",
        "location_vs_propriete__compare_location_vs_propriete",
        "lpp_conversion_service__LppConversionService_compare",
        "rachat_vs_marche__compare_rachat_vs_marche",
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "is_mother": {
        "naissance_service__NaissanceService_simulate_conge_parental",
    },
    "is_property_owner": {
        "allocation_annuelle__compare_allocation_annuelle",
    },
    "life_expectancy": {
        "avs_estimation_service__AvsEstimationService_estimate",
        "lpp_conversion_service__LppConversionService_compare",
    },
    "living_expenses": {
        "expat_service__ExpatService_simulate_forfait_fiscal",
    },
    "loyer": {
        "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
    },
    "loyer_mensuel_actuel": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "marge_banque": {
        "saron_vs_fixed_service__SaronVsFixedService_compare",
    },
    "marital_status": {
        "frontalier_service__FrontalierSegmentService_calculate_source_tax",
    },
    "montant": {
        "rachat_vs_marche__compare_rachat_vs_marche",
    },
    "montant_disponible": {
        "allocation_annuelle__compare_allocation_annuelle",
    },
    "montant_hypothecaire": {
        "amortization_service__AmortizationService_compare",
        "saron_vs_fixed_service__SaronVsFixedService_compare",
    },
    "montant_retrait_souhaite": {
        "epl_service__EPLService_simulate",
    },
    "nb_comptes": {
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
    },
    "nb_enfants": {
        "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
        "naissance_service__NaissanceService_calculate_impact_fiscal_enfant",
        "naissance_service__NaissanceService_estimate_allocations",
    },
    "new": {
        "job_comparator__JobComparator_compare",
    },
    "patrimoine": {
        "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage",
        "concubinage_service__ConcubinageService_estimate_inheritance_tax",
    },
    "patrimoine_1": {
        "mariage_service__MariageService_simulate_regime_matrimonial",
    },
    "patrimoine_2": {
        "mariage_service__MariageService_simulate_regime_matrimonial",
    },
    "potentiel_rachat_lpp": {
        "allocation_annuelle__compare_allocation_annuelle",
    },
    "prime_assurance_batiment": {
        "imputed_rental_service__ImputedRentalService_calculate",
    },
    "prix_achat": {
        "affordability_service__AffordabilityService_calculate_affordability",
    },
    "prix_bien": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "prix_cible": {
        "epl_combined_service__EplCombinedService_calculate",
    },
    "profil_risque": {
        "provider_comparator_service__ProviderComparatorService_compare_providers",
    },
    "profile_data": {
        "cross_pillar_service__CrossPillarService_compute",
        "retirement_projection_service__RetirementProjectionService_compute",
    },
    "rachat_max": {
        "rachat_echelonne_service__RachatEchelonneService_simulate",
    },
    "reference_date": {
        "fri_service__FriService_compute",
    },
    "reference_year": {
        "retroactive_3a_service__calculate_retroactive_3a",
    },
    "regime": {
        "mariage_service__MariageService_simulate_regime_matrimonial",
    },
    "rendement_3a": {
        "allocation_annuelle__compare_allocation_annuelle",
        "amortization_service__AmortizationService_compare",
    },
    "rendement_brut": {
        "real_return_service__RealReturnService_calculate_real_return",
    },
    "rendement_capital": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "rendement_lpp": {
        "allocation_annuelle__compare_allocation_annuelle",
        "rachat_vs_marche__compare_rachat_vs_marche",
    },
    "rendement_marche": {
        "allocation_annuelle__compare_allocation_annuelle",
        "location_vs_propriete__compare_location_vs_propriete",
        "rachat_vs_marche__compare_rachat_vs_marche",
    },
    "rente_annuelle": {
        "cantonal_comparator__estimate_income_tax_on_rente",
    },
    "rente_annuelle_proposee": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "rente_avs": {
        "mariage_service__MariageService_estimate_survivor_benefits",
    },
    "rente_lpp": {
        "mariage_service__MariageService_estimate_survivor_benefits",
    },
    "residence_country": {
        "frontalier_service__FrontalierSegmentService_estimate_lamal_option",
    },
    "retirement_age": {
        "avs_estimation_service__AvsEstimationService_estimate",
        "lpp_conversion_service__LppConversionService_compare",
    },
    "revenu_1": {
        "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage",
        "mariage_service__MariageService_compare_fiscal_impact",
    },
    "revenu_2": {
        "concubinage_service__ConcubinageService_compare_mariage_vs_concubinage",
        "mariage_service__MariageService_compare_fiscal_impact",
    },
    "revenu_brut_annuel": {
        "affordability_service__AffordabilityService_calculate_affordability",
    },
    "revenu_imposable": {
        "multi_account_service__MultiAccountService_simulate_staggered_withdrawal",
        "naissance_service__NaissanceService_calculate_impact_fiscal_enfant",
        "rachat_echelonne_service__RachatEchelonneService_simulate",
    },
    "revenu_net": {
        "independant_service__IndependantService_calculate_3a_plafond",
        "independant_service__IndependantService_calculate_avs_contribution",
        "independant_service__IndependantService_estimate_ijm_cost",
        "independant_service__IndependantService_estimate_laa_cost",
    },
    "revenu_net_annuel": {
        "retroactive_3a_service__calculate_retroactive_3a",
    },
    "revenus_mensuels": {
        "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
    },
    "salaire_mensuel": {
        "naissance_service__NaissanceService_simulate_conge_parental",
    },
    "salary": {
        "expat_service__ExpatService_compare_tax_burden",
        "frontalier_service__FrontalierSegmentService_calculate_source_tax",
        "frontalier_service__FrontalierSegmentService_compare_social_charges",
    },
    "scenarios_saron": {
        "saron_vs_fixed_service__SaronVsFixedService_compare",
    },
    "situation_familiale": {
        "debt_ratio_service__DebtRatioService_calculate_debt_ratio",
    },
    "target_country": {
        "expat_service__ExpatService_compare_tax_burden",
    },
    "taux_conversion": {
        "rachat_vs_marche__compare_rachat_vs_marche",
    },
    "taux_conversion_obligatoire": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "taux_conversion_surobligatoire": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "taux_entretien": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "taux_fixe": {
        "saron_vs_fixed_service__SaronVsFixedService_compare",
    },
    "taux_hypothecaire": {
        "allocation_annuelle__compare_allocation_annuelle",
    },
    "taux_hypotheque": {
        "location_vs_propriete__compare_location_vs_propriete",
    },
    "taux_interet": {
        "amortization_service__AmortizationService_compare",
    },
    "taux_marginal": {
        "allocation_annuelle__compare_allocation_annuelle",
        "naissance_service__NaissanceService_calculate_impact_fiscal_enfant",
        "rachat_vs_marche__compare_rachat_vs_marche",
        "real_return_service__RealReturnService_calculate_real_return",
        "retroactive_3a_service__calculate_retroactive_3a",
    },
    "taux_marginal_estime": {
        "rachat_echelonne_service__RachatEchelonneService_simulate",
    },
    "taux_marginal_imposition": {
        "amortization_service__AmortizationService_compare",
        "imputed_rental_service__ImputedRentalService_calculate",
    },
    "taux_marginal_revenu": {
        "lpp_conversion_service__LppConversionService_compare",
    },
    "taux_retrait": {
        "rente_vs_capital__compare_rente_vs_capital",
    },
    "taux_saron_actuel": {
        "saron_vs_fixed_service__SaronVsFixedService_compare",
    },
    "taxable_income": {
        "cantonal_comparator__estimate_income_tax",
    },
    "valeur_venale": {
        "imputed_rental_service__ImputedRentalService_calculate",
    },
    "versement_annuel": {
        "provider_comparator_service__ProviderComparatorService_compare_providers",
        "real_return_service__RealReturnService_calculate_real_return",
    },
    "versement_annuel_amortissement": {
        "amortization_service__AmortizationService_compare",
    },
    "years_abroad": {
        "expat_service__ExpatService_estimate_avs_gap",
    },
    "years_in_ch": {
        "expat_service__ExpatService_estimate_avs_gap",
    },
    "years_to_retirement": {
        "job_comparator__JobComparator_compare",
    },
}

def get_calculator(name: str) -> CalculatorMetadata:
    """Lookup helper — raises ``KeyError`` if ``name`` is not in REGISTRY.

    Plan 05 (D-CE-11) primary read API. Wave 2 ``ToolRegistryAdapter`` and
    Wave 3 reverse-dep cache consume this.
    """
    if name not in REGISTRY:
        raise KeyError(
            f"Calculator {name!r} not in REGISTRY. "
            "Re-run tools/generate_calc_registry.py."
        )
    return REGISTRY[name]


def get_reverse_deps(field_name: str) -> Set[str]:
    """Return the set of calc names that depend on ``field_name``.

    Plan 14 (D-CE-14) ships the full implementation (« static reverse-dep map
    for pre-compute selection ») ; this scaffold returns the AST-derived seed
    so Wave 2 / Wave 3 can wire against the API today.
    """
    return REVERSE_DEP_MAP.get(field_name, set())
