#!/usr/bin/env python3
"""Reproduce and verify the pinned Unicode tables used by Batch 14."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import io
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
FIXTURES = ROOT / "tools/checks/fixtures/unicode"
CASE_FIXTURE = FIXTURES / "CaseFolding-17.0.0.txt.gz"
IGNORABLE_FIXTURE = FIXTURES / "DefaultIgnorable-17.0.0.txt"
CASE_OUTPUT = (
    ROOT
    / "product/mint_next/batch7/design_lab/lib/multi_provider_casefold_data.dart"
)
IGNORABLE_OUTPUT = (
    ROOT
    / "product/mint_next/batch7/design_lab/lib/multi_provider_default_ignorable_data.dart"
)

CASE_URL = "https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt"
DERIVED_URL = (
    "https://www.unicode.org/Public/17.0.0/ucd/DerivedCoreProperties.txt"
)
CASE_SHA = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"
DERIVED_SHA = "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"
IGNORABLE_FIXTURE_SHA = (
    "0c6981e758af93e1912461e9fb755b8ad1ddde66ce9a3ba8fac649968572ffc6"
)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def extract_ignorable_fixture(derived: bytes) -> bytes:
    selected = []
    for line in derived.decode("utf-8").splitlines():
        core = line.split("#", 1)[0].strip()
        if core.endswith("; Default_Ignorable_Code_Point"):
            selected.append(line)
    text = (
        "# Extracted from Unicode 17.0.0 DerivedCoreProperties.txt.\n"
        f"# Source SHA-256: {DERIVED_SHA}\n"
        + "\n".join(selected)
        + "\n"
    )
    return text.encode("utf-8")


def refresh_fixtures() -> None:
    case = urllib.request.urlopen(CASE_URL, timeout=30).read()
    derived = urllib.request.urlopen(DERIVED_URL, timeout=30).read()
    if sha256(case) != CASE_SHA or sha256(derived) != DERIVED_SHA:
        raise SystemExit("Unicode upstream SHA mismatch; refuse regeneration")
    FIXTURES.mkdir(parents=True, exist_ok=True)
    buffer = io.BytesIO()
    with gzip.GzipFile(fileobj=buffer, mode="wb", compresslevel=9, mtime=0) as out:
        out.write(case)
    CASE_FIXTURE.write_bytes(buffer.getvalue())
    IGNORABLE_FIXTURE.write_bytes(extract_ignorable_fixture(derived))


def read_casefold() -> bytes:
    data = gzip.decompress(CASE_FIXTURE.read_bytes())
    if sha256(data) != CASE_SHA:
        raise SystemExit("CaseFolding fixture SHA mismatch")
    return data


def read_ignorable() -> bytes:
    data = IGNORABLE_FIXTURE.read_bytes()
    if sha256(data) != IGNORABLE_FIXTURE_SHA:
        raise SystemExit("DefaultIgnorable fixture SHA mismatch")
    return data


def render_casefold(data: bytes) -> str:
    mappings: dict[int, tuple[str, str]] = {}
    for line in data.decode("utf-8").splitlines():
        core = line.split("#", 1)[0].strip()
        if not core:
            continue
        codepoint, status, mapping, _ = [part.strip() for part in core.split(";")]
        if status not in {"C", "F"}:
            continue
        key = int(codepoint, 16)
        if status == "F" or key not in mappings:
            mappings[key] = (status, mapping)
    lines = [
        "// GENERATED by tools/checks/mint_next_batch14_unicode_data.py.",
        "// Unicode 17.0.0 CaseFolding.txt; default full C/F mappings, T excluded.",
        f"// Source: {CASE_URL}",
        f"// SHA-256: {CASE_SHA}",
        "// Unicode license: https://www.unicode.org/license.txt",
        "const Map<int, String> multiProviderFullCaseFold = {",
    ]
    for codepoint, (_, mapping) in sorted(mappings.items()):
        escaped = "".join(f"\\u{{{int(item, 16):X}}}" for item in mapping.split())
        lines.append(f"  0x{codepoint:X}: '{escaped}',")
    lines.append("};")
    return "\n".join(lines) + "\n"


def render_ignorable(data: bytes) -> str:
    ranges: list[tuple[int, int]] = []
    for line in data.decode("utf-8").splitlines():
        core = line.split("#", 1)[0].strip()
        if not core:
            continue
        value, prop = [part.strip() for part in core.split(";")]
        if prop != "Default_Ignorable_Code_Point":
            raise SystemExit(f"Unexpected property in ignorable fixture: {prop}")
        bounds = value.split("..")
        ranges.append((int(bounds[0], 16), int(bounds[-1], 16)))
    lines = [
        "// GENERATED by tools/checks/mint_next_batch14_unicode_data.py.",
        "// Unicode 17.0.0 DerivedCoreProperties: Default_Ignorable_Code_Point.",
        f"// Source: {DERIVED_URL}",
        f"// SHA-256: {DERIVED_SHA}",
        "// Unicode license: https://www.unicode.org/license.txt",
        "const List<(int, int)> multiProviderDefaultIgnorableRanges = [",
    ]
    lines.extend(f"  (0x{start:X}, 0x{end:X})," for start, end in ranges)
    lines.append("];")
    return "\n".join(lines) + "\n"


def verify_or_write(*, write: bool) -> None:
    expected = {
        CASE_OUTPUT: render_casefold(read_casefold()),
        IGNORABLE_OUTPUT: render_ignorable(read_ignorable()),
    }
    if write:
        for path, content in expected.items():
            path.write_text(content, encoding="utf-8")
        return
    mismatches = [path for path, content in expected.items() if path.read_text() != content]
    if mismatches:
        joined = ", ".join(str(path.relative_to(ROOT)) for path in mismatches)
        raise SystemExit(f"Generated Unicode data mismatch: {joined}")
    print("OK mint_next_batch14_unicode_data: pinned Unicode tables reproduce exactly.")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--refresh", action="store_true", help="download pinned sources")
    parser.add_argument("--write", action="store_true", help="rewrite Dart outputs")
    args = parser.parse_args()
    if args.refresh:
        refresh_fixtures()
    verify_or_write(write=args.write or args.refresh)


if __name__ == "__main__":
    main()
