#!/usr/bin/env python3
"""Phase 87 OBSV-06 — block NEW bare catches outside the v2.12 ledger.

A « bare catch » is a `} catch (e) {` or `} catch (_) {` that does NOT
route the exception through `Sentry.captureException` (whitelisted in
`error_boundary.dart` only) or `captureSwallowedException` (the one
allowed swallow path).

The full inventory of currently-tolerated sites lives in
`tools/checks/bare_catch_debt.lock` (machine-readable allowlist). The
human ledger lives at `.planning/BARE_CATCH_DEBT.md`. Wave 1 (Phase 87)
typed-converts 15 sites; Wave 2/3 are scheduled in v2.13/v2.14 ROADMAPs.

Exit codes:
  0  no violations (ledger is in sync)
  1  at least one new bare catch found that is NOT in the lock file
  2  ledger / lock file invariants broken (file missing, malformed)

Usage:
    python3 tools/checks/no_new_bare_catch.py
    python3 tools/checks/no_new_bare_catch.py --regen-debt   # regenerate lock

Conventions:
  - Lock format: `<relpath>:<line>` per line, sorted, comments allowed
    on lines starting with `#`. Anything else is a hard error.
  - Scan target: `apps/mobile/lib/` (Wave 1 ; Wave 2 will widen to
    `services/backend/app/` once Python bare-except sweep starts).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCAN_ROOTS = [REPO_ROOT / "apps" / "mobile" / "lib"]
LOCK_FILE = REPO_ROOT / "tools" / "checks" / "bare_catch_debt.lock"
LEDGER_MD = REPO_ROOT / ".planning" / "BARE_CATCH_DEBT.md"

# Match `} catch (NAME) {` and `} catch (_) {` end-of-line.
# Excludes typed catches like `} on FooException catch (e, st) {`.
BARE_CATCH_RE = re.compile(r"\}\s*catch\s*\(\s*\w+\s*\)\s*\{")

# Whitelisted: a typed `on X catch ...` followed by a `} catch (...) {`
# fallback in the same construct is still flagged because it matches the
# regex on the line. The ledger covers it explicitly when needed.

EXCLUDE_SUFFIXES = (".g.dart",)
EXCLUDE_DIRS = {"generated", "l10n"}


def is_excluded(path: Path) -> bool:
    if path.name.endswith(EXCLUDE_SUFFIXES):
        return True
    rel = path.relative_to(REPO_ROOT)
    for part in rel.parts:
        if part in EXCLUDE_DIRS:
            return True
    return False


def scan() -> list[tuple[str, int, str]]:
    """Return list of (relpath, line_no, snippet) for every bare catch."""
    hits: list[tuple[str, int, str]] = []
    for root in SCAN_ROOTS:
        if not root.is_dir():
            continue
        for dart_path in sorted(root.rglob("*.dart")):
            if is_excluded(dart_path):
                continue
            try:
                text = dart_path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            for line_no, line in enumerate(text.splitlines(), start=1):
                if BARE_CATCH_RE.search(line):
                    rel = dart_path.relative_to(REPO_ROOT).as_posix()
                    hits.append((rel, line_no, line.strip()))
    return hits


def load_lock() -> tuple[set[tuple[str, int]], list[str]]:
    """Return (allowed-set, raw-lines) from bare_catch_debt.lock.

    Raises SystemExit(2) on malformed lines.
    """
    if not LOCK_FILE.is_file():
        return set(), []
    raw_lines = LOCK_FILE.read_text(encoding="utf-8").splitlines()
    allowed: set[tuple[str, int]] = set()
    for ln, raw in enumerate(raw_lines, start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        # Format: relpath:lineno
        try:
            head, rest = line.rsplit(":", 1)
            line_no = int(rest.split()[0])
        except (ValueError, IndexError):
            print(
                f"[FAIL] malformed lock entry @ line {ln}: {raw!r}",
                file=sys.stderr,
            )
            raise SystemExit(2)
        allowed.add((head, line_no))
    return allowed, raw_lines


def regen_debt(hits: list[tuple[str, int, str]]) -> None:
    """Overwrite the lock file with all current bare-catch sites."""
    LOCK_FILE.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# tools/checks/bare_catch_debt.lock",
        "# Phase 87 OBSV-06 — machine-readable allowlist of grandfathered",
        "# bare catches.  Generated by no_new_bare_catch.py --regen-debt.",
        "# DO NOT edit manually unless adding a justified false-positive",
        "# entry; the lint scans this file in O(n).",
        "#",
        "# Format: <relpath>:<lineno>",
        "# Human ledger: .planning/BARE_CATCH_DEBT.md",
        "",
    ]
    body = sorted(f"{rel}:{lineno}" for rel, lineno, _ in hits)
    LOCK_FILE.write_text("\n".join(header + body) + "\n", encoding="utf-8")
    print(f"[OK] regenerated {LOCK_FILE.name} with {len(body)} entries")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--regen-debt",
        action="store_true",
        help="regenerate tools/checks/bare_catch_debt.lock from current hits",
    )
    args = parser.parse_args()

    hits = scan()

    if args.regen_debt:
        regen_debt(hits)
        return 0

    if not LEDGER_MD.is_file():
        print(
            f"[FAIL] ledger {LEDGER_MD.relative_to(REPO_ROOT)} not found — "
            "Phase 87 OBSV-05 invariant",
            file=sys.stderr,
        )
        return 2

    allowed, _ = load_lock()
    if not allowed:
        # Lock file missing or empty. If hits exist, this means Phase 87
        # never bootstrapped the lock; refuse to allow blanket pass-through.
        if hits:
            print(
                f"[FAIL] {LOCK_FILE.relative_to(REPO_ROOT)} is empty but "
                f"{len(hits)} bare catch(es) exist. Run "
                "`python3 tools/checks/no_new_bare_catch.py --regen-debt` "
                "to bootstrap.",
                file=sys.stderr,
            )
            return 1
        return 0

    new_hits = [
        (rel, lineno, snippet)
        for rel, lineno, snippet in hits
        if (rel, lineno) not in allowed
    ]
    if not new_hits:
        print(
            f"no_new_bare_catch: OK — {len(hits)} grandfathered, "
            f"0 new violations"
        )
        return 0

    print(
        f"no_new_bare_catch: FAIL — {len(new_hits)} NEW bare catch(es) "
        f"outside the ledger:",
        file=sys.stderr,
    )
    for rel, lineno, snippet in new_hits:
        print(f"  {rel}:{lineno}: {snippet}", file=sys.stderr)
    print(
        "\nFix options:\n"
        "  1. Convert to typed catch + captureSwallowedException + "
        "MintBreadcrumbs.swallow (preferred).\n"
        "  2. If genuinely false positive, add the path:line to "
        f"{LOCK_FILE.relative_to(REPO_ROOT)} with a `# rationale` comment "
        "AND open an entry in .planning/BARE_CATCH_DEBT.md.\n",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
