#!/usr/bin/env python3
"""HARD lefthook lint — Phase mint-data-architecture-v1-02 W0 Plan 02-01 iter-2 Tier-B B4 (D-09).

Refuses re-introduction of `class FrontalierService:` outside the S12 façade
allowlist (`services/backend/app/services/frontalier_service.py`).

After Plan 02-01 W0, the S23 (expat) `FrontalierService` is renamed to
`FrontalierSegmentService`. An alias `FrontalierService = FrontalierSegmentService`
remains for backward-compat until Plan 02-04 PR-2 removes it. New backend
files landing between W0 and W4 must NOT re-declare the old name in the S23
namespace, otherwise the alias-window collides.

Allowlist (hardcoded) :
    services/backend/app/services/frontalier_service.py — S12 façade,
        a DIFFERENT class with the same name, kept forever per D-08.

Self-exempt :
    * this script
    * `services/backend/tests/fixtures/bad_s23_redeclaration.py` (lint fixture)

Exit codes :
    0 — no `class FrontalierService:` outside allowlist + self-exempt
    1 — at least one re-introduction

Usage :
    python3 tools/checks/s23_class_name_lint.py [paths...]
    python3 tools/checks/s23_class_name_lint.py --self-test
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_SELF_PATH = Path(__file__).resolve()
_BAD_FIXTURE = (
    _REPO_ROOT
    / "services"
    / "backend"
    / "tests"
    / "fixtures"
    / "bad_s23_redeclaration.py"
)

# S12 façade — DIFFERENT class with the same name, allowlisted forever per D-08.
_ALLOWLIST = {
    _REPO_ROOT / "services" / "backend" / "app" / "services" / "frontalier_service.py",
}

_DEFAULT_SCAN_DIR = _REPO_ROOT / "services" / "backend"

# `class FrontalierService:` or `class FrontalierService(Base):` — but NOT
# `class FrontalierServiceFoo:` (must be a word boundary after).
_CLASS_RE = re.compile(r"^class\s+FrontalierService\b", re.MULTILINE)


def _is_self_exempt(path: Path) -> bool:
    resolved = path.resolve()
    return resolved in {_SELF_PATH, _BAD_FIXTURE} | _ALLOWLIST


def scan_file(path: Path) -> list[int]:
    """Return [lineno, ...] for each `class FrontalierService:` line in `path`."""
    if _is_self_exempt(path):
        return []
    try:
        source = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return []
    return [
        source.count("\n", 0, m.start()) + 1 for m in _CLASS_RE.finditer(source)
    ]


# Generated / build artifact directories that may contain stale copies of
# pre-rename code (e.g., setup.py develop creates `build/lib/...`). These
# MUST NOT count as violations — they are not source-of-truth. CI fix
# 2026-05-19 : the lint was tripping on `services/backend/build/lib/app/
# services/frontalier_service.py:291` which is the pre-rename copy
# regenerated by `pip install -e .` during CI's "Install dependencies" step.
_EXCLUDED_DIR_PARTS = frozenset({
    "build",        # setuptools / pip install -e . output
    "dist",         # setuptools sdist / wheel output
    ".eggs",        # legacy easy_install
    "__pycache__",  # CPython bytecode
    ".venv",        # local virtualenv
    "venv",
    ".tox",
    ".pytest_cache",
})


def _is_excluded(path: Path) -> bool:
    """True if any path part is in the excluded directories list."""
    return any(part in _EXCLUDED_DIR_PARTS for part in path.parts)


def _iter_paths(paths: list[str]) -> list[Path]:
    result: list[Path] = []
    for raw in paths:
        p = Path(raw).resolve()
        if not p.exists():
            continue
        if p.is_dir():
            result.extend(
                sorted(f for f in p.rglob("*.py") if not _is_excluded(f))
            )
        elif p.suffix == ".py" and not _is_excluded(p):
            result.append(p)
    return result


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="HARD lint — re-introduction of `class FrontalierService:` (D-09).",
    )
    parser.add_argument(
        "paths",
        nargs="*",
        help="Files or directories to scan. Default: services/backend/.",
    )
    parser.add_argument(
        "--self-test", action="store_true", help="Scan fixture and assert ≥ 1 violation."
    )
    args = parser.parse_args(argv)

    if args.self_test:
        if not _BAD_FIXTURE.exists():
            print(f"ERROR: self-test fixture missing : {_BAD_FIXTURE}", file=sys.stderr)
            return 2

        # Scan fixture WITHOUT self-exempt
        try:
            source = _BAD_FIXTURE.read_text(encoding="utf-8")
        except OSError:
            print(f"ERROR: cannot read fixture : {_BAD_FIXTURE}", file=sys.stderr)
            return 2
        fixture_lines = [
            source.count("\n", 0, m.start()) + 1 for m in _CLASS_RE.finditer(source)
        ]
        if not fixture_lines:
            print(
                f"ERROR: self-test expected ≥ 1 `class FrontalierService:` in "
                f"{_BAD_FIXTURE.relative_to(_REPO_ROOT)}, got 0.",
                file=sys.stderr,
            )
            return 1

        # Verify the existing tree is clean (only the S12 façade declares it).
        scan_paths = _iter_paths([str(_DEFAULT_SCAN_DIR)])
        tree_violations: list[tuple[str, int]] = []
        for p in scan_paths:
            for lineno in scan_file(p):
                tree_violations.append((str(p.relative_to(_REPO_ROOT)), lineno))
        if tree_violations:
            print(
                f"ERROR: self-test expected clean tree (only S12 façade declares "
                f"`class FrontalierService:`), got {len(tree_violations)} "
                f"declarations outside allowlist :",
                file=sys.stderr,
            )
            for rel, lineno in tree_violations:
                print(f"  {rel}:{lineno}", file=sys.stderr)
            return 1
        print(
            f"OK s23_class_name_lint --self-test : "
            f"caught {len(fixture_lines)} re-introductions in fixture, "
            f"existing tree clean (S12 façade allowlisted)."
        )
        return 0

    paths = args.paths or [str(_DEFAULT_SCAN_DIR)]
    scan_paths = _iter_paths(paths)
    total = 0
    for p in scan_paths:
        for lineno in scan_file(p):
            total += 1
            try:
                rel = p.relative_to(_REPO_ROOT)
            except ValueError:
                rel = p
            print(
                f"{rel}:{lineno}  Do not re-introduce `class FrontalierService:` "
                f"outside the S12 façade `app/services/frontalier_service.py`. "
                f"The S23 class is `FrontalierSegmentService` since Phase 02 D-09.",
                file=sys.stderr,
            )
    if total > 0:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
