#!/usr/bin/env python3
"""Phase 53-04 — three-way intent contract parity gate.

Enforces single-source-of-truth across the chat→screen routing contract:

  1. `apps/mobile/lib/services/navigation/screen_registry.dart`
     — the SOURCE OF TRUTH (`MintScreenRegistry.entries`)
  2. `tools/contracts/screen_registry.json`
     — committed snapshot, regenerated by
     `tools/contracts/regen_screen_registry_contract.py`
  3. `apps/mobile/lib/services/coach/_valid_routes_generated.dart`
     — generated Dart Set consumed by `ToolCallParser.validRoutes`
  4. `services/backend/app/services/coach/_route_intents_generated.py`
     — generated Python frozenset consumed by `COACH_TOOLS`

Without this gate, Plan 53-01's "138 ScreenEntry routes parity OK"
claim was misleading: 26 of the new entries were unreachable from
chat because the LLM whitelist + mobile validator weren't updated.
Façade-sans-câblage class banned by Julien's discipline.

Usage:
    python3 tools/checks/screen_registry_three_way_parity.py

Exit 0 on parity. Exit 1 on drift with `::error file=...` diagnostics
pointing at the specific generated file that needs regeneration. Per
the "fix the code" maintenance policy: run
`python3 tools/contracts/regen_screen_registry_contract.py` and commit
the generated changes.

Stdlib-only Python 3.9-compatible. Runtime ~50 ms.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
REGEN_SCRIPT = REPO / "tools" / "contracts" / "regen_screen_registry_contract.py"


def main() -> int:
    if not REGEN_SCRIPT.exists():
        sys.stderr.write(
            f"[FAIL] regen script missing at "
            f"{REGEN_SCRIPT.relative_to(REPO).as_posix()}\n"
        )
        return 2

    # Delegate the actual diff logic to the regen script's --check mode.
    # That keeps the lint a thin wrapper and ensures parity with the
    # exact rendering logic that the regen script uses to write artifacts.
    result = subprocess.run(
        [sys.executable, str(REGEN_SCRIPT), "--check"],
        capture_output=True,
        text=True,
    )
    sys.stderr.write(result.stderr)
    sys.stdout.write(result.stdout)
    if result.returncode != 0:
        sys.stderr.write(
            "\n[FAIL] Three-way intent contract drift detected. "
            "Run: python3 tools/contracts/regen_screen_registry_contract.py "
            "and commit the regenerated files.\n"
        )
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())
