#!/usr/bin/env python3
"""MINT v2.2 — Ship Gate Matrix Wrapper (Plan 12-05).

Invokes ``tools/ship_gate/run_all_gates_v2_2.sh``, parses its markdown output,
and writes ``docs/SHIP_GATE_v2.2.md`` — the canonical evidence that v2.2 is
ready to ship (code side). Plan 12-06 adds the human-gated rows.

Usage:
    python3 tools/ship_gate/gate_matrix.py [--out docs/SHIP_GATE_v2.2.md]

Exit codes:
    0  All 18 gates PASS — SHIP READY
    1  At least one gate FAIL — SHIP BLOCKED (report still written)
    2  Runner could not execute or output was unparseable
"""
from __future__ import annotations

import argparse
import datetime as dt
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
RUNNER = REPO_ROOT / "tools" / "ship_gate" / "run_all_gates_v2_2.sh"
DEFAULT_OUT = REPO_ROOT / "docs" / "SHIP_GATE_v2.2.md"

# Gates that are known-RED and tracked under a separate hotfix dispatch.
# These remain ship-blocking but are surfaced as "tracked deferred" in the
# matrix verdict so 12-05 can ship its tooling without owning the fix.
KNOWN_RED_DEFERRED: dict[int, dict] = {
    2: {
        "issue": "21 PremierEclairageCard test failures",
        "owner": "Phase 10 (separate hotfix dispatch by orchestrator)",
        "tracked_in": ".planning/phases/12-l1.6c-ton-ux-ship-gate/12-05-DEFERRED.md",
        "ship_blocking": True,
    },
}

ROW_RE = re.compile(
    r"^\|\s*(\d+)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(PASS|FAIL)\s*\|\s*(\d+)\s*\|\s*`(.+?)`\s*\|\s*$"
)


def run_runner() -> tuple[int, Path]:
    matrix_tmp = Path(tempfile.mkstemp(prefix="mint_ship_gate_", suffix=".md")[1])
    env = os.environ.copy()
    env["SHIP_GATE_OUT"] = str(matrix_tmp)
    print(f"[gate_matrix] Invoking {RUNNER}")
    print(f"[gate_matrix] SHIP_GATE_OUT={matrix_tmp}")
    proc = subprocess.run(
        ["bash", str(RUNNER)],
        cwd=str(REPO_ROOT),
        env=env,
        check=False,
    )
    return proc.returncode, matrix_tmp


def parse_matrix(matrix_path: Path) -> list[dict]:
    rows: list[dict] = []
    if not matrix_path.exists():
        return rows
    for line in matrix_path.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        rows.append(
            {
                "num": int(m.group(1)),
                "name": m.group(2),
                "owner": m.group(3),
                "status": m.group(4),
                "duration": int(m.group(5)),
                "command": m.group(6),
            }
        )
    rows.sort(key=lambda r: r["num"])
    return rows


def git_sha() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=str(REPO_ROOT), text=True
    ).strip()


def git_branch() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=str(REPO_ROOT), text=True
    ).strip()


def render_report(rows: list[dict], out_path: Path) -> int:
    sha = git_sha()
    branch = git_branch()
    run_date = dt.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")

    passed = sum(1 for r in rows if r["status"] == "PASS")
    failed = sum(1 for r in rows if r["status"] == "FAIL")
    total = len(rows)
    deferred_failed = sum(
        1 for r in rows if r["status"] == "FAIL" and r["num"] in KNOWN_RED_DEFERRED
    )
    unknown_failed = failed - deferred_failed
    if failed == 0 and total == 18:
        verdict = "SHIP READY (code side)"
    elif unknown_failed == 0 and deferred_failed > 0:
        verdict = (
            f"SHIP BLOCKED on {deferred_failed} deferred gate(s), "
            f"{passed}/{total} green, awaiting hotfix dispatch"
        )
    else:
        verdict = "SHIP BLOCKED"

    lines: list[str] = []
    lines.append("# MINT v2.2 — Ship Gate Matrix")
    lines.append("")
    lines.append("> Canonical evidence that "
                 "**La Beauté de Mint (v2.2)** is ready to ship — code side.")
    lines.append("> Generated by `tools/ship_gate/gate_matrix.py`. Do not edit by hand.")
    lines.append("")
    lines.append(f"- **Milestone:** v2.2 La Beauté de Mint")
    lines.append(f"- **Branch:** `{branch}`")
    lines.append(f"- **Git SHA:** `{sha}`")
    lines.append(f"- **Run date (UTC):** {run_date}")
    lines.append(f"- **Runner:** `tools/ship_gate/run_all_gates_v2_2.sh`")
    lines.append(f"- **Result:** {passed}/{total} PASS, {failed} FAIL")
    lines.append(f"- **Verdict:** **{verdict}**")
    lines.append("")
    lines.append("## 18-gate matrix")
    lines.append("")
    lines.append("| # | Gate | Owner Phase | Status | Duration (s) | Command |")
    lines.append("|---|------|-------------|--------|--------------|---------|")
    for r in rows:
        cmd_md = r["command"].replace("|", "\\|")
        lines.append(
            f"| {r['num']} | {r['name']} | {r['owner']} | "
            f"{'**' + r['status'] + '**' if r['status'] == 'FAIL' else r['status']} | "
            f"{r['duration']} | `{cmd_md}` |"
        )
    lines.append("")

    if failed > 0:
        lines.append("## Failed gates")
        lines.append("")
        for r in rows:
            if r["status"] != "FAIL":
                continue
            if r["num"] in KNOWN_RED_DEFERRED:
                meta = KNOWN_RED_DEFERRED[r["num"]]
                lines.append(
                    f"- **Gate {r['num']}: {r['name']}** — TRACKED DEFERRED "
                    f"(owner: {meta['owner']}). Issue: {meta['issue']}. "
                    f"Tracked in `{meta['tracked_in']}`. "
                    f"Log: `/tmp/mint_gate_{r['num']}.log`."
                )
            else:
                lines.append(
                    f"- **Gate {r['num']}: {r['name']}** "
                    f"(owner: {r['owner']}) — see "
                    f"`tools/ship_gate/run_all_gates_v2_2.sh` "
                    f"and `/tmp/mint_gate_{r['num']}.log` for details."
                )
        lines.append("")

    lines.append("## Human gates pending (Plan 12-06)")
    lines.append("")
    lines.append("These gates cannot be automated. They are tracked in Plan 12-06 and")
    lines.append("must be signed off by a human reviewer before the v2.2 ship decision.")
    lines.append("")
    lines.append("| # | Gate | Owner | Status |")
    lines.append("|---|------|-------|--------|")
    lines.append("| H1 | ACCESS-01 — manual screen-reader pass (VoiceOver + TalkBack) on S0–S5 | Julien | PENDING |")
    lines.append("| H2 | Krippendorff α ≥ 0.80 on voice corpus (3 raters, 100 samples) | Tester pool | PENDING |")
    lines.append("| H3 | Regional voice spot-check (FR / DE / IT 8 cantons) | Native reviewers | PENDING |")
    lines.append("| H4 | Performance budget on Galaxy A14 (TTI, scroll jank, cold start) | Julien | PENDING |")
    lines.append("| H5 | Compliance read-through (LSFin / LPD / banned-terms) on user-facing copy | Compliance | PENDING |")
    lines.append("| H6 | Final visual QA — all S0–S5 surfaces against `docs/DESIGN_SYSTEM.md` | Julien | PENDING |")
    lines.append("")
    lines.append("## Ship decision")
    lines.append("")
    lines.append("_To be filled by Plan 12-06 once all human gates are signed off._")
    lines.append("")
    lines.append("- [ ] All 18 automated gates green at the same commit")
    lines.append("- [ ] All 6 human gates signed off")
    lines.append("- [ ] Final ship verdict: **\\<TBD by 12-06\\>**")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[gate_matrix] Wrote {out_path}")

    if total != 18:
        print(f"[gate_matrix] WARNING: parsed {total} rows, expected 18", file=sys.stderr)
        return 2
    return 0 if failed == 0 else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="MINT v2.2 ship gate matrix wrapper")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                        help="Output markdown report (default: docs/SHIP_GATE_v2.2.md)")
    args = parser.parse_args()

    if not RUNNER.exists():
        print(f"[gate_matrix] ERROR: runner not found at {RUNNER}", file=sys.stderr)
        return 2

    runner_rc, matrix_tmp = run_runner()
    rows = parse_matrix(matrix_tmp)
    if not rows:
        print(f"[gate_matrix] ERROR: could not parse runner output at {matrix_tmp}",
              file=sys.stderr)
        return 2

    parse_rc = render_report(rows, args.out)

    # Prefer the runner's exit code if it indicates failure; otherwise use parser rc.
    if runner_rc != 0:
        return 1 if parse_rc == 0 else parse_rc
    return parse_rc


if __name__ == "__main__":
    sys.exit(main())
