// GENERATED — Batch18 R1 runtime catalog for the hidden design lab.
// Mirrors product/mint_next/batch17/six-locale-copy.yaml. The 26 canton
// codes, six-locale labels and reviewed per-locale order are byte-identical
// to product/mint_next/batch7/design_lab/test/batch18_canton_fixture.g.dart
// (verified). Screen copy is the accepted Batch17 six-locale copy; the two
// origin-receipt lines are authored here (LSFin-clean, no naked numbers).
// Do not edit by hand.

const Set<String> cantonR1AllowedCodes = <String>{
  'AG', 'AI', 'AR', 'BE', 'BL', 'BS', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SO', 'SZ', 'TG', 'TI', 'UR', 'VD', 'VS', 'ZG', 'ZH',
};

const Map<String, Map<String, String>> cantonR1Labels =
    <String, Map<String, String>>{
  'fr': <String, String>{
    'AG': 'Argovie',
    'AI': 'Appenzell Rhodes-Intérieures',
    'AR': 'Appenzell Rhodes-Extérieures',
    'BE': 'Berne',
    'BL': 'Bâle-Campagne',
    'BS': 'Bâle-Ville',
    'FR': 'Fribourg',
    'GE': 'Genève',
    'GL': 'Glaris',
    'GR': 'Grisons',
    'JU': 'Jura',
    'LU': 'Lucerne',
    'NE': 'Neuchâtel',
    'NW': 'Nidwald',
    'OW': 'Obwald',
    'SG': 'Saint-Gall',
    'SH': 'Schaffhouse',
    'SO': 'Soleure',
    'SZ': 'Schwytz',
    'TG': 'Thurgovie',
    'TI': 'Tessin',
    'UR': 'Uri',
    'VD': 'Vaud',
    'VS': 'Valais',
    'ZG': 'Zoug',
    'ZH': 'Zurich',
  },
  'en': <String, String>{
    'AG': 'Aargau',
    'AI': 'Appenzell Innerrhoden',
    'AR': 'Appenzell Ausserrhoden',
    'BE': 'Bern',
    'BL': 'Basel-Landschaft',
    'BS': 'Basel-Stadt',
    'FR': 'Fribourg',
    'GE': 'Geneva',
    'GL': 'Glarus',
    'GR': 'Graubünden',
    'JU': 'Jura',
    'LU': 'Lucerne',
    'NE': 'Neuchâtel',
    'NW': 'Nidwalden',
    'OW': 'Obwalden',
    'SG': 'St. Gallen',
    'SH': 'Schaffhausen',
    'SO': 'Solothurn',
    'SZ': 'Schwyz',
    'TG': 'Thurgau',
    'TI': 'Ticino',
    'UR': 'Uri',
    'VD': 'Vaud',
    'VS': 'Valais',
    'ZG': 'Zug',
    'ZH': 'Zurich',
  },
  'de': <String, String>{
    'AG': 'Aargau',
    'AI': 'Appenzell Innerrhoden',
    'AR': 'Appenzell Ausserrhoden',
    'BE': 'Bern',
    'BL': 'Basel-Landschaft',
    'BS': 'Basel-Stadt',
    'FR': 'Freiburg',
    'GE': 'Genf',
    'GL': 'Glarus',
    'GR': 'Graubünden',
    'JU': 'Jura',
    'LU': 'Luzern',
    'NE': 'Neuenburg',
    'NW': 'Nidwalden',
    'OW': 'Obwalden',
    'SG': 'St. Gallen',
    'SH': 'Schaffhausen',
    'SO': 'Solothurn',
    'SZ': 'Schwyz',
    'TG': 'Thurgau',
    'TI': 'Tessin',
    'UR': 'Uri',
    'VD': 'Waadt',
    'VS': 'Wallis',
    'ZG': 'Zug',
    'ZH': 'Zürich',
  },
  'it': <String, String>{
    'AG': 'Argovia',
    'AI': 'Appenzello Interno',
    'AR': 'Appenzello Esterno',
    'BE': 'Berna',
    'BL': 'Basilea Campagna',
    'BS': 'Basilea Città',
    'FR': 'Friburgo',
    'GE': 'Ginevra',
    'GL': 'Glarona',
    'GR': 'Grigioni',
    'JU': 'Giura',
    'LU': 'Lucerna',
    'NE': 'Neuchâtel',
    'NW': 'Nidvaldo',
    'OW': 'Obvaldo',
    'SG': 'San Gallo',
    'SH': 'Sciaffusa',
    'SO': 'Soletta',
    'SZ': 'Svitto',
    'TG': 'Turgovia',
    'TI': 'Ticino',
    'UR': 'Uri',
    'VD': 'Vaud',
    'VS': 'Vallese',
    'ZG': 'Zugo',
    'ZH': 'Zurigo',
  },
  'es': <String, String>{
    'AG': 'Argovia',
    'AI': 'Appenzell Rodas Interiores',
    'AR': 'Appenzell Rodas Exteriores',
    'BE': 'Berna',
    'BL': 'Basilea-Campiña',
    'BS': 'Basilea-Ciudad',
    'FR': 'Friburgo',
    'GE': 'Ginebra',
    'GL': 'Glaris',
    'GR': 'Grisones',
    'JU': 'Jura',
    'LU': 'Lucerna',
    'NE': 'Neuchâtel',
    'NW': 'Nidwalden',
    'OW': 'Obwalden',
    'SG': 'San Galo',
    'SH': 'Schaffhausen',
    'SO': 'Soleura',
    'SZ': 'Schwyz',
    'TG': 'Turgovia',
    'TI': 'Tesino',
    'UR': 'Uri',
    'VD': 'Vaud',
    'VS': 'Valais',
    'ZG': 'Zug',
    'ZH': 'Zúrich',
  },
  'pt': <String, String>{
    'AG': 'Argóvia',
    'AI': 'Appenzell Interior',
    'AR': 'Appenzell Exterior',
    'BE': 'Berna',
    'BL': 'Basileia-Campo',
    'BS': 'Basileia-Cidade',
    'FR': 'Friburgo',
    'GE': 'Genebra',
    'GL': 'Glaris',
    'GR': 'Grisões',
    'JU': 'Jura',
    'LU': 'Lucerna',
    'NE': 'Neuchâtel',
    'NW': 'Nidwalden',
    'OW': 'Obwalden',
    'SG': 'São Galo',
    'SH': 'Schaffhausen',
    'SO': 'Soleura',
    'SZ': 'Schwyz',
    'TG': 'Turgóvia',
    'TI': 'Ticino',
    'UR': 'Uri',
    'VD': 'Vaud',
    'VS': 'Valais',
    'ZG': 'Zug',
    'ZH': 'Zurique',
  },
};

const Map<String, List<String>> cantonR1Order = <String, List<String>>{
  'fr': <String>['AR', 'AI', 'AG', 'BL', 'BS', 'BE', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SZ', 'SO', 'TI', 'TG', 'UR', 'VS', 'VD', 'ZG', 'ZH'],
  'en': <String>['AG', 'AR', 'AI', 'BL', 'BS', 'BE', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SH', 'SZ', 'SO', 'SG', 'TG', 'TI', 'UR', 'VS', 'VD', 'ZG', 'ZH'],
  'de': <String>['AG', 'AR', 'AI', 'BL', 'BS', 'BE', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SH', 'SZ', 'SO', 'SG', 'TI', 'TG', 'UR', 'VD', 'VS', 'ZG', 'ZH'],
  'it': <String>['AR', 'AI', 'AG', 'BL', 'BS', 'BE', 'FR', 'GE', 'JU', 'GL', 'GR', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SO', 'SZ', 'TI', 'TG', 'UR', 'VS', 'VD', 'ZG', 'ZH'],
  'es': <String>['AR', 'AI', 'AG', 'BL', 'BS', 'BE', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SZ', 'SO', 'TI', 'TG', 'UR', 'VS', 'VD', 'ZG', 'ZH'],
  'pt': <String>['AR', 'AI', 'AG', 'BL', 'BS', 'BE', 'FR', 'GE', 'GL', 'GR', 'JU', 'LU', 'NE', 'NW', 'OW', 'SG', 'SH', 'SZ', 'SO', 'TI', 'TG', 'UR', 'VS', 'VD', 'ZG', 'ZH'],
};

class CantonR1Copy {
  const CantonR1Copy({
    required this.eyebrow,
    required this.question,
    required this.body,
    required this.searchLabel,
    required this.searchEmpty,
    required this.clearSearch,
    required this.privacy,
    required this.back,
    required this.originNo,
    required this.originPositive,
  });

  /// Templates below contain the literal token {taxYear}; the runtime
  /// substitutes the selected tax year. No other interpolation is used.
  final String eyebrow;
  final String question;
  final String body;
  final String searchLabel;
  final String searchEmpty;
  final String clearSearch;
  final String privacy;
  final String back;
  final String originNo;
  final String originPositive;
}

const Map<String, CantonR1Copy> cantonR1Copy = <String, CantonR1Copy>{
  'fr': CantonR1Copy(
    eyebrow: 'Simulation 3a · {taxYear}',
    question: 'Dans quel canton es-tu imposé pour {taxYear} ?',
    body: 'Choisis le canton fiscal applicable à ta situation fiscale simple pour {taxYear}, pas l’endroit où se trouve ton appareil aujourd’hui. La commune sera demandée ensuite. Aucun résultat fiscal personnel n’est encore calculé à cette étape. Si tu as déménagé ou si ta situation est plus complexe, choisis « Je ne sais pas / ma situation est complexe ».',
    searchLabel: 'Rechercher un canton',
    searchEmpty: 'Aucun canton trouvé',
    clearSearch: 'Effacer la recherche',
    privacy: 'Choix temporaire et non envoyé. Il est effacé quand tu quittes ce parcours, même si tu conserves une référence générale, ou après 30 minutes d’inactivité.',
    back: 'Retour',
    originNo: 'Origine : sans versement déclaré.',
    originPositive: 'Origine : versement déclaré.',
  ),
  'en': CantonR1Copy(
    eyebrow: '3a simulation · {taxYear}',
    question: 'In which canton are you taxed for {taxYear}?',
    body: 'Choose the tax canton that applies to your straightforward tax situation for {taxYear}, not where your device is today. We will ask for the municipality next. No personal tax result has been calculated at this step. If you moved or your situation is more complex, choose “I’m not sure / my situation is complex”.',
    searchLabel: 'Search for a canton',
    searchEmpty: 'No canton found',
    clearSearch: 'Clear search',
    privacy: 'This choice is temporary and is not sent anywhere. It is deleted when you leave this journey, even if you keep a general reference, or after 30 minutes of inactivity.',
    back: 'Back',
    originNo: 'Origin: no contribution reported.',
    originPositive: 'Origin: contribution reported.',
  ),
  'de': CantonR1Copy(
    eyebrow: '3a-Simulation · {taxYear}',
    question: 'In welchem Kanton wirst du für {taxYear} besteuert?',
    body: 'Wähle den Steuerkanton, der für deine einfache Steuersituation in {taxYear} gilt, nicht den heutigen Standort deines Geräts. Danach fragen wir nach der Gemeinde. In diesem Schritt wurde noch kein persönliches Steuerergebnis berechnet. Wenn du umgezogen bist oder deine Situation komplexer ist, wähle «Ich bin nicht sicher / meine Situation ist komplex».',
    searchLabel: 'Kanton suchen',
    searchEmpty: 'Kein Kanton gefunden',
    clearSearch: 'Suche löschen',
    privacy: 'Diese Auswahl ist vorübergehend und wird nicht übermittelt. Sie wird beim Verlassen dieses Ablaufs gelöscht, auch wenn du eine allgemeine Referenz behältst, oder nach 30 Minuten Inaktivität.',
    back: 'Zurück',
    originNo: 'Herkunft: keine Einzahlung angegeben.',
    originPositive: 'Herkunft: Einzahlung angegeben.',
  ),
  'it': CantonR1Copy(
    eyebrow: 'Simulazione 3a · {taxYear}',
    question: 'In quale Cantone sei tassato per il {taxYear}?',
    body: 'Scegli il cantone fiscale applicabile alla tua situazione fiscale semplice per il {taxYear}, non il luogo in cui si trova oggi il tuo dispositivo. In seguito chiederemo il comune. In questa fase non è ancora stato calcolato alcun risultato fiscale personale. Se ti sei trasferito o la tua situazione è più complessa, scegli «Non ne sono sicuro / la mia situazione è complessa».',
    searchLabel: 'Cerca un cantone',
    searchEmpty: 'Nessun cantone trovato',
    clearSearch: 'Cancella la ricerca',
    privacy: 'Questa scelta è temporanea e non viene trasmessa. È cancellata quando lasci questo percorso, anche se conservi un riferimento generale, o dopo 30 minuti di inattività.',
    back: 'Indietro',
    originNo: 'Origine: nessun versamento indicato.',
    originPositive: 'Origine: versamento indicato.',
  ),
  'es': CantonR1Copy(
    eyebrow: 'Simulación 3a · {taxYear}',
    question: '¿En qué cantón tributas en {taxYear}?',
    body: 'Elige el cantón fiscal aplicable a tu situación fiscal sencilla en {taxYear}, no el lugar donde se encuentra hoy tu dispositivo. Después preguntaremos el municipio. En este paso aún no se ha calculado ningún resultado fiscal personal. Si te has mudado o tu situación es más compleja, elige «No estoy seguro / mi situación es compleja».',
    searchLabel: 'Buscar un cantón',
    searchEmpty: 'No se ha encontrado ningún cantón',
    clearSearch: 'Borrar búsqueda',
    privacy: 'Esta elección es temporal y no se envía. Se elimina cuando abandonas este recorrido, aunque conserves una referencia general, o tras 30 minutos de inactividad.',
    back: 'Volver',
    originNo: 'Origen: sin aportación indicada.',
    originPositive: 'Origen: aportación indicada.',
  ),
  'pt': CantonR1Copy(
    eyebrow: 'Simulação 3a · {taxYear}',
    question: 'Em que cantão és tributado em {taxYear}?',
    body: 'Escolhe o cantão fiscal aplicável à tua situação fiscal simples em {taxYear}, não o local onde o teu dispositivo se encontra hoje. A seguir perguntaremos o município. Nesta etapa ainda não foi calculado qualquer resultado fiscal pessoal. Se mudaste de residência ou a tua situação é mais complexa, escolhe «Não tenho a certeza / a minha situação é complexa».',
    searchLabel: 'Procurar um cantão',
    searchEmpty: 'Nenhum cantão encontrado',
    clearSearch: 'Limpar pesquisa',
    privacy: 'Esta escolha é temporária e não é enviada. É eliminada quando sais deste percurso, mesmo que guardes uma referência geral, ou após 30 minutos de inatividade.',
    back: 'Voltar',
    originNo: 'Origem: sem contribuição indicada.',
    originPositive: 'Origem: contribuição indicada.',
  ),
};
