// Phase 57 PR-A — anonymous chat persistence (data layer).
//
// Closes the « 3-msg dead-end » UX bug : anonymous user types 3 messages,
// kills the app, comes back to a blank canvas (state was in-memory only).
// This service writes a versioned, TTL-bounded snapshot of the
// conversation to SharedPreferences so the chat hydrates on app resume.
//
// Storage envelope (single key `mint.anonymous.chat.v1`) :
//
//   {
//     "version": 1,
//     "expiresAt": "<ISO-8601 UTC>",
//     "intent": "<optional canonical intent>",
//     "messages": [
//       { "role": "user|assistant|system",
//         "content": "<utf8 text>",
//         "ts": "<ISO-8601 UTC>" },
//       ...
//     ]
//   }
//
// The persisted message shape is INTENTIONALLY minimal — three fields
// only — because the rich `ChatMessage` (response cards, route payloads,
// rich-tool calls, RAG sources, etc.) is a per-turn coach derivation and
// will be regenerated by the backend when the conversation resumes. Only
// the human-typed and assistant-spoken text needs to survive an app kill.
//
// PII discipline (Pitfall 6) :
//   - SharedPreferences (plaintext on disk) is acceptable here because
//     the anonymous tier hasn't accepted any LSFin/banking data yet ;
//     the « content » field carries chat text only, not bank credentials,
//     IBAN, or AVS numbers (those gate at the auth-required tier).
//   - On `register_success`, AnonymousChatScreen MUST call clear() —
//     we do NOT keep the anonymous transcript past account creation,
//     to avoid creating a per-user log that wasn't covered by the
//     consent screen.
//
// TTL : 7 days. Anonymous conversations older than that get dropped on
// the next load() — Cleo-style « we won't remember you forever, the
// promise stays small ». No background sweeper ; expiry is a load-time
// gate.
//
// Versioning : the envelope's `version` field is read on load() ; a
// mismatched version is treated as missing data (clean slate). Callers
// should bump this constant when the schema breaks.

import 'dart:async';
import 'dart:convert';

import 'package:shared_preferences/shared_preferences.dart';

import 'package:mint_mobile/services/coach_llm_service.dart' show ChatMessage;

/// Minimal triplet persisted per message. Use [hydrate] to materialise a
/// `ChatMessage` from this record (carries empty defaults for the rich
/// fields the backend will re-derive on resume).
class AnonymousChatRecord {
  const AnonymousChatRecord({
    required this.role,
    required this.content,
    required this.timestamp,
  });

  final String role; // 'user' | 'assistant' | 'system'
  final String content;
  final DateTime timestamp;

  Map<String, String> toMap() => <String, String>{
        'role': role,
        'content': content,
        'ts': timestamp.toUtc().toIso8601String(),
      };

  static AnonymousChatRecord? fromMap(Map<String, dynamic> map) {
    final role = map['role'];
    final content = map['content'];
    final ts = map['ts'];
    if (role is! String || content is! String || ts is! String) {
      return null;
    }
    final parsed = DateTime.tryParse(ts);
    if (parsed == null) return null;
    return AnonymousChatRecord(
      role: role,
      content: content,
      timestamp: parsed,
    );
  }

  /// Project this record into a `ChatMessage` with empty rich fields. The
  /// backend will repopulate cards / tools / sources on the next turn.
  ChatMessage hydrate() => ChatMessage(
        role: role,
        content: content,
        timestamp: timestamp,
      );
}

/// Snapshot returned by [AnonymousChatPersistence.load].
class AnonymousChatSnapshot {
  const AnonymousChatSnapshot({
    required this.messages,
    required this.expiresAt,
    this.intent,
  });

  final List<AnonymousChatRecord> messages;
  final DateTime expiresAt;
  final String? intent;
}

/// Persists / restores anonymous-tier chat transcripts via SharedPreferences.
///
/// All methods are safe to call when the storage backend fails — they
/// degrade silently to "no snapshot" rather than throwing, so a bad
/// install never blocks the chat UI.
class AnonymousChatPersistence {
  AnonymousChatPersistence({
    Duration? ttl,
    Future<SharedPreferences> Function()? prefsFactory,
  })  : _ttl = ttl ?? _defaultTtl,
        _prefsFactory = prefsFactory ?? SharedPreferences.getInstance;

  /// Bumped when the storage envelope changes shape.
  static const int schemaVersion = 1;

  /// Single SharedPreferences key carrying the JSON envelope.
  static const String storageKey = 'mint.anonymous.chat.v1';

  static const Duration _defaultTtl = Duration(days: 7);

  final Duration _ttl;
  final Future<SharedPreferences> Function() _prefsFactory;

  /// Write the [messages] (and optional [intent]) to disk with a fresh
  /// `expiresAt` of `now + ttl`. Returns silently on any storage error —
  /// callers must not depend on persistence as a correctness gate.
  Future<void> save({
    required List<ChatMessage> messages,
    String? intent,
  }) async {
    try {
      final prefs = await _prefsFactory();
      final records = messages
          .map((m) => AnonymousChatRecord(
                role: m.role,
                content: m.content,
                timestamp: m.timestamp,
              ).toMap())
          .toList(growable: false);
      final envelope = <String, dynamic>{
        'version': schemaVersion,
        'expiresAt':
            DateTime.now().toUtc().add(_ttl).toIso8601String(),
        if (intent != null && intent.isNotEmpty) 'intent': intent,
        'messages': records,
      };
      await prefs.setString(storageKey, jsonEncode(envelope));
    } catch (_) {
      // Storage failure — caller continues, snapshot lost.
    }
  }

  /// Read the snapshot from disk. Returns null if missing, expired, or
  /// any of the envelope fields fail validation (treat as clean slate).
  Future<AnonymousChatSnapshot?> load() async {
    try {
      final prefs = await _prefsFactory();
      final raw = prefs.getString(storageKey);
      if (raw == null || raw.isEmpty) return null;

      final dynamic decoded = jsonDecode(raw);
      if (decoded is! Map<String, dynamic>) return null;

      final version = decoded['version'];
      if (version is! int || version != schemaVersion) return null;

      final expiresAtRaw = decoded['expiresAt'];
      if (expiresAtRaw is! String) return null;
      final expiresAt = DateTime.tryParse(expiresAtRaw);
      if (expiresAt == null) return null;
      if (DateTime.now().toUtc().isAfter(expiresAt.toUtc())) return null;

      final rawMessages = decoded['messages'];
      if (rawMessages is! List) return null;
      final records = <AnonymousChatRecord>[];
      for (final item in rawMessages) {
        if (item is! Map) continue;
        final record = AnonymousChatRecord.fromMap(
          item.cast<String, dynamic>(),
        );
        if (record != null) records.add(record);
      }

      final intentRaw = decoded['intent'];
      final intent = (intentRaw is String && intentRaw.isNotEmpty)
          ? intentRaw
          : null;

      return AnonymousChatSnapshot(
        messages: records,
        expiresAt: expiresAt,
        intent: intent,
      );
    } catch (_) {
      return null;
    }
  }

  /// Drop the snapshot. Idempotent — calling twice is safe.
  ///
  /// MUST be called by the auth flow on `register_success` so the
  /// anonymous transcript is not retained past account creation.
  Future<void> clear() async {
    try {
      final prefs = await _prefsFactory();
      await prefs.remove(storageKey);
    } catch (_) {
      // Best-effort.
    }
  }

  /// Convenience predicate : returns true if a snapshot exists but its
  /// expiresAt has passed. Callers that don't need the messages can use
  /// this to decide whether to render a "resume" affordance vs a fresh
  /// chat surface.
  Future<bool> isExpired() async {
    try {
      final prefs = await _prefsFactory();
      final raw = prefs.getString(storageKey);
      if (raw == null || raw.isEmpty) return false;
      final decoded = jsonDecode(raw);
      if (decoded is! Map<String, dynamic>) return false;
      final expiresAtRaw = decoded['expiresAt'];
      if (expiresAtRaw is! String) return false;
      final expiresAt = DateTime.tryParse(expiresAtRaw);
      if (expiresAt == null) return false;
      return DateTime.now().toUtc().isAfter(expiresAt.toUtc());
    } catch (_) {
      return false;
    }
  }
}
