"""Unit tests for RegionalMicrocopy — Phase 6 / REGIONAL-04 + REGIONAL-05.

Covers:
- canton resolution (primary, secondary Romande -> VS flip per D-05,
  Deutschschweiz -> ZH, GR -> TI, unknown, None, lowercase)
- identity_block content (non-empty for known cantons, neutral fallback
  for None / unknown)
- codegen determinism (running twice produces byte-identical output)
- generated file header marker
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from app.services.coach.regional_microcopy import (
    CANTON_TO_PRIMARY,
    RegionalMicrocopy,
)

REPO_ROOT = Path(__file__).resolve().parents[5]
GENERATED = (
    REPO_ROOT
    / "services"
    / "backend"
    / "app"
    / "services"
    / "coach"
    / "regional_microcopy.py"
)
CODEGEN = REPO_ROOT / "tools" / "regional" / "regional_microcopy_codegen.py"


# ---------------------------------------------------------------------------
# resolve()
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "raw,expected",
    [
        # Primary anchors map to themselves
        ("VS", "VS"),
        ("ZH", "ZH"),
        ("TI", "TI"),
        # Romande secondary cantons -> VS (D-05 flip)
        ("VD", "VS"),
        ("GE", "VS"),
        ("NE", "VS"),
        ("JU", "VS"),
        ("FR", "VS"),
        # Deutschschweiz secondary cantons -> ZH
        ("BE", "ZH"),
        ("LU", "ZH"),
        ("AG", "ZH"),
        ("BS", "ZH"),
        ("BL", "ZH"),
        ("ZG", "ZH"),
        # Italiana
        ("GR", "TI"),
        # Case-insensitive
        ("vs", "VS"),
        ("vd", "VS"),
        ("zh", "ZH"),
        # Whitespace tolerant
        (" VS ", "VS"),
    ],
)
def test_resolve_known(raw: str, expected: str) -> None:
    assert RegionalMicrocopy.resolve(raw) == expected


def test_resolve_none_returns_none() -> None:
    assert RegionalMicrocopy.resolve(None) is None


def test_resolve_empty_returns_none() -> None:
    assert RegionalMicrocopy.resolve("") is None


def test_resolve_unknown_returns_none() -> None:
    assert RegionalMicrocopy.resolve("XX") is None
    assert RegionalMicrocopy.resolve("ZZ") is None


def test_canton_to_primary_covers_all_swiss_secondaries() -> None:
    """All 23 secondary cantons must route to one of VS/ZH/TI (D-05)."""
    expected_secondaries = {
        # Romande -> VS
        "VD", "GE", "NE", "JU", "FR",
        # Deutschschweiz -> ZH
        "BE", "LU", "AG", "SG", "TG", "SO", "SH", "AR", "AI",
        "OW", "NW", "GL", "SZ", "UR", "ZG", "BL", "BS",
        # Italiana
        "GR",
    }
    assert set(CANTON_TO_PRIMARY.keys()) == expected_secondaries
    assert set(CANTON_TO_PRIMARY.values()) <= {"VS", "ZH", "TI"}


def test_romande_cantons_anchor_to_vs_not_vd() -> None:
    """REGIONAL-04 D-05 routing flip: Romande anchor is VS, not VD."""
    for romand in ("VD", "GE", "NE", "JU", "FR"):
        assert RegionalMicrocopy.resolve(romand) == "VS"


# ---------------------------------------------------------------------------
# identity_block()
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("canton,marker", [
    ("VS", "Romande"),
    ("ZH", "Deutschschweiz"),
    ("TI", "Italiana"),
])
def test_identity_block_known_canton(canton: str, marker: str) -> None:
    block = RegionalMicrocopy.identity_block(canton)
    assert block
    assert marker in block
    assert canton in block


def test_identity_block_secondary_canton_routes_to_anchor() -> None:
    # VD must yield the VS Romande block
    vd_block = RegionalMicrocopy.identity_block("VD")
    vs_block = RegionalMicrocopy.identity_block("VS")
    assert vd_block == vs_block
    assert "Romande" in vd_block


def test_identity_block_none_returns_neutral() -> None:
    block = RegionalMicrocopy.identity_block(None)
    assert "REGIONAL IDENTITY" in block
    assert "no canton" in block.lower()


def test_identity_block_unknown_returns_neutral() -> None:
    assert RegionalMicrocopy.identity_block("XX") == RegionalMicrocopy.identity_block(None)


# ---------------------------------------------------------------------------
# Codegen determinism + drift guard
# ---------------------------------------------------------------------------


def test_generated_file_has_header_marker() -> None:
    content = GENERATED.read_text(encoding="utf-8")
    assert content.startswith("# GENERATED by tools/regional/regional_microcopy_codegen.py")


def test_codegen_is_deterministic(tmp_path: Path) -> None:
    """Running the codegen twice must produce byte-identical output."""
    first = GENERATED.read_bytes()
    subprocess.run(
        [sys.executable, str(CODEGEN)],
        check=True,
        capture_output=True,
    )
    second = GENERATED.read_bytes()
    assert first == second, "regional_microcopy.py drifted across two runs"
