-- Phase mint-data-architecture-v1-02 W0 Plan 02-01 (D-23) — pg_dump baseline reference.
--
-- Snapshot date : 2026-05-18
-- Alembic heads at snapshot : p112_audit_event_user_hash, p86_eclairage_delivered
--   (pre-existing dual-head condition — see deferred-items.md DEFERRED-02-01-A)
-- Generated by : tools/db/regenerate_baseline.sh OR (when Docker unavailable
--   locally) a deterministic SQLAlchemy-metadata DDL emitter that walks
--   `Base.metadata.tables` sorted alphabetically + emits CreateTable +
--   CreateIndex statements via the postgresql dialect.
--
-- Reproducibility contract :
--   * `bash tools/db/regenerate_baseline.sh` running against the same alembic
--     head twice yields `git diff --exit-code` exit 0.
--   * The deterministic SQLAlchemy fallback (used here in environments
--     without Docker) produces a stable canonical DDL form — re-running the
--     generator with the same model imports yields byte-identical output.
--   * This file MUST be regenerated by Plan 02-02 when p98_fact_event ships
--     (the 2026-05-18 stamp is the PRE-PHASE-02 baseline — do NOT rename
--     across regenerations, this is the stable historical anchor).
--
-- Format note : DDL below is normalized — leading/trailing whitespace stripped,
-- tables sorted alphabetically, indexes per-table sorted alphabetically. This
-- diverges from `pg_dump --schema-only` byte-output (which has owner blocks,
-- search_path SET commands, etc.) but contains the same logical schema and is
-- the form the CI baseline check compares against.

-- Dumped by pg_dump version <masked-for-reproducibility>

CREATE TABLE admin_audit_events (
	id VARCHAR NOT NULL,
	admin_user_id VARCHAR NOT NULL,
	action VARCHAR NOT NULL,
	target_user_id VARCHAR NOT NULL,
	reason TEXT NOT NULL,
	ip_address VARCHAR,
	user_agent VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(admin_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_admin_audit_events_action ON admin_audit_events (action);

CREATE INDEX ix_admin_audit_events_admin_user_id ON admin_audit_events (admin_user_id);

CREATE INDEX ix_admin_audit_events_target_user_id ON admin_audit_events (target_user_id);

CREATE TABLE analytics_events (
	id SERIAL NOT NULL,
	event_name VARCHAR NOT NULL,
	event_category VARCHAR NOT NULL,
	event_data TEXT,
	session_id VARCHAR,
	user_id VARCHAR,
	screen_name VARCHAR,
	timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	app_version VARCHAR,
	platform VARCHAR,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_analytics_events_event_category ON analytics_events (event_category);

CREATE INDEX ix_analytics_events_event_name ON analytics_events (event_name);

CREATE INDEX ix_analytics_events_screen_name ON analytics_events (screen_name);

CREATE INDEX ix_analytics_events_session_id ON analytics_events (session_id);

CREATE INDEX ix_analytics_events_timestamp ON analytics_events (timestamp);

CREATE INDEX ix_analytics_events_user_id ON analytics_events (user_id);

CREATE INDEX ix_analytics_user_timestamp ON analytics_events (user_id, timestamp);

CREATE TABLE anonymous_sessions (
	session_id VARCHAR(36) NOT NULL,
	message_count INTEGER NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	eclairage_delivered BOOLEAN DEFAULT '0' NOT NULL,
	PRIMARY KEY (session_id)
);

CREATE TABLE audit_events (
	id VARCHAR NOT NULL,
	user_id VARCHAR,
	user_id_hash VARCHAR(64),
	actor_email VARCHAR,
	event_type VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	source VARCHAR NOT NULL,
	ip_address VARCHAR,
	user_agent VARCHAR,
	details_json TEXT,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id)
);

CREATE INDEX ix_audit_events_created_at ON audit_events (created_at);

CREATE INDEX ix_audit_events_event_type ON audit_events (event_type);

CREATE INDEX ix_audit_events_user_id ON audit_events (user_id);

CREATE INDEX ix_audit_events_user_id_hash ON audit_events (user_id_hash);

CREATE TABLE banking_consents (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	bank_id VARCHAR NOT NULL,
	bank_name VARCHAR NOT NULL,
	scopes TEXT NOT NULL,
	status VARCHAR NOT NULL,
	granted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_banking_consents_status ON banking_consents (user_id, status);

CREATE INDEX ix_banking_consents_user_id ON banking_consents (user_id);

CREATE TABLE billing_transactions (
	id VARCHAR NOT NULL,
	subscription_id VARCHAR NOT NULL,
	provider_transaction_id VARCHAR,
	amount_cents INTEGER NOT NULL,
	currency VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	raw_payload TEXT,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(subscription_id) REFERENCES subscriptions (id)
);

CREATE INDEX ix_billing_transactions_provider_transaction_id ON billing_transactions (provider_transaction_id);

CREATE INDEX ix_billing_transactions_subscription_id ON billing_transactions (subscription_id);

CREATE TABLE billing_webhook_events (
	id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	event_id VARCHAR NOT NULL,
	event_type VARCHAR NOT NULL,
	subscription_id VARCHAR,
	outcome VARCHAR NOT NULL,
	is_processed BOOLEAN NOT NULL,
	payload TEXT,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_billing_provider_event UNIQUE (provider, event_id),
	FOREIGN KEY(subscription_id) REFERENCES subscriptions (id)
);

CREATE INDEX ix_billing_webhook_events_event_id ON billing_webhook_events (event_id);

CREATE INDEX ix_billing_webhook_events_event_type ON billing_webhook_events (event_type);

CREATE INDEX ix_billing_webhook_events_provider ON billing_webhook_events (provider);

CREATE INDEX ix_billing_webhook_events_subscription_id ON billing_webhook_events (subscription_id);

CREATE TABLE coach_insights (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	topic VARCHAR NOT NULL,
	summary TEXT NOT NULL,
	insight_type VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_coach_insights_user_id ON coach_insights (user_id);

CREATE INDEX ix_coach_insights_user_topic ON coach_insights (user_id, topic);

CREATE TABLE consents (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	consent_type VARCHAR,
	enabled BOOLEAN NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	receipt_id VARCHAR(36),
	purpose_category VARCHAR(64),
	policy_version VARCHAR(32),
	policy_hash VARCHAR(64),
	consent_timestamp TIMESTAMP WITHOUT TIME ZONE,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	receipt_json JSONB,
	prev_hash VARCHAR(64),
	signature VARCHAR(64),
	PRIMARY KEY (id)
);

CREATE INDEX ix_consents_purpose_category ON consents (purpose_category);

CREATE UNIQUE INDEX ix_consents_receipt_id ON consents (receipt_id);

CREATE INDEX ix_consents_user_id ON consents (user_id);

CREATE INDEX ix_consents_user_purpose ON consents (user_id, purpose_category, revoked_at);

CREATE INDEX ix_consents_user_type ON consents (user_id, consent_type);

CREATE TABLE dek_vault (
	user_id VARCHAR NOT NULL,
	wrapped_dek BYTEA,
	kms_key_ref VARCHAR(256),
	algo VARCHAR(32) NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	rotated_at TIMESTAMP WITHOUT TIME ZONE,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (user_id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE document_memory (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	fingerprint VARCHAR(128) NOT NULL,
	doc_type VARCHAR NOT NULL,
	issuer VARCHAR,
	last_seen_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	field_history JSON NOT NULL,
	evidence_text TEXT,
	evidence_text_enc BYTEA,
	vision_raw TEXT,
	vision_raw_enc BYTEA,
	PRIMARY KEY (id),
	CONSTRAINT uq_document_memory_user_fp UNIQUE (user_id, fingerprint),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_document_memory_fingerprint ON document_memory (fingerprint);

CREATE INDEX ix_document_memory_user_fp ON document_memory (user_id, fingerprint);

CREATE INDEX ix_document_memory_user_id ON document_memory (user_id);

CREATE TABLE documents (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	document_type VARCHAR NOT NULL,
	upload_date TIMESTAMP WITHOUT TIME ZONE,
	confidence FLOAT,
	fields_found INTEGER,
	fields_total INTEGER,
	extracted_fields JSON,
	warnings JSON,
	extraction_method VARCHAR,
	overall_confidence FLOAT,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_documents_user_id ON documents (user_id);

CREATE TABLE earmark_tags (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	label VARCHAR NOT NULL,
	source_description TEXT,
	amount_hint VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_earmark_tags_user_id ON earmark_tags (user_id);

CREATE INDEX ix_earmark_tags_user_label ON earmark_tags (user_id, label);

CREATE TABLE email_verification_tokens (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	token_hash VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	used_at TIMESTAMP WITHOUT TIME ZONE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_email_verification_tokens_token_hash ON email_verification_tokens (token_hash);

CREATE INDEX ix_email_verification_tokens_user_id ON email_verification_tokens (user_id);

CREATE TABLE entitlements (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	subscription_id VARCHAR,
	feature_key VARCHAR NOT NULL,
	is_active BOOLEAN NOT NULL,
	granted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_entitlement_user_feature UNIQUE (user_id, feature_key),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY(subscription_id) REFERENCES subscriptions (id)
);

CREATE INDEX ix_entitlements_feature_key ON entitlements (feature_key);

CREATE INDEX ix_entitlements_subscription_id ON entitlements (subscription_id);

CREATE INDEX ix_entitlements_user_id ON entitlements (user_id);

CREATE TABLE external_data_sources (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	source_type VARCHAR NOT NULL,
	cached_response TEXT NOT NULL,
	fetched_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_external_data_sources_expires ON external_data_sources (expires_at);

CREATE UNIQUE INDEX ix_external_data_sources_user_source ON external_data_sources (user_id, source_type);

CREATE TABLE household_members (
	id VARCHAR NOT NULL,
	household_id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	role VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	invitation_code VARCHAR,
	invited_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	accepted_at TIMESTAMP WITHOUT TIME ZONE,
	cooldown_override BOOLEAN NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_household_member_user UNIQUE (user_id),
	CONSTRAINT ck_household_member_role CHECK (role IN ('owner', 'partner')),
	CONSTRAINT ck_household_member_status CHECK (status IN ('pending', 'active', 'revoked')),
	FOREIGN KEY(household_id) REFERENCES households (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_household_members_household_id ON household_members (household_id);

CREATE UNIQUE INDEX ix_household_members_invitation_code ON household_members (invitation_code);

CREATE INDEX ix_household_members_user_id ON household_members (user_id);

CREATE TABLE households (
	id VARCHAR NOT NULL,
	household_owner_user_id VARCHAR NOT NULL,
	billing_owner_user_id VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(household_owner_user_id) REFERENCES users (id) ON DELETE CASCADE,
	FOREIGN KEY(billing_owner_user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_households_billing_owner_user_id ON households (billing_owner_user_id);

CREATE INDEX ix_households_household_owner_user_id ON households (household_owner_user_id);

CREATE TABLE login_security_states (
	id VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	failed_attempts INTEGER NOT NULL,
	next_allowed_at TIMESTAMP WITHOUT TIME ZONE,
	lockout_until TIMESTAMP WITHOUT TIME ZONE,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_login_security_states_email ON login_security_states (email);

CREATE TABLE magic_link_tokens (
	id VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	token_hash VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	used BOOLEAN NOT NULL,
	used_at TIMESTAMP WITHOUT TIME ZONE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id)
);

CREATE INDEX ix_magic_link_tokens_email ON magic_link_tokens (email);

CREATE UNIQUE INDEX ix_magic_link_tokens_token_hash ON magic_link_tokens (token_hash);

CREATE TABLE password_reset_tokens (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	token_hash VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	used_at TIMESTAMP WITHOUT TIME ZONE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_password_reset_tokens_token_hash ON password_reset_tokens (token_hash);

CREATE INDEX ix_password_reset_tokens_user_id ON password_reset_tokens (user_id);

CREATE TABLE profiles (
	id VARCHAR NOT NULL,
	user_id VARCHAR,
	data TEXT NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_profiles_user_id ON profiles (user_id);

CREATE TABLE projection_audit_records (
	id VARCHAR NOT NULL,
	user_id_hash VARCHAR(64) NOT NULL,
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	projection_type VARCHAR(32) NOT NULL,
	projection_id VARCHAR NOT NULL,
	constants_version_hash VARCHAR(64) NOT NULL,
	scenario_inputs_hash VARCHAR(64) NOT NULL,
	output_hash VARCHAR(64) NOT NULL,
	lsfin_disclaimer_shown BOOLEAN NOT NULL,
	PRIMARY KEY (id)
);

CREATE INDEX ix_projection_audit_user_computed ON projection_audit_records (user_id_hash, computed_at);

CREATE TABLE provenance_records (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	product_type VARCHAR NOT NULL,
	recommended_by VARCHAR NOT NULL,
	institution VARCHAR,
	context_note TEXT,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_provenance_records_user_id ON provenance_records (user_id);

CREATE INDEX ix_provenance_records_user_product ON provenance_records (user_id, product_type);

CREATE TABLE scenarios (
	id VARCHAR NOT NULL,
	profile_id VARCHAR NOT NULL,
	kind VARCHAR NOT NULL,
	inputs JSON,
	outputs JSON,
	inputs_hash VARCHAR(64),
	superseded_by VARCHAR(36),
	created_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);

CREATE INDEX ix_scenarios_profile_id ON scenarios (profile_id);

CREATE TABLE sessions (
	id VARCHAR NOT NULL,
	profile_id VARCHAR NOT NULL,
	data TEXT NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(profile_id) REFERENCES profiles (id)
);

CREATE INDEX ix_sessions_profile_id ON sessions (profile_id);

CREATE TABLE snapshots (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	trigger VARCHAR NOT NULL,
	model_version VARCHAR NOT NULL,
	constants_version_hash VARCHAR(64),
	age INTEGER DEFAULT 0,
	birth_date VARCHAR,
	gross_income FLOAT DEFAULT 0.0,
	canton VARCHAR DEFAULT 'VD',
	archetype VARCHAR DEFAULT 'swiss_native',
	household_type VARCHAR DEFAULT 'single',
	replacement_ratio FLOAT DEFAULT 0.0,
	months_liquidity FLOAT DEFAULT 0.0,
	tax_saving_potential FLOAT DEFAULT 0.0,
	confidence_score FLOAT DEFAULT 0.0,
	enrichment_count INTEGER DEFAULT 0,
	fri_total FLOAT DEFAULT 0.0,
	fri_l FLOAT DEFAULT 0.0,
	fri_f FLOAT DEFAULT 0.0,
	fri_r FLOAT DEFAULT 0.0,
	fri_s FLOAT DEFAULT 0.0,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_snapshots_created_at ON snapshots (created_at);

CREATE INDEX ix_snapshots_user_created ON snapshots (user_id, created_at);

CREATE INDEX ix_snapshots_user_id ON snapshots (user_id);

CREATE TABLE subscriptions (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	tier VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	source VARCHAR NOT NULL,
	is_trial BOOLEAN NOT NULL,
	current_period_end TIMESTAMP WITHOUT TIME ZONE,
	external_customer_id VARCHAR,
	external_subscription_id VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	last_event_at TIMESTAMP WITHOUT TIME ZONE,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_subscription_user_source UNIQUE (user_id, source),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_subscriptions_external_customer_id ON subscriptions (external_customer_id);

CREATE INDEX ix_subscriptions_external_subscription_id ON subscriptions (external_subscription_id);

CREATE INDEX ix_subscriptions_user_id ON subscriptions (user_id);

CREATE TABLE token_blacklist (
	jti VARCHAR(64) NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	blacklisted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (jti)
);

CREATE INDEX ix_token_blacklist_expires_at ON token_blacklist (expires_at);

CREATE TABLE users (
	id VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	hashed_password VARCHAR NOT NULL,
	display_name VARCHAR,
	email_verified BOOLEAN NOT NULL,
	role VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	password_changed_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id)
);

CREATE UNIQUE INDEX ix_users_email ON users (email);
