#!/usr/bin/env python3
"""Phase mint-data-architecture-v1-01 Plan 01 — D-14 bundle-size validation.

Serialises the active ``RegulatoryRegistry`` snapshot (CH + 26 cantons) to
deterministic JSON, gzip-compresses, and reports the raw / gzip byte counts
against the 100 KB ceiling locked in CONTEXT.md §Decisions D-14.

Run pre-build to catch threshold breaches before they ship in a Flutter bundle :

    python3 tools/measurement/regulatory_snapshot_bundle_size.py --ci

Exit codes :
    0  PASS — gzip_bytes < 102 400 (100 KB)
    1  FAIL — D-14 re-litigation trigger fired ; the doctrine ADR must be
       revised toward lazy per-canton fetch before Plan 02 ships.

The script is a one-shot measurement tool, NOT a public API endpoint. Plan 03
adds the ``/v1/regulatory/constants/snapshot`` endpoint that re-uses the same
``.to_dict()`` + ``json.dumps`` serialisation pattern so the measurement here
and the production endpoint stay byte-aligned.

Payload filter is intentionally aligned with
``RegulatoryRegistry.version_hash(today)`` — both call ``is_active(today)`` —
so the measured payload bytes correspond exactly to the snapshot version_hash
the future endpoint will publish (no semantic drift).
"""
from __future__ import annotations

import argparse
import gzip
import json
import sys
from datetime import date
from pathlib import Path
from typing import Optional, Sequence

# tools/measurement/<this>.py → parents[2] = repo root
_REPO_ROOT = Path(__file__).resolve().parents[2]
# Allow `from app.services...` resolution without invoking via FastAPI.
sys.path.insert(0, str(_REPO_ROOT / "services" / "backend"))

from app.services.regulatory.registry import RegulatoryRegistry  # noqa: E402


_THRESHOLD_BYTES = 102_400  # 100 KB exact per CONTEXT.md D-14


def _build_payload(today: date) -> dict:
    """Build the active-snapshot payload matching the future Plan 03 endpoint shape."""
    registry = RegulatoryRegistry.instance()
    # get_all() returns active + historical ; filter to active so we measure
    # what mobile would actually bake (D-08 + D-14 doctrine).
    all_params = registry.get_all()
    active = [p for p in all_params if p.is_active(today)]
    return {
        "active_version_hash": registry.version_hash(today),
        "effective_on": today.isoformat(),
        "param_count": len(active),
        "parameters": [p.to_dict() for p in active],
    }


def _measure(payload: dict) -> dict:
    """Serialise + gzip + compute verdict. Returns a JSON-serialisable result dict."""
    raw_json = json.dumps(
        payload, separators=(",", ":"), sort_keys=True, ensure_ascii=False
    )
    raw_utf8 = raw_json.encode("utf-8")
    raw_bytes = len(raw_utf8)
    gzip_bytes = len(gzip.compress(raw_utf8, compresslevel=9))
    cantons_covered = sorted({p["jurisdiction"] for p in payload["parameters"]})
    verdict = (
        "PASS"
        if gzip_bytes < _THRESHOLD_BYTES
        else "FAIL — D-14 re-litigation trigger fired, switch to lazy per-canton fetch"
    )
    return {
        "active_version_hash": payload["active_version_hash"],
        "effective_on": payload["effective_on"],
        "param_count": payload["param_count"],
        "cantons_covered": cantons_covered,
        "raw_bytes": raw_bytes,
        "gzip_bytes": gzip_bytes,
        "threshold_bytes": _THRESHOLD_BYTES,
        "verdict": verdict,
    }


def _write_markdown_report(result: dict, report_path: Path) -> None:
    """Emit the markdown report committed to the phase directory."""
    cantons = ", ".join(result["cantons_covered"])
    pass_or_fail_line = (
        f"**Verdict : {result['verdict']}**"
        if result["verdict"] == "PASS"
        else f"**Verdict : FAIL**\n\n{result['verdict']}"
    )
    body = f"""# D-14 Bundle-size measurement report

> Phase `mint-data-architecture-v1-01-calc-engine-canonical` Plan 01 Task 1.
> Generated by `tools/measurement/regulatory_snapshot_bundle_size.py`.
> Cited by Plan 02 doctrine as the data anchor for D-14.

## Methodology

`RegulatoryRegistry.instance().get_all()` filtered to `is_active(today)` →
`[p.to_dict() for p in active]` →
`json.dumps(separators=(',', ':'), sort_keys=True, ensure_ascii=False)` →
`gzip.compress(payload_utf8, compresslevel=9)` → byte count.

The payload shape mirrors the planned `/v1/regulatory/constants/snapshot`
endpoint contract (Plan 03) so this measurement and the production endpoint
stay byte-aligned ; both use the same `is_active(today)` filter as
`RegulatoryRegistry.version_hash(today)`.

## Results

| Field                | Value |
| -------------------- | ----- |
| effective_on         | `{result['effective_on']}` |
| active_version_hash  | `{result['active_version_hash']}` |
| param_count          | {result['param_count']} |
| cantons_covered      | {len(result['cantons_covered'])} ({cantons}) |
| raw_bytes (JSON)     | {result['raw_bytes']:,} |
| gzip_bytes           | {result['gzip_bytes']:,} |
| threshold_bytes      | {result['threshold_bytes']:,} (100 KB per D-14) |

## Verdict

{pass_or_fail_line}

`gzip_bytes` ({result['gzip_bytes']:,}) vs threshold ({result['threshold_bytes']:,}) → margin {result['threshold_bytes'] - result['gzip_bytes']:,} bytes ({(result['threshold_bytes'] - result['gzip_bytes']) / result['threshold_bytes'] * 100:.1f}% headroom).

## Re-litigation trigger

Per CONTEXT.md §Decisions D-14 :

> *If the compressed snapshot exceeds 100 KB, revisit and consider lazy per-canton fetch with a per-canton on-disk cache.*

If the verdict above is **FAIL**, Plan 02 (doctrine + ADR PR) MUST be revised
to swap D-14 for lazy per-canton fetch before that plan ships. The verdict
gate is mechanical : the measurement script exits 1 on FAIL.
"""
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(body, encoding="utf-8")


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "D-14 bundle-size validation — measure gzip-compressed bytes of the active "
            "RegulatoryRegistry snapshot against the 100 KB ceiling."
        )
    )
    parser.add_argument(
        "--ci",
        action="store_true",
        help="Emit machine-readable JSON to stdout (CI / lefthook mode).",
    )
    parser.add_argument(
        "--write-report",
        metavar="PATH",
        help="Also write a markdown report to PATH.",
    )
    args = parser.parse_args(argv)

    today = date.today()
    payload = _build_payload(today)
    result = _measure(payload)

    if args.write_report:
        _write_markdown_report(result, Path(args.write_report))

    if args.ci:
        sys.stdout.write(json.dumps(result, sort_keys=True))
        sys.stdout.write("\n")
    else:
        sys.stdout.write(
            f"raw_bytes       : {result['raw_bytes']:,}\n"
            f"gzip_bytes      : {result['gzip_bytes']:,}\n"
            f"threshold_bytes : {result['threshold_bytes']:,}\n"
            f"verdict         : {result['verdict']}\n"
            f"param_count     : {result['param_count']}\n"
            f"cantons_covered : {len(result['cantons_covered'])}\n"
        )

    return 0 if result["verdict"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
