// GATE-04: Route guard snapshot test.
//
// Generates a sorted text snapshot of (path, scope) pairs from app.dart
// and compares against a golden file. Any unreviewed change to route
// scoping will fail this test, forcing explicit developer review.
//
// First run: generate the golden file and commit it.
// Subsequent runs: fail if any route was added/removed/re-scoped
// without updating the golden file.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Extract all (path, scope) pairs from app.dart source.
List<MapEntry<String, String>> extractRouteScopes(String source) {
  final entries = <MapEntry<String, String>>[];

  // Match routes with explicit scope
  final scopedPattern = RegExp(
    r'''ScopedGoRoute\s*\(\s*(?:\n\s*)?path:\s*['"]([^'"]+)['"]'''
    r'''\s*,\s*(?:\n\s*)?scope:\s*RouteScope\.(\w+)''',
  );
  final explicitPaths = <String>{};
  for (final match in scopedPattern.allMatches(source)) {
    final path = match.group(1)!;
    final scope = match.group(2)!;
    entries.add(MapEntry(path, scope));
    explicitPaths.add(path);
  }

  // Match all ScopedGoRoute paths (including those without explicit scope)
  final allPathPattern = RegExp(
    r'''ScopedGoRoute\s*\(\s*(?:\n\s*)?path:\s*['"]([^'"]+)['"]''',
  );
  for (final match in allPathPattern.allMatches(source)) {
    final path = match.group(1)!;
    if (!explicitPaths.contains(path)) {
      entries.add(MapEntry(path, 'authenticated'));
      explicitPaths.add(path);
    }
  }

  // Also find inline scope declarations (e.g. `ScopedGoRoute(path: '/x', scope: RouteScope.y,`)
  // that are on one line
  final inlinePattern = RegExp(
    r'''ScopedGoRoute\s*\(\s*path:\s*['"]([^'"]+)['"]\s*,\s*scope:\s*RouteScope\.(\w+)''',
  );
  for (final match in inlinePattern.allMatches(source)) {
    final path = match.group(1)!;
    final scope = match.group(2)!;
    // Update if already exists with default scope
    final idx = entries.indexWhere((e) => e.key == path);
    if (idx != -1 && entries[idx].value == 'authenticated' && scope != 'authenticated') {
      entries[idx] = MapEntry(path, scope);
    }
  }

  // Handle nested child routes (e.g., under /profile)
  final nestedPattern = RegExp(
    r'''ScopedGoRoute\s*\(\s*(?:\n\s*)?path:\s*['"]([^'"]+)['"].*?routes:\s*\[([\s\S]*?)\]\s*,?\s*\)''',
    dotAll: true,
  );
  for (final match in nestedPattern.allMatches(source)) {
    final parentPath = match.group(1)!;
    final childBlock = match.group(2)!;

    final childPathPattern = RegExp(
      r'''ScopedGoRoute\s*\(\s*(?:\n\s*)?path:\s*['"]([^'"]+)['"]''',
    );
    for (final childMatch in childPathPattern.allMatches(childBlock)) {
      final childRelPath = childMatch.group(1)!;
      final childFullPath = childRelPath.startsWith('/')
          ? childRelPath
          : '$parentPath/$childRelPath';

      if (!explicitPaths.contains(childFullPath)) {
        // Inherit parent scope by default
        final parentEntry = entries.firstWhere(
          (e) => e.key == parentPath,
          orElse: () => const MapEntry('', 'authenticated'),
        );
        entries.add(MapEntry(childFullPath, parentEntry.value));
        explicitPaths.add(childFullPath);
      }
    }
  }

  // Sort by path for deterministic output
  entries.sort((a, b) => a.key.compareTo(b.key));

  return entries;
}

/// Format route scopes as a human-readable snapshot.
String formatSnapshot(List<MapEntry<String, String>> entries) {
  final lines = <String>[
    '# Route Guard Snapshot',
    '# Generated by GATE-04 (route_guard_snapshot_test.dart)',
    '# Any change to this file requires explicit review.',
    '#',
    '# Format: PATH | SCOPE',
    '#',
  ];

  for (final entry in entries) {
    lines.add('${entry.key} | ${entry.value}');
  }

  lines.add(''); // trailing newline
  return lines.join('\n');
}

void main() {
  late String appSource;
  late List<MapEntry<String, String>> routeScopes;
  late String snapshot;

  setUpAll(() {
    final appFile = File('lib/app.dart');
    expect(appFile.existsSync(), isTrue);
    appSource = appFile.readAsStringSync();
    routeScopes = extractRouteScopes(appSource);
    snapshot = formatSnapshot(routeScopes);
  });

  group('GATE-04: Route guard snapshot', () {
    test('route scopes match golden file', () {
      final goldenFile =
          File('test/architecture/route_guard_snapshot.golden.txt');

      if (!goldenFile.existsSync()) {
        // First run: create the golden file
        goldenFile.writeAsStringSync(snapshot);
        // ignore: avoid_print
        print('GATE-04: Golden file created at '
            'test/architecture/route_guard_snapshot.golden.txt\n'
            'Contains ${routeScopes.length} routes. '
            'Commit this file to establish the baseline.');
        // Don't fail on first run — the golden was just created
        return;
      }

      final golden = goldenFile.readAsStringSync();

      if (golden != snapshot) {
        // Find differences for helpful output
        final goldenLines = golden.split('\n');
        final snapshotLines = snapshot.split('\n');

        final added = <String>[];
        final removed = <String>[];

        final goldenRoutes = goldenLines
            .where((l) => !l.startsWith('#') && l.contains('|'))
            .toSet();
        final currentRoutes = snapshotLines
            .where((l) => !l.startsWith('#') && l.contains('|'))
            .toSet();

        for (final r in currentRoutes) {
          if (!goldenRoutes.contains(r)) added.add('+ $r');
        }
        for (final r in goldenRoutes) {
          if (!currentRoutes.contains(r)) removed.add('- $r');
        }

        final diff = [...removed, ...added].join('\n');
        fail(
          'Route guard snapshot has changed. '
          'If this is intentional, update the golden file:\n'
          '  cp test/architecture/route_guard_snapshot.golden.txt.new '
          'test/architecture/route_guard_snapshot.golden.txt\n\n'
          'Diff:\n$diff\n\n'
          'To auto-update, run: flutter test '
          'test/architecture/route_guard_snapshot_test.dart '
          '--update-goldens',
        );
      }
    });

    test('snapshot contains expected number of routes', () {
      // Sanity check: the app should have a substantial number of routes
      expect(routeScopes.length, greaterThan(80),
          reason: 'Expected 80+ routes in the app');
    });

    test('all public routes are explicitly marked', () {
      final publicRoutes =
          routeScopes.where((e) => e.value == 'public').toList();

      // Known public routes that MUST exist
      final requiredPublic = ['/', '/auth/login', '/auth/register', '/about'];
      for (final path in requiredPublic) {
        expect(
          publicRoutes.any((r) => r.key == path),
          isTrue,
          reason: '$path must be marked as public',
        );
      }
    });

    test('onboarding routes are explicitly marked', () {
      final onboardingRoutes =
          routeScopes.where((e) => e.value == 'onboarding').toList();

      expect(
        onboardingRoutes.any((r) => r.key == '/onboarding/intent'),
        isTrue,
        reason: '/onboarding/intent must be marked as onboarding',
      );
    });
  });
}
