import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:mint_mobile/services/coach_narrative_service.dart';
import 'package:mint_mobile/services/dashboard_curator_service.dart';
import 'package:mint_mobile/theme/colors.dart';
import 'package:mint_mobile/utils/chf_formatter.dart';

/// Coach briefing card (P3).
///
/// Displays the coach's personalized greeting, score summary, top tip,
/// and confidence chip. This is the first thing the user sees on the
/// retirement dashboard — it makes the coach "speak".
///
/// Consumes [CoachNarrative] from CoachNarrativeService and
/// [CuratedCard] from DashboardCuratorService.
class CoachBriefingCard extends StatelessWidget {
  /// The generated narrative (greeting, scoreSummary, tip, etc.).
  final CoachNarrative? narrative;

  /// The top curated card (coaching tip or reengagement message).
  final CuratedCard? topCard;

  /// Current confidence score (0-100).
  final double confidenceScore;

  /// Whether narrative was generated by LLM (shows "Coach IA" badge).
  final bool isLlmGenerated;

  /// Callback when user taps "Enrichir" chip.
  final VoidCallback? onEnrich;

  const CoachBriefingCard({
    super.key,
    required this.narrative,
    this.topCard,
    required this.confidenceScore,
    this.isLlmGenerated = false,
    this.onEnrich,
  });

  @override
  Widget build(BuildContext context) {
    final narr = narrative;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: MintColors.coachBubble, // subtle blue, clearly visible
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: MintColors.blueClassic.withValues(alpha: 0.20), // blue accent
          width: 1.5,
        ),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Header: Greeting + badge ────────────────────
          Row(
            children: [
              Expanded(
                child: Text(
                  narr?.greeting ?? 'Bonjour',
                  style: GoogleFonts.montserrat(
                    fontSize: 19,
                    fontWeight: FontWeight.w700,
                    color: MintColors.textPrimary,
                  ),
                ),
              ),
              _buildBadge(),
            ],
          ),

          // ── Score summary ──────────────────────────────
          if (narr?.scoreSummary != null &&
              narr!.scoreSummary.isNotEmpty) ...[
            const SizedBox(height: 8),
            Text(
              narr.scoreSummary,
              style: GoogleFonts.inter(
                fontSize: 14,
                color: MintColors.textPrimary,
                height: 1.5,
              ),
            ),
          ],

          // ── Retirement countdown (45+ and not yet retired) ──
          if (narr?.retirementCountdown != null &&
              !narr!.retirementCountdown!.contains('0 mois')) ...[
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.symmetric(
                  horizontal: 10, vertical: 6),
              decoration: BoxDecoration(
                color: MintColors.primary.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Icon(Icons.timer_outlined,
                      size: 14, color: MintColors.primary),
                  const SizedBox(width: 6),
                  Flexible(
                    child: Text(
                      narr.retirementCountdown!,
                      style: GoogleFonts.inter(
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                        color: MintColors.primary,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],

          // ── Monthly comparison (Coach Vivant N vs N-1) ──
          if (narrative?.monthlyComparison != null &&
              narrative!.monthlyComparison!.isNotEmpty) ...[
            const SizedBox(height: 10),
            _buildMonthlyComparison(),
          ],

          // ── Top tip / urgent alert ─────────────────────
          if (_hasTopContent) ...[
            const SizedBox(height: 12),
            _buildTopContent(),
          ],

          // ── Confidence chip ────────────────────────────
          const SizedBox(height: 12),
          _buildConfidenceChip(),
        ],
      ),
    );
  }

  Widget _buildMonthlyComparison() {
    final trend = narrative!.versementsTrend ?? 'stable';
    final icon = switch (trend) {
      'en hausse' => Icons.trending_up,
      'en baisse' => Icons.trending_down,
      _ => Icons.trending_flat,
    };
    final color = switch (trend) {
      'en hausse' => MintColors.success,
      'en baisse' => MintColors.warning,
      _ => MintColors.textSecondary,
    };

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(10),
      ),
      child: Row(
        children: [
          Icon(icon, size: 16, color: color),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              narrative!.monthlyComparison!,
              style: GoogleFonts.inter(
                fontSize: 12,
                color: MintColors.textPrimary,
                height: 1.4,
              ),
              maxLines: 2,
              overflow: TextOverflow.ellipsis,
            ),
          ),
        ],
      ),
    );
  }

  bool get _hasTopContent =>
      narrative?.urgentAlert != null ||
      narrative?.topTipNarrative != null ||
      topCard != null;

  Widget _buildTopContent() {
    // Priority: urgent alert > top tip narrative > curated card
    if (narrative?.urgentAlert != null) {
      return _buildAlertRow(
        icon: Icons.warning_amber_rounded,
        color: MintColors.error,
        text: narrative!.urgentAlert!,
      );
    }

    if (narrative?.topTipNarrative != null) {
      return _buildAlertRow(
        icon: Icons.lightbulb_outline,
        color: MintColors.primary,
        text: narrative!.topTipNarrative!,
      );
    }

    if (topCard != null) {
      final card = topCard!;
      final color = switch (card.urgency) {
        AlertUrgency.urgent => MintColors.error,
        AlertUrgency.active => MintColors.warning,
        AlertUrgency.info => MintColors.primary,
      };
      final icon = switch (card.urgency) {
        AlertUrgency.urgent => Icons.warning_amber_rounded,
        AlertUrgency.active => Icons.trending_up,
        AlertUrgency.info => Icons.lightbulb_outline,
      };

      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _buildAlertRow(icon: icon, color: color, text: card.message),
          if (card.impactChf != null && card.impactChf! > 0) ...[
            const SizedBox(height: 6),
            Text(
              'Impact estim\u00e9\u00a0: CHF\u00a0${formatChf(card.impactChf!)}',
              style: GoogleFonts.inter(
                fontSize: 11,
                fontWeight: FontWeight.w600,
                color: MintColors.success,
              ),
            ),
          ],
        ],
      );
    }

    return const SizedBox.shrink();
  }

  Widget _buildAlertRow({
    required IconData icon,
    required Color color,
    required String text,
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          width: 28,
          height: 28,
          decoration: BoxDecoration(
            color: color.withValues(alpha: 0.12),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Icon(icon, size: 14, color: color),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: Text(
            text,
            style: GoogleFonts.inter(
              fontSize: 12,
              color: MintColors.textPrimary,
              height: 1.5,
            ),
            maxLines: 3,
            overflow: TextOverflow.ellipsis,
          ),
        ),
      ],
    );
  }

  Widget _buildBadge() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(
        color: isLlmGenerated
            ? MintColors.primary.withValues(alpha: 0.12)
            : MintColors.textMuted.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Text(
        isLlmGenerated ? 'Coach IA' : 'Coach',
        style: GoogleFonts.inter(
          fontSize: 10,
          fontWeight: FontWeight.w600,
          color: isLlmGenerated ? MintColors.primary : MintColors.textMuted,
        ),
      ),
    );
  }

  Widget _buildConfidenceChip() {
    final isLow = confidenceScore < 70;

    return GestureDetector(
      onTap: isLow ? onEnrich : null,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
        decoration: BoxDecoration(
          color: isLow
              ? MintColors.warning.withValues(alpha: 0.10)
              : MintColors.success.withValues(alpha: 0.10),
          borderRadius: BorderRadius.circular(8),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              isLow ? Icons.tune : Icons.check_circle_outline,
              size: 14,
              color: isLow ? MintColors.warning : MintColors.success,
            ),
            const SizedBox(width: 6),
            Text(
              isLow
                  ? 'Confiance ${confidenceScore.toStringAsFixed(0)}% — Enrichir'
                  : 'Confiance ${confidenceScore.toStringAsFixed(0)}%',
              style: GoogleFonts.inter(
                fontSize: 11,
                fontWeight: FontWeight.w600,
                color: isLow ? MintColors.warning : MintColors.success,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
