import 'package:mint_mobile/models/coach_profile.dart';
import 'package:mint_mobile/services/financial_plan_ledger_inputs.dart'
    as ledger_inputs;

// ────────────────────────────────────────────────────────────────────────────
//  FinancialPlan model
//
//  Stores a persisted financial plan generated by the MINT coach.
//  Includes milestones, projected outcomes, and a deterministic profile hash
//  for staleness detection.
//
//  Compliance: educational tool only — not financial advice (LSFin).
//  See: LIFD art. 38, LPP art. 14.
// ────────────────────────────────────────────────────────────────────────────

/// A single quarterly milestone within a financial plan.
class PlanMilestone {
  /// When this milestone target date falls.
  final DateTime targetDate;

  /// Amount that should be reached at this milestone.
  final double targetAmount;

  /// Human-readable description including percentage.
  final String description;

  const PlanMilestone({
    required this.targetDate,
    required this.targetAmount,
    required this.description,
  });

  Map<String, dynamic> toJson() => {
        'targetDate': targetDate.toIso8601String(),
        'targetAmount': targetAmount,
        'description': description,
      };

  factory PlanMilestone.fromJson(Map<String, dynamic> json) {
    return PlanMilestone(
      targetDate: DateTime.parse(json['targetDate'] as String),
      targetAmount: (json['targetAmount'] as num?)?.toDouble() ?? 0.0,
      description: json['description'] as String? ?? '',
    );
  }
}

/// Salary basis used by a retirement projection.
///
/// This is persisted as structured data so UI surfaces can distinguish a
/// current pension-fund fact from the visible monthly-salary × 12 fallback.
class FinancialPlanSalaryBasis {
  final String kind;
  final double? annualChf;

  const FinancialPlanSalaryBasis({
    required this.kind,
    this.annualChf,
  });

  Map<String, dynamic> toJson() => {
        'kind': kind,
        if (annualChf != null) 'annualChf': annualChf,
      };

  factory FinancialPlanSalaryBasis.fromJson(Map<String, dynamic> json) {
    return FinancialPlanSalaryBasis(
      kind: json['kind'] as String? ?? 'notApplicable',
      annualChf: (json['annualChf'] as num?)?.toDouble(),
    );
  }
}

/// Bonification basis used by a retirement projection.
class FinancialPlanBonificationBasis {
  final String kind;
  final double? annualRate;

  const FinancialPlanBonificationBasis({
    required this.kind,
    this.annualRate,
  });

  Map<String, dynamic> toJson() => {
        'kind': kind,
        if (annualRate != null) 'annualRate': annualRate,
      };

  factory FinancialPlanBonificationBasis.fromJson(
    Map<String, dynamic> json,
  ) {
    return FinancialPlanBonificationBasis(
      kind: json['kind'] as String? ?? 'notApplicable',
      annualRate: (json['annualRate'] as num?)?.toDouble(),
    );
  }
}

/// Explicit, replayable assumptions behind one retirement scenario.
class FinancialPlanProjectionAssumptions {
  final double? caisseReturnBase;
  final double? caisseReturnLow;
  final double? caisseReturnHigh;
  final double supplementalMonthlySavingsReturn;
  final FinancialPlanSalaryBasis salaryBasis;
  final FinancialPlanBonificationBasis bonificationBasis;
  final DateTime projectionAsOf;

  const FinancialPlanProjectionAssumptions({
    required this.caisseReturnBase,
    required this.caisseReturnLow,
    required this.caisseReturnHigh,
    required this.supplementalMonthlySavingsReturn,
    required this.salaryBasis,
    required this.bonificationBasis,
    required this.projectionAsOf,
  });

  Map<String, dynamic> toJson() => {
        if (caisseReturnBase != null) 'caisseReturnBase': caisseReturnBase,
        if (caisseReturnLow != null) 'caisseReturnLow': caisseReturnLow,
        if (caisseReturnHigh != null) 'caisseReturnHigh': caisseReturnHigh,
        'supplementalMonthlySavingsReturn': supplementalMonthlySavingsReturn,
        'salaryBasis': salaryBasis.toJson(),
        'bonificationBasis': bonificationBasis.toJson(),
        'projectionAsOf': projectionAsOf.toUtc().toIso8601String(),
      };

  factory FinancialPlanProjectionAssumptions.fromJson(
    Map<String, dynamic> json,
  ) {
    final salaryJson = json['salaryBasis'];
    final bonificationJson = json['bonificationBasis'];
    return FinancialPlanProjectionAssumptions(
      caisseReturnBase: (json['caisseReturnBase'] as num?)?.toDouble(),
      caisseReturnLow: (json['caisseReturnLow'] as num?)?.toDouble(),
      caisseReturnHigh: (json['caisseReturnHigh'] as num?)?.toDouble(),
      supplementalMonthlySavingsReturn:
          (json['supplementalMonthlySavingsReturn'] as num?)?.toDouble() ?? 0,
      salaryBasis: FinancialPlanSalaryBasis.fromJson(
        salaryJson is Map<String, dynamic>
            ? salaryJson
            : const <String, dynamic>{},
      ),
      bonificationBasis: FinancialPlanBonificationBasis.fromJson(
        bonificationJson is Map<String, dynamic>
            ? bonificationJson
            : const <String, dynamic>{},
      ),
      projectionAsOf: DateTime.tryParse(
            json['projectionAsOf'] as String? ?? '',
          ) ??
          DateTime.fromMillisecondsSinceEpoch(0, isUtc: true),
    );
  }
}

/// A persisted financial plan generated by the MINT coach.
///
/// Contains projected outcomes, milestones at 25/50/75/100% of goal,
/// and a deterministic profile hash to detect staleness when the user's
/// financial profile changes.
///
/// Threat T-04-01: monthlyTarget is clamped to [0, 1e7] in fromJson.
/// Threat T-04-03: Caller (FinancialPlanService) handles JSON parse errors.
class FinancialPlan {
  /// Unique identifier (UUID string).
  final String id;

  /// User-readable goal description (e.g. "Acheter un appartement à Genève").
  /// Must not contain verbatim PII.
  final String goalDescription;

  /// Category matching GoalTemplate.id values.
  final String goalCategory;

  /// Monthly savings target (clamped to [0, 1e7]).
  final double monthlyTarget;

  /// Quarterly progress milestones (4 items at 25/50/75/100%).
  final List<PlanMilestone> milestones;

  /// Central projected outcome amount in CHF.
  final double projectedOutcome;

  /// Lower-bound projection (pessimistic scenario). Null if not computed.
  final double? projectedLow;

  /// Upper-bound projection (optimistic scenario). Null if not computed.
  final double? projectedHigh;

  /// Target date for reaching the goal.
  final DateTime targetDate;

  /// When this plan was generated.
  final DateTime generatedAt;

  /// Deterministic hash of the CoachProfile at generation time.
  /// Used to detect when the plan is stale.
  final String profileHashAtGeneration;

  /// Coach narrative text (LLM-generated, compliance-filtered).
  final String coachNarrative;

  /// Confidence level 0-100 as per EnhancedConfidence 4-axis model.
  final double confidenceLevel;

  /// Legal source references included in the plan.
  final List<String> sources;

  /// Educational disclaimer (LSFin compliant).
  final String disclaimer;

  /// Explicit amount confirmed for this immutable scenario.
  ///
  /// Null means a legacy record could not be migrated safely and therefore
  /// cannot be regenerated.
  final double? goalAmount;

  /// Stable identity of the confirmed scenario, independent from GoalA.
  final String? scenarioId;

  /// Final user-confirmation time for this scenario.
  final DateTime? confirmedAt;

  /// Time at which the ledger snapshot was captured.
  final DateTime? inputAsOf;

  /// Structured retirement assumptions. Null for simple deadline arithmetic
  /// and unmigrated legacy records.
  final FinancialPlanProjectionAssumptions? projectionAssumptions;

  const FinancialPlan({
    required this.id,
    required this.goalDescription,
    required this.goalCategory,
    required this.monthlyTarget,
    required this.milestones,
    required this.projectedOutcome,
    this.projectedLow,
    this.projectedHigh,
    required this.targetDate,
    required this.generatedAt,
    required this.profileHashAtGeneration,
    required this.coachNarrative,
    required this.confidenceLevel,
    required this.sources,
    required this.disclaimer,
    this.goalAmount,
    this.scenarioId,
    this.confirmedAt,
    this.inputAsOf,
    this.projectionAssumptions,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'goalDescription': goalDescription,
        'goalCategory': goalCategory,
        'monthlyTarget': monthlyTarget,
        'milestones': milestones.map((m) => m.toJson()).toList(),
        'projectedOutcome': projectedOutcome,
        if (projectedLow != null) 'projectedLow': projectedLow,
        if (projectedHigh != null) 'projectedHigh': projectedHigh,
        'targetDate': targetDate.toIso8601String(),
        'generatedAt': generatedAt.toIso8601String(),
        'profileHashAtGeneration': profileHashAtGeneration,
        'coachNarrative': coachNarrative,
        'confidenceLevel': confidenceLevel,
        'sources': sources,
        'disclaimer': disclaimer,
        if (goalAmount != null) 'goalAmount': goalAmount,
        if (scenarioId != null) 'scenarioId': scenarioId,
        if (confirmedAt != null)
          'confirmedAt': confirmedAt!.toUtc().toIso8601String(),
        if (inputAsOf != null)
          'inputAsOf': inputAsOf!.toUtc().toIso8601String(),
        if (projectionAssumptions != null)
          'projectionAssumptions': projectionAssumptions!.toJson(),
      };

  /// Deserialize with defensive parsing.
  ///
  /// Threat T-04-01: monthlyTarget clamped to [0, 1e7].
  /// All numeric fields use safe cast: `(json['field'] as num?)?.toDouble() ?? 0`.
  factory FinancialPlan.fromJson(Map<String, dynamic> json) {
    final rawMonthly = (json['monthlyTarget'] as num?)?.toDouble() ?? 0.0;
    final clampedMonthly = rawMonthly.clamp(0.0, 1e7);

    final rawMilestones = json['milestones'] as List<dynamic>? ?? [];
    final milestones = <PlanMilestone>[];
    for (final raw in rawMilestones) {
      if (raw is! Map<String, dynamic>) continue;
      try {
        milestones.add(PlanMilestone.fromJson(raw));
      } on FormatException {
        // Malformed legacy milestones are not scenario ownership evidence.
      } on TypeError {
        // Keep the record readable but unregeneratable.
      }
    }

    final rawSources = json['sources'] as List<dynamic>? ?? [];
    final sources = rawSources.map((e) => e as String).toList();

    final hasExplicitGoalAmount = json.containsKey('goalAmount');
    final rawGoalAmount = json['goalAmount'];
    final explicitGoalAmount =
        rawGoalAmount is num ? rawGoalAmount.toDouble() : null;
    final goalAmount = _validGoalAmount(explicitGoalAmount)
        ? explicitGoalAmount
        : hasExplicitGoalAmount
            ? null
            : _recoverUniqueLegacyGoalAmount(milestones);
    final assumptionsJson = json['projectionAssumptions'];

    return FinancialPlan(
      id: json['id'] as String? ?? '',
      goalDescription: json['goalDescription'] as String? ?? '',
      goalCategory: json['goalCategory'] as String? ?? '',
      monthlyTarget: clampedMonthly,
      milestones: milestones,
      projectedOutcome: (json['projectedOutcome'] as num?)?.toDouble() ?? 0.0,
      projectedLow: (json['projectedLow'] as num?)?.toDouble(),
      projectedHigh: (json['projectedHigh'] as num?)?.toDouble(),
      targetDate: DateTime.parse(json['targetDate'] as String),
      generatedAt: DateTime.parse(json['generatedAt'] as String),
      profileHashAtGeneration: json['profileHashAtGeneration'] as String? ?? '',
      coachNarrative: json['coachNarrative'] as String? ?? '',
      confidenceLevel: (json['confidenceLevel'] as num?)?.toDouble() ?? 0.0,
      sources: sources,
      disclaimer: json['disclaimer'] as String? ?? '',
      goalAmount: goalAmount,
      scenarioId: json['scenarioId'] as String?,
      confirmedAt: _tryParseInstant(json['confirmedAt']),
      inputAsOf: _tryParseInstant(json['inputAsOf']),
      projectionAssumptions: assumptionsJson is Map<String, dynamic>
          ? FinancialPlanProjectionAssumptions.fromJson(assumptionsJson)
          : null,
    );
  }

  /// Generates 4 milestones at 25/50/75/100% of [goalAmount].
  ///
  /// Milestone dates are evenly spaced between now and [targetDate].
  static List<PlanMilestone> generateMilestones(
    double goalAmount,
    DateTime targetDate, {
    DateTime? now,
  }) {
    final generatedAt = now ?? DateTime.now();
    final totalMs =
        targetDate.millisecondsSinceEpoch - generatedAt.millisecondsSinceEpoch;
    const percentages = [25, 50, 75, 100];

    return List.generate(4, (i) {
      final pct = percentages[i];
      final dateMs =
          generatedAt.millisecondsSinceEpoch + (totalMs * (i + 1) ~/ 4);
      final date = DateTime.fromMillisecondsSinceEpoch(dateMs);
      final amount = goalAmount * pct / 100;
      return PlanMilestone(
        targetDate: date,
        targetAmount: amount,
        description: '$pct% atteint — ${amount.toStringAsFixed(0)} CHF',
      );
    });
  }

  /// Returns a copy of this plan with the given fields overridden.
  FinancialPlan copyWith({
    String? id,
    String? goalDescription,
    String? goalCategory,
    double? monthlyTarget,
    List<PlanMilestone>? milestones,
    double? projectedOutcome,
    double? projectedLow,
    double? projectedHigh,
    DateTime? targetDate,
    DateTime? generatedAt,
    String? profileHashAtGeneration,
    String? coachNarrative,
    double? confidenceLevel,
    List<String>? sources,
    String? disclaimer,
    double? goalAmount,
    String? scenarioId,
    DateTime? confirmedAt,
    DateTime? inputAsOf,
    FinancialPlanProjectionAssumptions? projectionAssumptions,
  }) {
    return FinancialPlan(
      id: id ?? this.id,
      goalDescription: goalDescription ?? this.goalDescription,
      goalCategory: goalCategory ?? this.goalCategory,
      monthlyTarget: monthlyTarget ?? this.monthlyTarget,
      milestones: milestones ?? this.milestones,
      projectedOutcome: projectedOutcome ?? this.projectedOutcome,
      projectedLow: projectedLow ?? this.projectedLow,
      projectedHigh: projectedHigh ?? this.projectedHigh,
      targetDate: targetDate ?? this.targetDate,
      generatedAt: generatedAt ?? this.generatedAt,
      profileHashAtGeneration:
          profileHashAtGeneration ?? this.profileHashAtGeneration,
      coachNarrative: coachNarrative ?? this.coachNarrative,
      confidenceLevel: confidenceLevel ?? this.confidenceLevel,
      sources: sources ?? this.sources,
      disclaimer: disclaimer ?? this.disclaimer,
      goalAmount: goalAmount ?? this.goalAmount,
      scenarioId: scenarioId ?? this.scenarioId,
      confirmedAt: confirmedAt ?? this.confirmedAt,
      inputAsOf: inputAsOf ?? this.inputAsOf,
      projectionAssumptions:
          projectionAssumptions ?? this.projectionAssumptions,
    );
  }
}

bool _validGoalAmount(double? value) =>
    value != null && value.isFinite && value > 0;

double? _recoverUniqueLegacyGoalAmount(List<PlanMilestone> milestones) {
  final candidates = milestones
      .where(
        (milestone) =>
            _validGoalAmount(milestone.targetAmount) &&
            RegExp(r'^\s*100\s*%').hasMatch(milestone.description),
      )
      .map((milestone) => milestone.targetAmount)
      .toList();
  return candidates.length == 1 ? candidates.single : null;
}

DateTime? _tryParseInstant(Object? value) =>
    value is String ? DateTime.tryParse(value) : null;

/// Backward-compatible model export for callers that have not yet moved to the
/// ledger snapshot module.
String computeProfileHash(CoachProfile profile, {DateTime? now}) =>
    ledger_inputs.computeProfileHash(profile, now: now);
