import 'dart:convert';

import 'package:crypto/crypto.dart';
import 'package:mint_mobile/models/coach_profile.dart';

// ────────────────────────────────────────────────────────────────────────────
//  FinancialPlan model
//
//  Stores a persisted financial plan generated by the MINT coach.
//  Includes milestones, projected outcomes, and a deterministic profile hash
//  for staleness detection.
//
//  Compliance: educational tool only — not financial advice (LSFin).
//  See: LIFD art. 38, LPP art. 14.
// ────────────────────────────────────────────────────────────────────────────

/// A single quarterly milestone within a financial plan.
class PlanMilestone {
  /// When this milestone target date falls.
  final DateTime targetDate;

  /// Amount that should be reached at this milestone.
  final double targetAmount;

  /// Human-readable description including percentage.
  final String description;

  const PlanMilestone({
    required this.targetDate,
    required this.targetAmount,
    required this.description,
  });

  Map<String, dynamic> toJson() => {
        'targetDate': targetDate.toIso8601String(),
        'targetAmount': targetAmount,
        'description': description,
      };

  factory PlanMilestone.fromJson(Map<String, dynamic> json) {
    return PlanMilestone(
      targetDate: DateTime.parse(json['targetDate'] as String),
      targetAmount: (json['targetAmount'] as num?)?.toDouble() ?? 0.0,
      description: json['description'] as String? ?? '',
    );
  }
}

/// A persisted financial plan generated by the MINT coach.
///
/// Contains projected outcomes, milestones at 25/50/75/100% of goal,
/// and a deterministic profile hash to detect staleness when the user's
/// financial profile changes.
///
/// Threat T-04-01: monthlyTarget is clamped to [0, 1e7] in fromJson.
/// Threat T-04-03: Caller (FinancialPlanService) handles JSON parse errors.
class FinancialPlan {
  /// Unique identifier (UUID string).
  final String id;

  /// User-readable goal description (e.g. "Acheter un appartement à Genève").
  /// Must not contain verbatim PII.
  final String goalDescription;

  /// Category matching GoalTemplate.id values.
  final String goalCategory;

  /// Monthly savings target (clamped to [0, 1e7]).
  final double monthlyTarget;

  /// Quarterly progress milestones (4 items at 25/50/75/100%).
  final List<PlanMilestone> milestones;

  /// Central projected outcome amount in CHF.
  final double projectedOutcome;

  /// Lower-bound projection (pessimistic scenario). Null if not computed.
  final double? projectedLow;

  /// Upper-bound projection (optimistic scenario). Null if not computed.
  final double? projectedHigh;

  /// Target date for reaching the goal.
  final DateTime targetDate;

  /// When this plan was generated.
  final DateTime generatedAt;

  /// Deterministic hash of the CoachProfile at generation time.
  /// Used to detect when the plan is stale.
  final String profileHashAtGeneration;

  /// Coach narrative text (LLM-generated, compliance-filtered).
  final String coachNarrative;

  /// Confidence level 0-100 as per EnhancedConfidence 4-axis model.
  final double confidenceLevel;

  /// Legal source references included in the plan.
  final List<String> sources;

  /// Educational disclaimer (LSFin compliant).
  final String disclaimer;

  const FinancialPlan({
    required this.id,
    required this.goalDescription,
    required this.goalCategory,
    required this.monthlyTarget,
    required this.milestones,
    required this.projectedOutcome,
    this.projectedLow,
    this.projectedHigh,
    required this.targetDate,
    required this.generatedAt,
    required this.profileHashAtGeneration,
    required this.coachNarrative,
    required this.confidenceLevel,
    required this.sources,
    required this.disclaimer,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'goalDescription': goalDescription,
        'goalCategory': goalCategory,
        'monthlyTarget': monthlyTarget,
        'milestones': milestones.map((m) => m.toJson()).toList(),
        'projectedOutcome': projectedOutcome,
        if (projectedLow != null) 'projectedLow': projectedLow,
        if (projectedHigh != null) 'projectedHigh': projectedHigh,
        'targetDate': targetDate.toIso8601String(),
        'generatedAt': generatedAt.toIso8601String(),
        'profileHashAtGeneration': profileHashAtGeneration,
        'coachNarrative': coachNarrative,
        'confidenceLevel': confidenceLevel,
        'sources': sources,
        'disclaimer': disclaimer,
      };

  /// Deserialize with defensive parsing.
  ///
  /// Threat T-04-01: monthlyTarget clamped to [0, 1e7].
  /// All numeric fields use safe cast: `(json['field'] as num?)?.toDouble() ?? 0`.
  factory FinancialPlan.fromJson(Map<String, dynamic> json) {
    final rawMonthly = (json['monthlyTarget'] as num?)?.toDouble() ?? 0.0;
    final clampedMonthly = rawMonthly.clamp(0.0, 1e7);

    final rawMilestones = json['milestones'] as List<dynamic>? ?? [];
    final milestones = rawMilestones
        .map((e) => PlanMilestone.fromJson(e as Map<String, dynamic>))
        .toList();

    final rawSources = json['sources'] as List<dynamic>? ?? [];
    final sources = rawSources.map((e) => e as String).toList();

    return FinancialPlan(
      id: json['id'] as String? ?? '',
      goalDescription: json['goalDescription'] as String? ?? '',
      goalCategory: json['goalCategory'] as String? ?? '',
      monthlyTarget: clampedMonthly,
      milestones: milestones,
      projectedOutcome: (json['projectedOutcome'] as num?)?.toDouble() ?? 0.0,
      projectedLow: (json['projectedLow'] as num?)?.toDouble(),
      projectedHigh: (json['projectedHigh'] as num?)?.toDouble(),
      targetDate: DateTime.parse(json['targetDate'] as String),
      generatedAt: DateTime.parse(json['generatedAt'] as String),
      profileHashAtGeneration: json['profileHashAtGeneration'] as String? ?? '',
      coachNarrative: json['coachNarrative'] as String? ?? '',
      confidenceLevel: (json['confidenceLevel'] as num?)?.toDouble() ?? 0.0,
      sources: sources,
      disclaimer: json['disclaimer'] as String? ?? '',
    );
  }

  /// Generates 4 milestones at 25/50/75/100% of [goalAmount].
  ///
  /// Milestone dates are evenly spaced between now and [targetDate].
  static List<PlanMilestone> generateMilestones(
    double goalAmount,
    DateTime targetDate,
  ) {
    final now = DateTime.now();
    final totalMs =
        targetDate.millisecondsSinceEpoch - now.millisecondsSinceEpoch;
    const percentages = [25, 50, 75, 100];

    return List.generate(4, (i) {
      final pct = percentages[i];
      final dateMs = now.millisecondsSinceEpoch + (totalMs * (i + 1) ~/ 4);
      final date = DateTime.fromMillisecondsSinceEpoch(dateMs);
      final amount = goalAmount * pct / 100;
      return PlanMilestone(
        targetDate: date,
        targetAmount: amount,
        description: '$pct% atteint — ${amount.toStringAsFixed(0)} CHF',
      );
    });
  }

  /// Returns a copy of this plan with the given fields overridden.
  FinancialPlan copyWith({
    String? id,
    String? goalDescription,
    String? goalCategory,
    double? monthlyTarget,
    List<PlanMilestone>? milestones,
    double? projectedOutcome,
    double? projectedLow,
    double? projectedHigh,
    DateTime? targetDate,
    DateTime? generatedAt,
    String? profileHashAtGeneration,
    String? coachNarrative,
    double? confidenceLevel,
    List<String>? sources,
    String? disclaimer,
  }) {
    return FinancialPlan(
      id: id ?? this.id,
      goalDescription: goalDescription ?? this.goalDescription,
      goalCategory: goalCategory ?? this.goalCategory,
      monthlyTarget: monthlyTarget ?? this.monthlyTarget,
      milestones: milestones ?? this.milestones,
      projectedOutcome: projectedOutcome ?? this.projectedOutcome,
      projectedLow: projectedLow ?? this.projectedLow,
      projectedHigh: projectedHigh ?? this.projectedHigh,
      targetDate: targetDate ?? this.targetDate,
      generatedAt: generatedAt ?? this.generatedAt,
      profileHashAtGeneration:
          profileHashAtGeneration ?? this.profileHashAtGeneration,
      coachNarrative: coachNarrative ?? this.coachNarrative,
      confidenceLevel: confidenceLevel ?? this.confidenceLevel,
      sources: sources ?? this.sources,
      disclaimer: disclaimer ?? this.disclaimer,
    );
  }
}

const _planInputFingerprintPrefix = 'mint-plan-input:v1:sha256:';

const _salaryPath = 'salaireBrutMensuel';
const _cantonPath = 'canton';
const _dateOfBirthPath = 'dateOfBirth';
const _birthYearPath = 'birthYear';
const _lppTotalPath = 'prevoyance.avoirLppTotal';
const _lppMandatoryPath = 'prevoyance.avoirLppObligatoire';
const _lppExtraMandatoryPath = 'prevoyance.avoirLppSurobligatoire';
const _lppReturnPath = 'prevoyance.rendementCaisse';
const _pillar3aPath = 'prevoyance.totalEpargne3a';
const _salaryMonthsPath = 'nombreDeMois';

/// Computes the versioned fingerprint of every ledger input that can change a
/// generated financial plan.
///
/// The fixed-order payload includes each fact's value and its field-centric
/// provenance. The effective-age union serializes `dateOfBirth` when known and
/// `birthYear` otherwise, never both. This wire format is intentionally
/// versioned so persisted hashes from older/incomplete algorithms fail closed.
String computeProfileHash(CoachProfile profile) {
  final effectiveAgePath =
      profile.dateOfBirth == null ? _birthYearPath : _dateOfBirthPath;
  final effectiveAgeValue = profile.dateOfBirth == null
      ? profile.birthYear
      : _businessDate(profile.dateOfBirth!);

  final facts = <Map<String, Object?>>[
    _fingerprintFact(profile, _salaryPath, profile.salaireBrutMensuel),
    _fingerprintFact(profile, _cantonPath, profile.canton),
    _fingerprintFact(
      profile,
      _lppTotalPath,
      profile.prevoyance.avoirLppTotal,
    ),
    _fingerprintFact(
      profile,
      _pillar3aPath,
      profile.prevoyance.totalEpargne3a,
    ),
    _fingerprintFact(profile, effectiveAgePath, effectiveAgeValue),
    _fingerprintFact(profile, _salaryMonthsPath, profile.nombreDeMois),
    _fingerprintFact(
      profile,
      _lppMandatoryPath,
      profile.prevoyance.avoirLppObligatoire,
    ),
    _fingerprintFact(
      profile,
      _lppExtraMandatoryPath,
      profile.prevoyance.avoirLppSurobligatoire,
    ),
    _fingerprintFact(
      profile,
      _lppReturnPath,
      profile.prevoyance.rendementCaisse,
    ),
  ];

  final payload = jsonEncode(<String, Object?>{
    'schema': 'mint-plan-input',
    'version': 1,
    'facts': facts,
  });
  return '$_planInputFingerprintPrefix${sha256.convert(utf8.encode(payload))}';
}

Map<String, Object?> _fingerprintFact(
  CoachProfile profile,
  String path,
  Object? rawValue,
) {
  return <String, Object?>{
    'path': path,
    'value': _canonicalFingerprintValue(rawValue, path),
    'source': _metadata(profile.dataSources, path)?.name,
    'updatedAt': _canonicalInstant(_metadata(profile.dataTimestamps, path)),
    'sourceDate': _canonicalSourceDate(
      _metadata<DateTime?>(profile.dataSourceDates, path),
    ),
  };
}

T? _metadata<T>(Map<String, T> metadata, String path) {
  if (metadata.containsKey(path)) return metadata[path];
  if (path == _dateOfBirthPath || path == _birthYearPath) {
    return metadata['age'];
  }
  return null;
}

Object? _canonicalFingerprintValue(Object? value, String path) {
  if (value is double) {
    if (!value.isFinite) {
      throw ArgumentError.value(value, path, 'finite plan input required');
    }
    return value == 0 ? 0.0 : value;
  }
  if (value is num && !value.isFinite) {
    throw ArgumentError.value(value, path, 'finite plan input required');
  }
  return value;
}

String _businessDate(DateTime value) {
  final year = value.year.toString().padLeft(4, '0');
  final month = value.month.toString().padLeft(2, '0');
  final day = value.day.toString().padLeft(2, '0');
  return '$year-$month-$day';
}

String? _canonicalSourceDate(DateTime? value) =>
    value == null ? null : _businessDate(value);

String? _canonicalInstant(DateTime? value) {
  if (value == null) return null;
  final utc = value.toUtc();
  final base = '${utc.year.toString().padLeft(4, '0')}-'
      '${utc.month.toString().padLeft(2, '0')}-'
      '${utc.day.toString().padLeft(2, '0')}T'
      '${utc.hour.toString().padLeft(2, '0')}:'
      '${utc.minute.toString().padLeft(2, '0')}:'
      '${utc.second.toString().padLeft(2, '0')}';
  final micros =
      (utc.millisecond * 1000 + utc.microsecond).toString().padLeft(6, '0');
  return '$base.${micros}Z';
}
