/// ReturnContract — standardized callback when user returns from a screen.
///
/// When a user navigates back from any orchestrated surface (B or C type),
/// the RoutePlanner receives this contract so the Coach can react accordingly.
///
/// See docs/CHAT_TO_SCREEN_ORCHESTRATION_STRATEGY.md §7
library;

// ════════════════════════════════════════════════════════════════
//  OUTCOME ENUM
// ════════════════════════════════════════════════════════════════

/// The outcome of a user's interaction with an orchestrated screen.
///
/// - [completed]: user finished the flow or simulation (all steps done).
/// - [abandoned]: user navigated away without completing.
/// - [changedInputs]: user modified profile fields / hypothesis values.
enum ScreenOutcome {
  /// User completed the surface — simulation run, flow acknowledged, etc.
  completed,

  /// User left the surface without completing. Coach may propose alternative.
  abandoned,

  /// User changed hypothesis inputs or profile fields mid-screen.
  /// Triggers profile update + confidence recalculation.
  changedInputs,
}

// ════════════════════════════════════════════════════════════════
//  RETURN CONTRACT
// ════════════════════════════════════════════════════════════════

/// Standardized return value from any orchestrated MINT surface.
///
/// Produced by the screen and consumed by [RoutePlanner] / CapMemory loop.
///
/// Rules:
/// - [route] MUST match the canonical GoRouter route string.
/// - [updatedFields] keys use the same dotted-path convention as
///   [CoachProfile.dataSources] (e.g. 'prevoyance.avoirLppTotal').
/// - [confidenceDelta] is a signed value in [-1.0, 1.0]. Positive means
///   the interaction raised data confidence (new certificate imported).
///   Negative means the user corrected assumptions downward.
/// - [nextCapSuggestion] is an optional CapEngine cap identifier string
///   (e.g. 'lpp_rachat', 'objectif_3a') that the Coach should surface next.
class ScreenReturn {
  /// The canonical GoRouter route of the screen that was navigated.
  /// Example: '/rente-vs-capital', '/divorce', '/budget'.
  final String route;

  /// How the user left the screen.
  final ScreenOutcome outcome;

  /// Profile fields that were updated during the session, if any.
  ///
  /// Keys follow the CoachProfile dotted-path convention.
  /// Example: {'prevoyance.avoirLppTotal': 70377.0, 'canton': 'VS'}
  final Map<String, dynamic>? updatedFields;

  /// Signed change in confidence score caused by this interaction.
  ///
  /// Range [-1.0, 1.0]. Null if no confidence change occurred.
  /// Positive: user provided validated data (e.g. scanned LPP certificate).
  /// Negative: user corrected an over-estimated assumption.
  final double? confidenceDelta;

  /// Identifier of the next CapEngine cap to suggest, if any.
  ///
  /// Set by the screen when it detects a natural follow-up action.
  /// Example: after completing '/3a-deep/staggered-withdrawal', suggest
  /// 'lpp_rachat' if rachat data is missing.
  final String? nextCapSuggestion;

  /// Structured outputs from this screen for guided sequence step transfer.
  ///
  /// Used by [SequenceCoordinator] to pre-fill the next step in a guided
  /// sequence. Keys are domain-specific (e.g. 'capacite_achat', 'montant_epl').
  /// Values must be JSON-serializable primitives (double, int, String, bool).
  ///
  /// Null when not in a guided sequence or screen doesn't produce outputs.
  /// See: docs/RFC_AGENT_LOOP_STATEFUL.md §3.4, §6.3
  final Map<String, dynamic>? stepOutputs;

  // ── SEQUENCE IDENTITY (Phase 2 Completion) ─────────────────────

  /// ID of the guided sequence run this return belongs to.
  ///
  /// Populated by Tier A screens that read `runId` from `GoRouter.extra`.
  /// Null for Tier B (legacy) screens or non-sequence navigation.
  /// Used by [SequenceChatHandler] for canonical routing and dedup.
  final String? runId;

  /// ID of the sequence step this return corresponds to.
  ///
  /// Populated by Tier A screens alongside [runId].
  /// Null for Tier B screens or non-sequence navigation.
  final String? stepId;

  /// Unique event identifier for idempotent processing.
  ///
  /// Generated by the emitting screen (UUID or timestamp-based).
  /// Used by [SequenceRun.processedEventIds] to prevent double
  /// consumption across realtime + fallback paths.
  /// Null for Tier B screens.
  final String? eventId;

  const ScreenReturn({
    required this.route,
    required this.outcome,
    this.updatedFields,
    this.confidenceDelta,
    this.nextCapSuggestion,
    this.stepOutputs,
    this.runId,
    this.stepId,
    this.eventId,
  });

  /// Convenience constructor for a completed return with no side effects.
  const ScreenReturn.completed({
    required String route,
    Map<String, dynamic>? updatedFields,
    double? confidenceDelta,
    String? nextCapSuggestion,
    Map<String, dynamic>? stepOutputs,
    String? runId,
    String? stepId,
    String? eventId,
  }) : this(
          route: route,
          outcome: ScreenOutcome.completed,
          updatedFields: updatedFields,
          confidenceDelta: confidenceDelta,
          nextCapSuggestion: nextCapSuggestion,
          stepOutputs: stepOutputs,
          runId: runId,
          stepId: stepId,
          eventId: eventId,
        );

  /// Convenience constructor for an abandoned return.
  const ScreenReturn.abandoned({
    required String route,
    String? runId,
    String? stepId,
    String? eventId,
  }) : this(
          route: route,
          outcome: ScreenOutcome.abandoned,
          runId: runId,
          stepId: stepId,
          eventId: eventId,
        );

  /// Convenience constructor when user only changed inputs (no completion).
  const ScreenReturn.changedInputs({
    required String route,
    required Map<String, dynamic> updatedFields,
    double? confidenceDelta,
    String? runId,
    String? stepId,
    String? eventId,
  }) : this(
          route: route,
          outcome: ScreenOutcome.changedInputs,
          updatedFields: updatedFields,
          confidenceDelta: confidenceDelta,
          runId: runId,
          stepId: stepId,
          eventId: eventId,
        );

  /// Whether any profile fields were updated during this session.
  bool get hasUpdates => updatedFields != null && updatedFields!.isNotEmpty;

  /// Whether a confidence change should be applied.
  bool get hasConfidenceDelta =>
      confidenceDelta != null && confidenceDelta != 0.0;

  /// Whether a follow-up cap is suggested.
  bool get hasNextCap =>
      nextCapSuggestion != null && nextCapSuggestion!.isNotEmpty;

  /// Whether structured step outputs are provided.
  bool get hasStepOutputs => stepOutputs != null && stepOutputs!.isNotEmpty;

  /// Whether this return carries sequence identity (Tier A screen).
  /// Both runId and stepId must be non-null AND non-empty.
  bool get hasSequenceId =>
      runId != null && runId!.isNotEmpty &&
      stepId != null && stepId!.isNotEmpty;

  /// Whether this return carries an idempotency event ID.
  bool get hasEventId => eventId != null && eventId!.isNotEmpty;

  @override
  String toString() => 'ScreenReturn('
      'route: $route, '
      'outcome: $outcome, '
      'updatedFields: $updatedFields, '
      'confidenceDelta: $confidenceDelta, '
      'nextCapSuggestion: $nextCapSuggestion, '
      'stepOutputs: $stepOutputs, '
      'runId: $runId, '
      'stepId: $stepId, '
      'eventId: $eventId'
      ')';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! ScreenReturn) return false;
    return other.route == route &&
        other.outcome == outcome &&
        other.confidenceDelta == confidenceDelta &&
        other.nextCapSuggestion == nextCapSuggestion &&
        other.runId == runId &&
        other.stepId == stepId &&
        other.eventId == eventId &&
        _mapEquals(other.updatedFields, updatedFields) &&
        _mapEquals(other.stepOutputs, stepOutputs);
  }

  static bool _mapEquals(Map<String, dynamic>? a, Map<String, dynamic>? b) {
    if (a == null && b == null) return true;
    if (a == null || b == null) return false;
    if (a.length != b.length) return false;
    return a.entries.every((e) => b[e.key] == e.value);
  }

  @override
  int get hashCode => Object.hash(
        route,
        outcome,
        confidenceDelta,
        nextCapSuggestion,
        runId,
        stepId,
        eventId,
        updatedFields == null
            ? null
            : Object.hashAll(
                updatedFields!.entries
                    .map((e) => Object.hash(e.key, e.value)),
              ),
        stepOutputs == null
            ? null
            : Object.hashAll(
                stepOutputs!.entries
                    .map((e) => Object.hash(e.key, e.value)),
              ),
      );
}
