/// SequenceTemplate — static definition of a guided multi-screen sequence.
///
/// Immutable. Defined in code, not generated by LLM.
/// The LLM decides the intent; the CODE maps intent → template.
///
/// See: docs/RFC_AGENT_LOOP_STATEFUL.md §3.1–3.2
library;

import 'package:mint_mobile/models/scenario_session.dart';

// ════════════════════════════════════════════════════════════════
//  STEP DEFINITION
// ════════════════════════════════════════════════════════════════

/// One step definition inside a SequenceTemplate.
///
/// Immutable. Maps to a ScreenRegistry intent tag (semantic, not a route).
class SequenceStepDef {
  /// Stable unique identifier for this step (e.g. 'housing_01_affordability').
  final String id;

  /// 1-based display order in the sequence.
  final int order;

  /// Semantic intent tag — maps to ScreenRegistry (e.g. 'housing_purchase').
  /// Resolved to a route via MintScreenRegistry.findByIntentStatic().
  final String intentTag;

  /// ARB key reserved for a future, fully wired progress surface.
  final String titleKey;

  /// Outputs that must be present and usable before this step may advance.
  /// Missing, null, empty, NaN, and infinite values keep the step paused.
  final Set<String> requiredOutputKeys;

  /// Whether this step can be skipped without blocking the sequence.
  final bool isOptional;

  /// Bounded G1 scenario kind required to complete this step.
  ///
  /// Null for every legacy step. Non-null only for the three explicit
  /// scenario bindings; it is never inferred from a route or intent at runtime.
  final ScenarioKind? scenarioKind;

  const SequenceStepDef({
    required this.id,
    required this.order,
    required this.intentTag,
    required this.titleKey,
    this.requiredOutputKeys = const {},
    this.isOptional = false,
    this.scenarioKind,
  });
}

// ════════════════════════════════════════════════════════════════
//  TEMPLATE
// ════════════════════════════════════════════════════════════════

/// Static definition of a guided multi-screen sequence.
///
/// Three V1 templates are pre-defined. New templates should be added
/// here as constants — never generated dynamically by the LLM.
class SequenceTemplate {
  /// Stable unique identifier (e.g. 'housing_purchase').
  final String id;

  /// ARB key for the goal label (e.g. 'sequenceHousingGoal').
  final String goalLabelKey;

  /// Ordered step definitions.
  final List<SequenceStepDef> steps;

  /// Archetype filter. Null = available for all archetypes.
  final String? archetypeFilter;

  /// Semantic topics covered by this sequence (for cohort suppression check).
  /// If any topic is in the user's suppressedTopics, this sequence should not
  /// be proposed (MINT_ANTI_BULLSHIT_MANIFESTO.md §6).
  final Set<String> topics;

  const SequenceTemplate({
    required this.id,
    required this.goalLabelKey,
    required this.steps,
    this.archetypeFilter,
    this.topics = const {},
  });

  // ── V1 PRE-DEFINED TEMPLATES ──────────────────────────────────

  /// Achat immobilier (4 étapes)
  static const housingPurchase = SequenceTemplate(
    id: 'housing_purchase',
    goalLabelKey: 'sequenceHousingGoal',
    steps: [
      SequenceStepDef(
        id: 'housing_01_affordability',
        order: 1,
        intentTag: 'housing_purchase',
        titleKey: 'sequenceHousingStep1',
        requiredOutputKeys: {
          'capacite_achat',
          'fonds_propres_requis',
        },
      ),
      SequenceStepDef(
        id: 'housing_02_epl',
        order: 2,
        intentTag: 'early_pension_withdrawal',
        titleKey: 'sequenceHousingStep2',
        scenarioKind: ScenarioKind.epl,
      ),
      SequenceStepDef(
        id: 'housing_03_fiscal',
        order: 3,
        intentTag: 'cantonal_fiscal_comparator',
        titleKey: 'sequenceHousingStep3',
        requiredOutputKeys: {'impot_retrait'},
      ),
      SequenceStepDef(
        id: 'housing_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceHousingStep4',
        isOptional: true,
      ),
    ],
  );

  /// Optimisation 3a (3 étapes)
  static const optimize3a = SequenceTemplate(
    id: 'optimize_3a',
    goalLabelKey: 'sequence3aGoal',
    steps: [
      SequenceStepDef(
        id: '3a_01_simulator',
        order: 1,
        intentTag: 'simulator_3a',
        titleKey: 'sequence3aStep1',
        requiredOutputKeys: {
          'contribution_annuelle',
          'economie_fiscale',
        },
      ),
      SequenceStepDef(
        id: '3a_02_withdrawal',
        order: 2,
        intentTag: 'tax_optimization_3a',
        titleKey: 'sequence3aStep2',
        requiredOutputKeys: {'gain_echelonnement'},
      ),
      SequenceStepDef(
        id: '3a_03_real_return',
        order: 3,
        intentTag: 'real_return_3a',
        titleKey: 'sequence3aStep3',
      ),
    ],
  );

  /// Préparation retraite (5 étapes)
  static const retirementPrep = SequenceTemplate(
    id: 'retirement_prep',
    topics: {'retirement_deep', 'rente_vs_capital'},
    goalLabelKey: 'sequenceRetirementGoal',
    steps: [
      SequenceStepDef(
        id: 'ret_01_projection',
        order: 1,
        intentTag: 'retirement_projection',
        titleKey: 'sequenceRetirementStep1',
        requiredOutputKeys: {
          'taux_remplacement',
          'gap_mensuel',
        },
      ),
      SequenceStepDef(
        id: 'ret_02_choice',
        order: 2,
        intentTag: 'retirement_choice',
        titleKey: 'sequenceRetirementStep2',
        scenarioKind: ScenarioKind.renteCapital,
      ),
      SequenceStepDef(
        id: 'ret_03_buyback',
        order: 3,
        intentTag: 'lpp_buyback',
        titleKey: 'sequenceRetirementStep3',
        requiredOutputKeys: {'economie_rachat'},
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'ret_04_withdrawal',
        order: 4,
        intentTag: 'withdrawal_sequencing',
        titleKey: 'sequenceRetirementStep4',
        // Educational screen — no computed outputs. Viewing = completed.
      ),
      SequenceStepDef(
        id: 'ret_05_summary',
        order: 5,
        intentTag: '_inline_summary',
        titleKey: 'sequenceRetirementStep5',
        isOptional: true,
      ),
    ],
  );

  /// Pré-retraite complète (11 étapes) — cohorte 53-64.
  ///
  /// Parcours flagship pré-retraite selon COHORT_OS_SPEC.md.
  /// Phase 1: Clarifier (scan LPP, AVS, 3a recap)
  /// Phase 2: Arbitrer (rente vs capital, 3a retrait, hypothèque)
  /// Phase 3: Préparer (rachat LPP, LAMal, succession)
  /// Phase 4: Agir (budget post-retraite, résumé)
  static const preretraiteComplete = SequenceTemplate(
    id: 'preretraite_complete',
    topics: {'retirement_deep', 'withdrawal_sequencing', 'rente_vs_capital', 'lpp_buyback'},
    goalLabelKey: 'sequencePreretraiteGoal',
    steps: [
      // Phase 1: Clarifier
      SequenceStepDef(
        id: 'pre_01_projection',
        order: 1,
        intentTag: 'retirement_projection',
        titleKey: 'sequencePreretraiteStep1',
        requiredOutputKeys: {
          'taux_remplacement',
          'gap_mensuel',
        },
      ),
      SequenceStepDef(
        id: 'pre_02_3a',
        order: 2,
        intentTag: 'simulator_3a',
        titleKey: 'sequencePreretraiteStep2',
        requiredOutputKeys: {
          'contribution_annuelle',
          'economie_fiscale',
        },
      ),
      // Phase 2: Arbitrer
      SequenceStepDef(
        id: 'pre_03_choice',
        order: 3,
        intentTag: 'retirement_choice',
        titleKey: 'sequencePreretraiteStep3',
        scenarioKind: ScenarioKind.renteCapital,
      ),
      SequenceStepDef(
        id: 'pre_04_withdrawal',
        order: 4,
        intentTag: 'tax_optimization_3a',
        titleKey: 'sequencePreretraiteStep4',
        requiredOutputKeys: {'gain_echelonnement'},
      ),
      SequenceStepDef(
        id: 'pre_05_mortgage',
        order: 5,
        intentTag: 'mortgage_amortization',
        titleKey: 'sequencePreretraiteStep5',
        isOptional: true,
      ),
      // Phase 3: Préparer
      SequenceStepDef(
        id: 'pre_06_buyback',
        order: 6,
        intentTag: 'lpp_buyback',
        titleKey: 'sequencePreretraiteStep6',
        requiredOutputKeys: {'economie_rachat'},
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'pre_07_lamal',
        order: 7,
        intentTag: 'lamal_franchise',
        titleKey: 'sequencePreretraiteStep7',
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'pre_08_succession',
        order: 8,
        intentTag: 'succession_patrimoine',
        titleKey: 'sequencePreretraiteStep8',
        isOptional: true,
      ),
      // Phase 4: Agir
      SequenceStepDef(
        id: 'pre_09_budget',
        order: 9,
        intentTag: 'budget_overview',
        titleKey: 'sequencePreretraiteStep9',
        requiredOutputKeys: {
          'revenu_net',
          'charges_totales',
        },
      ),
      SequenceStepDef(
        id: 'pre_10_decaissement',
        order: 10,
        intentTag: 'withdrawal_sequencing',
        titleKey: 'sequencePreretraiteStep10',
      ),
      SequenceStepDef(
        id: 'pre_11_summary',
        order: 11,
        intentTag: '_inline_summary',
        titleKey: 'sequencePreretraiteStep11',
        isOptional: true,
      ),
    ],
  );

  /// Sortir d'une tension financière (4 étapes)
  ///
  /// Parcours flagship #2 — douleur réelle, forte fréquence.
  /// Diagnostic → Budget → Plan de remboursement → Résumé.
  /// Safe Mode: si ratio > 30%, 3a/LPP optimisations désactivées.
  static const financialTension = SequenceTemplate(
    id: 'financial_tension',
    goalLabelKey: 'sequenceTensionGoal',
    steps: [
      SequenceStepDef(
        id: 'tension_01_diagnostic',
        order: 1,
        intentTag: 'debt_ratio',
        titleKey: 'sequenceTensionStep1',
        requiredOutputKeys: {
          'ratio_endettement',
          'marge_mensuelle',
        },
      ),
      SequenceStepDef(
        id: 'tension_02_budget',
        order: 2,
        intentTag: 'budget_overview',
        titleKey: 'sequenceTensionStep2',
        requiredOutputKeys: {
          'revenu_net',
          'charges_totales',
        },
      ),
      SequenceStepDef(
        id: 'tension_03_repayment',
        order: 3,
        intentTag: 'debt_repayment',
        titleKey: 'sequenceTensionStep3',
        requiredOutputKeys: {
          'horizon_mois',
          'versement_mensuel',
        },
      ),
      SequenceStepDef(
        id: 'tension_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceTensionStep4',
        isOptional: true,
      ),
    ],
  );

  /// Premiers pas financiers (3 étapes) — cohorte 18-27.
  ///
  /// Premier salaire → budget de base → 3a découverte.
  static const premiersPas = SequenceTemplate(
    id: 'premiers_pas',
    goalLabelKey: 'sequencePremiersPasGoal',
    steps: [
      SequenceStepDef(
        id: 'pp_01_first_job',
        order: 1,
        intentTag: 'life_event_first_job',
        titleKey: 'sequencePremiersPasStep1',
      ),
      SequenceStepDef(
        id: 'pp_02_budget',
        order: 2,
        intentTag: 'budget_overview',
        titleKey: 'sequencePremiersPasStep2',
        requiredOutputKeys: {
          'revenu_net',
          'charges_totales',
        },
      ),
      SequenceStepDef(
        id: 'pp_03_3a',
        order: 3,
        intentTag: 'simulator_3a',
        titleKey: 'sequencePremiersPasStep3',
        requiredOutputKeys: {
          'contribution_annuelle',
          'economie_fiscale',
        },
      ),
    ],
  );

  /// Densification & protection (4 étapes) — cohorte 38-52.
  ///
  /// Projection retraite → protection invalidité → rachat LPP → résumé.
  static const densification = SequenceTemplate(
    id: 'densification',
    topics: {'retirement_deep', 'lpp_buyback'},
    goalLabelKey: 'sequenceDensificationGoal',
    steps: [
      SequenceStepDef(
        id: 'dens_01_projection',
        order: 1,
        intentTag: 'retirement_projection',
        titleKey: 'sequenceDensificationStep1',
        requiredOutputKeys: {
          'taux_remplacement',
          'gap_mensuel',
        },
      ),
      SequenceStepDef(
        id: 'dens_02_disability',
        order: 2,
        intentTag: 'disability_gap',
        titleKey: 'sequenceDensificationStep2',
      ),
      SequenceStepDef(
        id: 'dens_03_buyback',
        order: 3,
        intentTag: 'lpp_buyback',
        titleKey: 'sequenceDensificationStep3',
        requiredOutputKeys: {'economie_rachat'},
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'dens_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceDensificationStep4',
        isOptional: true,
      ),
    ],
  );

  /// Retraite active (4 étapes) — cohorte 65-74.
  ///
  /// Budget retraite → succession → LAMal → résumé.
  static const retraiteActive = SequenceTemplate(
    id: 'retraite_active',
    topics: {'succession', 'estate_planning'},
    goalLabelKey: 'sequenceRetraiteActiveGoal',
    steps: [
      SequenceStepDef(
        id: 'ra_01_budget',
        order: 1,
        intentTag: 'budget_overview',
        titleKey: 'sequenceRetraiteActiveStep1',
        requiredOutputKeys: {
          'revenu_net',
          'charges_totales',
        },
      ),
      SequenceStepDef(
        id: 'ra_02_succession',
        order: 2,
        intentTag: 'succession_patrimoine',
        titleKey: 'sequenceRetraiteActiveStep2',
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'ra_03_lamal',
        order: 3,
        intentTag: 'lamal_franchise',
        titleKey: 'sequenceRetraiteActiveStep3',
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'ra_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceRetraiteActiveStep4',
        isOptional: true,
      ),
    ],
  );

  /// Couple financier (5 étapes) — cohorte 28-37.
  ///
  /// Mariage vs concubinage, fiscalité couple, 3a couple,
  /// coordination LPP, résumé.
  static const coupleFinancier = SequenceTemplate(
    id: 'couple_financier',
    goalLabelKey: 'sequenceCoupleGoal',
    steps: [
      SequenceStepDef(
        id: 'couple_01_status',
        order: 1,
        intentTag: 'life_event_marriage',
        titleKey: 'sequenceCoupleStep1',
        requiredOutputKeys: {'impact_fiscal_couple'},
      ),
      SequenceStepDef(
        id: 'couple_02_household',
        order: 2,
        intentTag: 'household_couple',
        titleKey: 'sequenceCoupleStep2',
      ),
      SequenceStepDef(
        id: 'couple_03_3a',
        order: 3,
        intentTag: 'simulator_3a',
        titleKey: 'sequenceCoupleStep3',
        requiredOutputKeys: {
          'contribution_annuelle',
          'economie_fiscale',
        },
      ),
      SequenceStepDef(
        id: 'couple_04_fiscal',
        order: 4,
        intentTag: 'cantonal_fiscal_comparator',
        titleKey: 'sequenceCoupleStep4',
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'couple_05_summary',
        order: 5,
        intentTag: '_inline_summary',
        titleKey: 'sequenceCoupleStep5',
        isOptional: true,
      ),
    ],
  );

  /// Naissance & coûts (4 étapes) — cohorte 28-37.
  ///
  /// Impact budget naissance, déductions enfants, 3a famille, résumé.
  static const naissanceCouts = SequenceTemplate(
    id: 'naissance_couts',
    goalLabelKey: 'sequenceNaissanceGoal',
    steps: [
      SequenceStepDef(
        id: 'naissance_01_impact',
        order: 1,
        intentTag: 'life_event_birth',
        titleKey: 'sequenceNaissanceStep1',
      ),
      SequenceStepDef(
        id: 'naissance_02_budget',
        order: 2,
        intentTag: 'budget_overview',
        titleKey: 'sequenceNaissanceStep2',
        requiredOutputKeys: {
          'revenu_net',
          'charges_totales',
        },
      ),
      SequenceStepDef(
        id: 'naissance_03_3a',
        order: 3,
        intentTag: 'simulator_3a',
        titleKey: 'sequenceNaissanceStep3',
        requiredOutputKeys: {
          'contribution_annuelle',
          'economie_fiscale',
        },
      ),
      SequenceStepDef(
        id: 'naissance_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceNaissanceStep4',
        isOptional: true,
      ),
    ],
  );

  // ── INTENT → TEMPLATE MAPPING ─────────────────────────────────

  /// Maps a user intent to a guided sequence template.
  /// Pure function — the LLM never sees sequence IDs.
  /// Returns null for single-screen intents (no sequence needed).
  static SequenceTemplate? templateForIntent(String intentTag) {
    return switch (intentTag) {
      'housing_purchase' => housingPurchase,
      'retirement_choice' || 'retirement_projection' => retirementPrep,
      'preretraite_complete' => preretraiteComplete,
      'life_event_marriage' || 'life_event_concubinage' || 'household_couple' => coupleFinancier,
      'life_event_birth' => naissanceCouts,
      'life_event_first_job' => premiersPas,
      'disability_gap' || 'disability_insurance_flow' => densification,
      'succession_patrimoine' => retraiteActive,
      // 75+ uses retraiteActive (same journey, simplified)
      'simulator_3a' || 'tax_optimization_3a' => optimize3a,
      'debt_ratio' || 'debt_repayment' || 'debt_risk_check' => financialTension,
      _ => null,
    };
  }
}
