/// SequenceTemplate — static definition of a guided multi-screen sequence.
///
/// Immutable. Defined in code, not generated by LLM.
/// The LLM decides the intent; the CODE maps intent → template.
///
/// See: docs/RFC_AGENT_LOOP_STATEFUL.md §3.1–3.2
library;

// ════════════════════════════════════════════════════════════════
//  STEP DEFINITION
// ════════════════════════════════════════════════════════════════

/// One step definition inside a SequenceTemplate.
///
/// Immutable. Maps to a ScreenRegistry intent tag (semantic, not a route).
class SequenceStepDef {
  /// Stable unique identifier for this step (e.g. 'housing_01_affordability').
  final String id;

  /// 1-based display order in the sequence.
  final int order;

  /// Semantic intent tag — maps to ScreenRegistry (e.g. 'housing_purchase').
  /// Resolved to a route via MintScreenRegistry.findByIntentStatic().
  final String intentTag;

  /// ARB key for the step title (displayed in SequenceProgressCard).
  final String titleKey;

  /// Maps output keys from this step's ScreenReturn.stepOutputs
  /// to input keys expected by the next step's prefill.
  ///
  /// Example: {'capacite_achat': 'montant_bien_cible'}
  /// means this step's output 'capacite_achat' becomes the next step's
  /// prefill key 'montant_bien_cible'.
  final Map<String, String> outputMapping;

  /// Whether this step can be skipped without blocking the sequence.
  final bool isOptional;

  const SequenceStepDef({
    required this.id,
    required this.order,
    required this.intentTag,
    required this.titleKey,
    this.outputMapping = const {},
    this.isOptional = false,
  });
}

// ════════════════════════════════════════════════════════════════
//  TEMPLATE
// ════════════════════════════════════════════════════════════════

/// Static definition of a guided multi-screen sequence.
///
/// Three V1 templates are pre-defined. New templates should be added
/// here as constants — never generated dynamically by the LLM.
class SequenceTemplate {
  /// Stable unique identifier (e.g. 'housing_purchase').
  final String id;

  /// ARB key for the goal label (e.g. 'sequenceHousingGoal').
  final String goalLabelKey;

  /// Ordered step definitions.
  final List<SequenceStepDef> steps;

  /// Archetype filter. Null = available for all archetypes.
  final String? archetypeFilter;

  const SequenceTemplate({
    required this.id,
    required this.goalLabelKey,
    required this.steps,
    this.archetypeFilter,
  });

  // ── V1 PRE-DEFINED TEMPLATES ──────────────────────────────────

  /// Achat immobilier (4 étapes)
  static const housingPurchase = SequenceTemplate(
    id: 'housing_purchase',
    goalLabelKey: 'sequenceHousingGoal',
    steps: [
      SequenceStepDef(
        id: 'housing_01_affordability',
        order: 1,
        intentTag: 'housing_purchase',
        titleKey: 'sequenceHousingStep1',
        outputMapping: {
          'capacite_achat': 'montant_bien_cible',
          'fonds_propres_requis': 'montant_necessaire',
        },
      ),
      SequenceStepDef(
        id: 'housing_02_epl',
        order: 2,
        intentTag: 'early_pension_withdrawal',
        titleKey: 'sequenceHousingStep2',
        outputMapping: {
          'montant_epl': 'montant_retrait',
          'impact_rente': 'impact_rente_mensuelle',
        },
      ),
      SequenceStepDef(
        id: 'housing_03_fiscal',
        order: 3,
        intentTag: 'cantonal_fiscal_comparator',
        titleKey: 'sequenceHousingStep3',
        outputMapping: {'impot_retrait': 'impot_retrait'},
      ),
      SequenceStepDef(
        id: 'housing_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceHousingStep4',
        isOptional: true,
      ),
    ],
  );

  /// Optimisation 3a (3 étapes)
  static const optimize3a = SequenceTemplate(
    id: 'optimize_3a',
    goalLabelKey: 'sequence3aGoal',
    steps: [
      SequenceStepDef(
        id: '3a_01_simulator',
        order: 1,
        intentTag: 'simulator_3a',
        titleKey: 'sequence3aStep1',
        outputMapping: {
          'contribution_annuelle': 'contribution_annuelle',
          'economie_fiscale': 'economie_fiscale',
        },
      ),
      SequenceStepDef(
        id: '3a_02_withdrawal',
        order: 2,
        intentTag: 'tax_optimization_3a',
        titleKey: 'sequence3aStep2',
        outputMapping: {'gain_echelonnement': 'gain_echelonnement'},
      ),
      SequenceStepDef(
        id: '3a_03_real_return',
        order: 3,
        intentTag: 'real_return_3a',
        titleKey: 'sequence3aStep3',
      ),
    ],
  );

  /// Préparation retraite (5 étapes)
  static const retirementPrep = SequenceTemplate(
    id: 'retirement_prep',
    goalLabelKey: 'sequenceRetirementGoal',
    steps: [
      SequenceStepDef(
        id: 'ret_01_projection',
        order: 1,
        intentTag: 'retirement_projection',
        titleKey: 'sequenceRetirementStep1',
        outputMapping: {
          'taux_remplacement': 'taux_remplacement',
          'gap_mensuel': 'gap_mensuel',
        },
      ),
      SequenceStepDef(
        id: 'ret_02_choice',
        order: 2,
        intentTag: 'retirement_choice',
        titleKey: 'sequenceRetirementStep2',
        outputMapping: {'decision_mixte': 'decision_mixte'},
      ),
      SequenceStepDef(
        id: 'ret_03_buyback',
        order: 3,
        intentTag: 'lpp_buyback',
        titleKey: 'sequenceRetirementStep3',
        outputMapping: {'economie_rachat': 'economie_rachat'},
        isOptional: true,
      ),
      SequenceStepDef(
        id: 'ret_04_withdrawal',
        order: 4,
        intentTag: 'withdrawal_sequencing',
        titleKey: 'sequenceRetirementStep4',
        // Educational screen — no computed outputs. Viewing = completed.
      ),
      SequenceStepDef(
        id: 'ret_05_summary',
        order: 5,
        intentTag: '_inline_summary',
        titleKey: 'sequenceRetirementStep5',
        isOptional: true,
      ),
    ],
  );

  /// Sortir d'une tension financière (4 étapes)
  ///
  /// Parcours flagship #2 — douleur réelle, forte fréquence.
  /// Diagnostic → Budget → Plan de remboursement → Résumé.
  /// Safe Mode: si ratio > 30%, 3a/LPP optimisations désactivées.
  static const financialTension = SequenceTemplate(
    id: 'financial_tension',
    goalLabelKey: 'sequenceTensionGoal',
    steps: [
      SequenceStepDef(
        id: 'tension_01_diagnostic',
        order: 1,
        intentTag: 'debt_ratio',
        titleKey: 'sequenceTensionStep1',
        outputMapping: {
          'ratio_endettement': 'ratio_endettement',
          'marge_mensuelle': 'marge_mensuelle',
        },
      ),
      SequenceStepDef(
        id: 'tension_02_budget',
        order: 2,
        intentTag: 'budget_overview',
        titleKey: 'sequenceTensionStep2',
        outputMapping: {
          'revenu_net': 'revenu_net',
          'charges_totales': 'charges_totales',
        },
      ),
      SequenceStepDef(
        id: 'tension_03_repayment',
        order: 3,
        intentTag: 'debt_repayment',
        titleKey: 'sequenceTensionStep3',
        outputMapping: {
          'horizon_mois': 'horizon_mois',
          'versement_mensuel': 'versement_mensuel',
        },
      ),
      SequenceStepDef(
        id: 'tension_04_summary',
        order: 4,
        intentTag: '_inline_summary',
        titleKey: 'sequenceTensionStep4',
        isOptional: true,
      ),
    ],
  );

  // ── INTENT → TEMPLATE MAPPING ─────────────────────────────────

  /// Maps a user intent to a guided sequence template.
  /// Pure function — the LLM never sees sequence IDs.
  /// Returns null for single-screen intents (no sequence needed).
  static SequenceTemplate? templateForIntent(String intentTag) {
    return switch (intentTag) {
      'housing_purchase' => housingPurchase,
      'retirement_choice' || 'retirement_projection' => retirementPrep,
      'simulator_3a' || 'tax_optimization_3a' => optimize3a,
      'debt_ratio' || 'debt_repayment' || 'debt_risk_check' => financialTension,
      _ => null,
    };
  }
}
